= 도메인

* 하나의 속성이 가질 수 있는 동일한 유형의 원자값들의 집합
* 릴레이션 스키마는 릴레이션 인스턴스의 각 필드의 도메인을 명세(도메인 제약조건)
* 프로그래밍 언어 관점에서 필드의 데이터 타입을 의미
* `R(f~i~:D1, … f~n~:Dn)` 을 릴레이션 스키마라고 하고,  각 `f~i~, 1 ≤ i ≤ n` 에 대한 이름이 `D~i~` 인 도메인에 대한 집합을 `Dom~i~` 이라고 할 때, 도메인 제약조건을 만족하는 R의 인스턴스는 다음과 같이 n개의 필드를 가진 투플의 한 집합이 됨

`{ <f~i~: d~i~, … f~n~: d~n~> | d~1~ ∈ Dom~1~, … d~n~ ∈ Dom~n~}`

---

릴레이션 스키마는 릴레이션 인스턴스의 각 필드, 즉 열의 도메인을 명세합니다. 스키마 내의 이러한 `도메인 제약조건(Domain Constraint)` 은 그 릴레이션 인스턴스가 지켜야 하는 중요한 조건으로서, 어떤 열의 값은 해당 도메인으로부터 나와야 한다는 것을 의미합니다. 따라서 어떤 필드의 도메인은 프로그래밍 언어 관점에서 보면 해당 필드의 타입으로서, 그 필드에 나올 수 있는 값을 제한합니다.

정식으로 표현하자면, `R(f~1~:D~1~, … f~n~:D~n~)` 을 릴레이션 스키마라고 하고,  각 `f~i~, 1 ≤ i ≤ n` 에 대한 이름이 `D~i~` 인 도메인에 대한 집합을 `Dom~i~` 라고 할 때, 도메인 제약조건을 만족하는 R의 인스턴스는 다음과 같이 n개의 필드를 가진 투플의 한 집합이 됩니다.

`{ <f~i~: d~i~, … f~n~: d~n~> | d~1~ ∈ Dom~1~, … d~n~ ∈ Dom~n~}`

여기에서 < … >는 한 투플의 필드들을 표시하며 중괄호 { … }는 집합(여기에서는 투플의 집합)을 나타냅니다. 수직 막대 | 는 ‘다음을 만족하는'을 의미하고, 기호 ∈ 는 ‘포함된다’를 나타내며, 수직 막대의 오른쪽은 이 집합에 속하는 투플의 필드 값들이 반드시 지켜야 하는 조건입니다.

link:./11_relational_database.adoc[다음: 관계형 데이터베이스]
