= 개체 무결성

* 한 개체(투플)는 다른 개체들과 명확히 구분되어야 함
* 모든 릴레이션에 속한 필드들의 최소 부분집합이 각 투플에 대해 고유 식별자가 되어야 함
* 키 제약조건(Key Constraint)으로 개체 무결성을 유지
** 릴레이션에 속한 필드들의 최소 부분 집합이 각 투플에 고유한 식별자가 되어야 함
** 키 제약조건에서 투플을 식별하는 부분집합을 키(Key)라고 함
* 키(Key)
** 적법한 인스턴스의 서로 다른 두 투플은 한 키에 속하는 모든 필드 전체에 대해 동일한 값을 가질 수 없음
** 키를 구성하는 필드 집합의 어떠한 부분집합도 투플에 대해 유일한 식별자가 될 수 없음
* 수퍼 키(Super Key) +
유일성을 만족하는, 필드들의 부분 집합
* 후보 키(Candidate Key) +
유일성과 최소성을 만족하는 수퍼키 집합의 부분 집합
* 기본 키(Primary Key) +
특정 투플을 구별하기 위해 후보 키에서 선택된 고유한 식별자

---

아래와 같은 릴레이션 스키마를 가진 릴레이션 인스턴스의 각 투플이 지켜야 할 제약조건을 생각해 봅시다.

_학생 (학번: 문자열, 이름: 문자열, 로그인: 문자열, 나이: 정수, 평점 평균: 실수)_

학생 릴레이션에서 학생은 동일한 학번을 가질 수 없습니다. 학교에 재학중인 모든 학생은 데이터베이스 내에서 유일하게 구분되어야 하고, 이는 학교 데이터베이스에서 지켜야 할 중요한 무결성 제약조건의 하나입니다. 릴레이션에서 각 투플은 각각의 학생 개체를 나타내고, 한 학생 개체는 다른 학생 개체와 명확히 구분되어야 합니다. 이를 각 개체는 데이터베이스 내에서 유일해야 한다는 의미에서 `개체 무결성(Entity Integrity)` 라고 합니다.

개체 무결성을 위해 `키 제약조건(Key Constraint)` 을 사용합니다. 키 제약조건은 릴레이션에 속한 필드들의 어떠한 최소 부분집합이 각 투플에 대해 고유한 식별자가 된다는 선언입니다. 키 제약조건에서 투플을 유일하게 식별하는 필드 집합을 그 릴레이션에 대한 키(Key)라고 합니다.

== 키(Key)
. 적법한 인스턴스의 서로 다른 두 투플은 한 키에 속하는 모든 필드 전체에 대해 동일한 값을 가질 수 없다.
. 키를 구성하는 필드 집합의 어떠한 부분집합도 투플에 대한 유일 식별자가 될 수 없다.

릴레이션 인스턴스가 적법한 인스턴스라면 키 필드의 값이 인스턴스 내의 각 투플을 유일하게 식별할 수 있어야 합니다. 데이터베이스 관리자가 키 제약조건을 명세 할 때에는 이것 떄문에 정확한 투플 집합을 저장하는데 방해가 되지 않아야 합니다. 만약 학교의 규칙이 같은 학번은 허용할 수 없으나 같은 이름을 가진 학생은 허용할 수 있다고 할 때, 이름 필드가 키로 지정되면 같은 이름을 가진 학생은 학교에 존재할 수 없게 되어 요구사항을 위반하게 됩니다.

위와 같은 요구사항을 가졌다면, 필드의 부분 집합 {학번, 이름}은 학생 릴레이션의 키가 될 수 없습니다. 요구사항에 따르면 학번은 투플에 대해 유일 식별자가 될 수 있기 때문입니다. 

* **슈퍼 키(Super Key)**
슈퍼 키는 릴레이션에 존재하는, 유일성을 만족하는 필드들의 부분 집합입니다. 필드의 부분집합인 {학번, 이름}은 그 자체로 필드를 식별할 수 있습니다. 학번 필드가 투플을 유일하게 식별할 수 있기 때문입니다. 
* **후보 키(Candidate Key)**
학생 릴레이션에서 학번 필드 이외에도 로그인 필드 또한 키가 될 수 있습니다. 이와 같은 키들을 후보 키라고 합니다. 후보 키는 릴레이션에 존재하는 전체 필드의 부분 집합으로서, 유일성과 최소성을 만족해야 합니다. 키의 두 가지 조건을 만족하는 릴레이션 필드의 부분집합을 후보 키라고 합니다. 
* **기본 키(Primary Key)**
후보 키 중 하나를 지정하여 릴레이션 인스턴스 내에서 투플의 유일성을 식별할 수 있도록 지정된 키를 기본 키라고 합니다. 

관계 모델에서 어떤 투플은 데이터베이스의 다른 곳에서 그 기본 키의 필드 값으로 참조될 수 있습니다. 과목을 수강하는 학생의 목록을 나타내는 수강이라는 릴레이션이 존재할 때, 수강 릴레이션은 과목에 참여하는 학생 목록을 나타내기 위해서 학생 테이블의 학번 필드를 참조할 수 있습니다. 

이론상으로는 한 투플을 지칭할 때 기본 키뿐 아니라 어떠한 키도 사용할 수 있습니다. 하지만 DBMS가 기본 키를 예상하고 그에 대해 최적화를 하므로, 기본 키를 사용합니다.

link:./16_referential_integrity.adoc[다음: 참조 무결성]