= SQL 루틴 개요

* SQL 프로시저 언어 구문을 포함하여 SQL로만 로직이 구현된 루틴
* 작성시 사용되는 CREATE 내에 해당 루틴-본문 로직을 포함함
* SQL 프로시저, SQL 함수 등을 작성할 수 있음
* 모두 SQL에서 구현되지만 각 루틴 함수 타입에는 다른 기능이 있음

---

SQL 루틴은 SQL 프로시저 언어(SQL Procedural Language) statement를 포함하여 SQL로만 로직이 구현되어 있는 루틴을 말합니다.

SQL 루틴은 SQL 호출 루틴(SQL Invoked-routine)은 프로시저(Procedure) 또는 함수(Function)의 일반적인 이름입니다. SQL 루틴은 일부 스키마 또는 데이터베이스에 종속되며 표준 SQL 문을 사용하여 생성되고 변경되며 삭제됩니다.

SQL에서 루틴은 루틴 이름, 파라미터, 본문 등 세 가지 항목으로 구성됩니다. SQL 프로시저는 CALL 문으로 호출되는 루틴이며, 입력 파라미터, 출력 파라미터가 있을 수 있습니다. SQL 함수는 <루틴 호출(Routine invocation)>에 의해 호출될 때 값을 반환하는 루틴입니다. SQL 함수에는 입력 파라미터만 있고, 결과를 반환합니다. 

루틴의 장점은 아래와 같습니다.

* 유연성(Flexibility) +
제약 조건이나 트리거보다 루틴을 사용하면 더 많은 작업을 수행할 수 있으며, 다 다양한 시나리오에서 작업을 수행할 수 있습니다.
* 효율성(Efficiency) +
일반적인 SQL 문을 최적화된 루틴으로 작성할 수 있습니다.
* 깔끔함(Cleanliness) +
같은 SQL 코드를 두 번 작성하는 것을 방지할 수 있습니다.
* 공유(Share) +
루틴은 서버에서 캐시되고 공유되어 모든 프로그래머가 액세스 할 수 있습니다. 자주 사용되는 코드들을 따로 공유할 필요가 없습니다.

SQL 루틴은 아래의 18가지 정보가 포함된 기술어구(descriptor)로 정의됩니다.

1.	루틴의 이름. +
이름은 전체 DBMS에서 고유하지 않아도 됩니다. 해당 루틴이 속한 스키마 또는 데이터베이스에 의해 정규화됩니다.
2.	루틴이 속한 스키마의 이름 +
루틴이 속한 스키마의 이름은 루틴의 고유한 이름에 포함됩니다.
3.	루틴의 외부 루틴 이름
4.	루틴의 AuthorizationID
5.	루틴의 SQL 경로
6.	루틴이 작성되는 언어
7.	루틴의 파라미터 정의 +
파라미터는 파라미터의 이름, 파라미터의 타입, 파라미터의 순서(위치), 파라미터의 입력/출력 여부가 포함됩니다.
8.	루틴이 호출 프로시저(Invoked procedure)인지 호출 함수(invoked function)인지의 여부
9.	동적 결과 세트의 최대 수
10.	루틴의 결정적(deterministic)인지 또는 비 결정적(non-deterministic)인지의 여부
11.	루틴이 데이터를 수정할 수 있는지, 읽을 수 있는지, SQL을 포함할 수 있는지의 여부
12.	루틴의 return 타입
13.	루틴이 유형 보존 함수(type-preserving function)인지 변경자 함수(mutator function)인지의 여부
14.	루틴의 결과 파라미터(유형 보존 함수인 경우)
15.	루틴의 생성 타임 스탬프
16.	루틴이 널 호출 루틴(함수)인지의 여부
17.	루틴의 마지막 변경 타임 스탬프
18.	루틴 본문 +
루틴이 실행될 때 실행되는 SQL 프로시저 명령문(SQL 루틴의 경우) 또는 루틴이 실행될 때 실행되는 호스트 언어 명령문(외부 루틴의 경우)이 포함됩니다.

SQL 루틴의 생성과 수정, 삭제는 표준 SQL의 DDL과 같습니다. 생성을 위해 CREATE, 수정을 위해 ALTER, 삭제를 위해 DROP을 사용합니다.
SQL 루틴에는 크게 아래 세 가지 종류가 있으며, 프로시저와 함수가 많이 사용됩니다.

* SQL PROCEDURE
* SQL FUNCTION
* SQL METHOD

link:./04_create_routine.adoc[다음: SQL 루틴 생성]
