= 비용 모델 개요

* 데이터베이스에서는 질의가 요청될 때 여러 실행계획을 세우고 최적화된 방법을 찾아 실행
* 쿼리 최적화기는 쿼리 기반, 비용 기반 등의 모델로 실행 계획을 비교
* 비용 측정
** 데이터 페이지의 개수 B, 페이지에 속한 레코드의 개수 R, 디스크 페이지를 하나를 읽는 시간을 D로 가정
** 디스크 페이지 하나를 쓰는데 걸리는 평균 시간 D, 한 레코드를 처리하는데 걸리는 시간 C
** 한 레코드에 해시 함수를 적용하는데 걸리는 시간 H
* 여기에서는 파일 입출력 비용만 감안하여 파일 조직 별 비용을 비교

---

데이터베이스 관리 시스템은 질의가 요청될 때 여러 실행 계획을 세우고 비교하여 최적화된 방법을 찾아 실행합니다. 이때 실행 계획을 세우고 비교하여 최적화된 방법을 찾아내는 DBMS 구성 요소를 **질의 최적화기(Query Optimizer)**라고 부릅니다. SQL 언어로 결과 집합을 요구하면 결과집합을 찾는 처리 경로는 질의 최적화기가 생성하며, 생성한 처리 계획을 실행 계획이라고 부릅니다. 

질의 최적화기는 두 가지로 나눌 수 있습니다.

* 규칙 기반 옵티마이저(Rule-Based Optimizer) +
휴리스틱 옵티마이저라고도 불리며, 미리 정해놓은 규칙에 따라 액세스 경로를 평가하고 실행 계획을 선택합니다. 규익은 액세스 경로별 우선순위로서, 인덱스 구조, 연산자, 조건절 형태가 순위를 결정짓는 주요 요인입니다.
* 비용기반 옵티마이저(Cost-Based Optimizer) +
쿼리를 수행하는데 소요되는 일의 양 또는 시간을 기반으로 최적화된 실행 경로를 계산합니다. 미리 구해놓은 테이블과 인덱스에 대한 통계정보를 기초로 각 실행 단계별 예상 비용을 산정하고, 이를 합산한 비용이 가장 낮은 실행 계획을 선택합니다. 레코드 개수, 블록 개수, 평균 행 길이, 컬럼 값의 수, 컬럼 값 분포등을 사용하며 하드웨어적인 특성인 CPU 속도, 디스크 I/O 속도 등을 사용합니다. 대부분의 RDBMS는 비용기반 쿼리 옵티마이저를 채택합니다.

이 장에서는 여러 감안 요소 중 파일 조직별 비용을 알아보기 위해 파일 조직별 입출력 비용만 감안하여 파일 조직별 비용을 비교합니다.

* B: 데이터 페이지의 개수
* R: 페이지에 속한 레코드의 개수 
* D: 디스크 페이지를 하나를 읽는 시간
* C: 한 레코드를 처리하는데 걸리는 시간 
* H: 한 레코드에 해시 함수를 적용하는데 걸리는 시간

link:./04_file_org.adoc[다음: 파일 조직법 비교 기준 연산]