= 정렬 파일

* 특정 필드를 기준으로 정렬된 파일
* 스캔 +
힙 파일과 다르지 않음. B(D+RC)
* 동등 셀렉션 +
정럴 기준 필드로 검색할 경우 이진 탐색으로 _Dlog~2~B_ + _Clog~2~R_. 정렬 필드가 아닌 경우 스캔과 동일
* 범위 셀렉션 +
정렬 기준 필드로 검색할 경우 첫 레코드를 찾는데 동등 셀렉션과 동일. 이후 범위내 스캔
* 삽입 +
정렬 순서를 유지하기 위해 레코드가 삽입될 위치를 검색 후 레코드 추가. 후속 페이지를 모두 로드하여 다시 저장. 탐색 비용 + B(D + RC)

---

정렬 파일은 특정 필드를 기준으로 정렬된 파일입니다. 정렬 파일에서 각각의 연산에 대한 비용은 아래와 같이 계산됩니다.

* 스캔  +
모든 페이지를 검사해야 하므로 B(D +RC) 입니다. 무순서 파일과 다를 바가 없으며, 레코드 검색 순서는 정렬 순서를 따릅니다.
* 동등 셀렉션 +
정렬 기준 필드에 대해 검색을 수행할 경우 log~2~B의 이진 탐색으로 검색 결과 페이지가 들어있는 첫 페이지를 구할 수 있습니다. 각 단계마다 한 번의 디스크 입출력과 두 번의 비교가 수행됩니다. 첫 페이지를 찾고나면 페이지의 첫 레코드는 Clog~2~R의 비용으로 찾을 수 있습니다. 총 비용은 Dlog~2~B + Clog~2~R로 힙 파일보다 월등히 효율이 좋습니다.
+
정렬 기준 필드가 검색 대상이 아닌 경우 스캔과 동일합니다.
* 범위 셀렉션  +
정렬 기준 필드에 대해 검색을 수행할 경우 첫 페이지를 찾는 시간은 동등 셀렉션과 동일합니다. 이후 범위내 스캔의 비용이 발생합니다.
정렬 기준 필드가 검색 대상이 아닌 경우 스캔과 동일합니다.
* 삽입 +
정렬 순서를 유지하기 위해 레코드가 삽입될 위치를 찾아야 합니다. 찾은 위치에 레코드를 추가하고, 후속 페이지들을 모두 로드해서 새로 저장해야 합니다(파일에 비어있는 슬롯이 없다고 가정하면, 기존 레코드들은 모두 한 슬롯씩 뒤로 이전해야 하기 때문). 레코드는 평균적으로 파일의 중간 부분에 삽입된다고 할 수 있으므로, 새 레코드를 추가한 다음에는 찾는 비용 + 2 x (0.5B(D + RC)) 만큼의 비용이 듭니다. 총 비용은 탐색 비용 + B(D + RC)입니다.
* 삭제 +
레코드를 탐색해서 그 페이지로부터 레코드를 삭제한 후, 수정된 페이지를 다시 기록해야 합니다. 또한 그 빈 공백을 정리해야 하기 때문에 삭제된 레코드를 한 자리씩 앞으로 이동해야 하므로 이후 페이지를 모두 로드하여 다시 써야 합니다. 삭제의 비용은 삽입과 마찬가지로 탐색 비용 + B(D + RC)입니다.

link:./07_hash_file.adoc[다음: 해시(Hash) 파일]