= Lab 4 : 인덱스 생성

== 연습 1 클러스터드 인덱스 확인

이 연습에서는 Module03에서 생성한 테이블에 인덱스를 생성하고 데이터를 삽입한 후 동작을 확인합니다. 아래 절차에 따릅니다.

=== Product 테이블에 데이터 삽입
1.	macOS와 Ubuntu에서는 터미널, Windows에서는 명령 프롬프트를 실행합니다.
2.	아래 명령을 실행하여 MySQL 콘솔에 접근합니다.
+
----
$ mysql -U root -P
Enter password:
----
3.	아래 명령을 수행하여 DBMS에 생성된 데이터베이스를 확인합니다.
+
----
mysql> show databases;
----
+
명령의 실행 결과는 아래와 유사할 것입니다:
+
----
+--------------------+
| Database           |
+--------------------+
| Module02           |
| Module03           |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
----
+
4.	아래 질의를 실행하여 연결 컨텍스트를 Module03 데이터베이스로 변경합니다.
+
----
mysql> use Module03;
----
질의가 성공적으로 수행되면, 아래와 같은 메시지가 표시됩니다.
+
----
Database changed
----
+
5.	아래 질의를 수행하여 Product 테이블의 스키마를 확인합니다.
+
----
mysql> desc Product;
----
+
질의가 실행되면 결과는 아래와 같습니다.
+
----
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| ProductNo   | int          | NO   | PRI | NULL    |       |
| ProductName | varchar(100) | NO   |     | NULL    |       |
| UnitPrice   | int          | NO   |     | 0       |       |
| Description | text         | YES  |     | NULL    |       |
| CategoryNo  | int          | YES  | MUL | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
5 rows in set (0.00 sec)
----
+
6. 다음 질의를 실행하여 Product 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Product VALUES (1, 'Fellowship of the Rings', 25000, 'Book of Legend', 1);
----
+
질의는 실패합니다. 오류 메시지는 아래와 같습니다.
+
----
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`Module03`.`Product`, CONSTRAINT `fk_Product_CategoryID` FOREIGN KEY (`CategoryNo`) REFERENCES `Category` (`CategoryNo`))
----
7. 아래 두 질의를 수행하여 Category 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Category VALUES(1, 'Novel');
INSERT INTO Category VALUES(2, 'Science');
----
8.	아래 질의를 수행하여 삽입된 데이터를 확인합니다.
+
----
mysql> SELECT * FROM Category;
----
질의가 실행되면, 결과는 아래와 같을 것입니다.
+
----
+------------+--------------+
| CategoryNo | CategoryName |
+------------+--------------+
|          1 | Novel        |
|          2 | Science      |
+------------+--------------+
2 rows in set (0.00 sec)
----
+
9. 다음 질의를 수행하여 Product 테이블에 데이터를 삽입합니다.
+
----
INSERT INTO Product VALUES (1, 'Fellowship of the Rings', 25000, 'Book of Legend', 1);
----
+
질의가 실행되면, 결과는 아래와 같을 것입니다.
+
----
Query OK, 1 row affected (0.02 sec)
----
+
10.	아래 질의를 수행하여 삽입된 데이터를 확인합니다.
+
----
mysql> SELECT * FROM Product;
----
+
질의가 실행되면 결과는 아래와 같을 것입니다.
+
----
+-----------+-------------------------+-----------+----------------+------------+
| ProductNo | ProductName             | UnitPrice | Description    | CategoryNo |
+-----------+-------------------------+-----------+----------------+------------+
|         1 | Fellowship of the Rings |     25000 | Book of Legend |          1 |
+-----------+-------------------------+-----------+----------------+------------+
1 row in set (0.00 sec)
----
11.	아래 질의를 수행하여 Product 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Product VALUES (1, 'The Two Towers', 25000, 'Book of Legend', 1);
----
+
질의가 실패합니다. 오류 메시지는 아래와 같습니다.
+
----
ERROR 1062 (23000): Duplicate entry '1' for key 'Product.PRIMARY'
----
12.	아래 질의를 수행하여 Product 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Product VALUES (1, 'The Two Towers', 25000, 'Book of Legend', 1);
----
질의가 성공적으로 수행되면, 메시지는 아래와 같습니다.
+
----
Query OK, 1 row affected (0.01 sec)
----
+
13.	아래 질의를 순서대로 수행하여 Product 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Product VALUES (4, 'Science', 45000, 'Book of Legend', 2);
INSERT INTO Product VALUES (5, 'Newton', 8000, 'Science Magazine', 2);
INSERT INTO Product VALUES (3, 'Return of the King', 25000, 'Book of Legend', 1);
----
+
14.	아래 질의를 수행하여 Product 테이블에 삽입된 데이터를 확인합니다.
+
----
mysql> SELECT * FROM Product;
----
+
결과는 아래와 같습니다. 데이터 삽입 순서와 관계없이 Product 테이블의 기본 키(Primary Key)인 ProductNo 필드를 기준으로 정렬됩니다.
+
----
+-----------+-------------------------+-----------+------------------+------------+
| ProductNo | ProductName             | UnitPrice | Description      | CategoryNo |
+-----------+-----------__------------+-----------+------------------+------------+
|         1 | Fellowship of the Rings |     25000 | Book of Legend   |          1 |
|         2 | The Two Towers          |     25000 | Book of Legend   |          1 |
|         3 | Return of the King      |     25000 | Book of Legend   |          1 |
|         4 | Science                 |     45000 | Book of Legend   |          2 |
|         5 | Newton                  |      8000 | Science Magazine |          2 |
+-----------+-------------------------+-----------+------------------+------------+
5 rows in set (0.00 sec)
----

== 연습 2 넌 클러스터드 인덱스 생성 및 확인

이 연습에서는 Module03 데이터베이스의 Product 테이블의 CategoryNo 컬럼에 대해 인덱스를 생성하고 확인합니다. 아래 절차에 따릅니다.

1.	아래 질의를 수행하여 현재 데이터베이스 컨텍스트를 확인합니다.
+
----
mysql> SELECT database();
----
+
결과는 아래와 같습니다.
+
----
+------------+
| database() |
+------------+
| Module03   |
+------------+
1 row in set (0.00 sec)
----
+
2.	아래 질의를 수행하여 Product 테이블의 CategoyNo 컬럼에 인덱스를 생성합니다.
+
----
mysql> CREATE INDEX idx_Product_CategoryNo ON Product(CategoryNo);
----
+
질의가 성공적으로 실행되면, 결과는 아래와 같습니다.
+
----
Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0
----
+
3.	아래 질의를 수행하여 Product 테이블의 인덱스를 확인합니다.
+
----
mysql> show index FROM Product;
----
결과는 아래와 같습니다.
 
4.	아래 두 질의를 순서대로 실행하여 Product 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Product VALUES (7, 'World War Z', 20000, 'Most interesting book', 1);
INSERT INTO Product VALUES (6, 'Bourne Identity', 18000, 'Spy Novel', 1);
----
5.	아래 질의를 수행하여 Product 테이블의 데이터를 확인합니다.
+
----
mysql> SELECT * FROM Product;
----
+
명령이 수행되면 결과는 아래와 같습니다. Product 테이블의 기본 키 인덱스인 ProductNo를 기준으로 정렬됩니다.
+
----
+-----------+-------------------------+-----------+-----------------------+------------+
| ProductNo | ProductName             | UnitPrice | Description           | CategoryNo |
+-----------+-------------------------+-----------+-----------------------+------------+
|         1 | Fellowship of the Rings |     25000 | Book of Legend        |          1 |
|         2 | The Two Towers          |     25000 | Book of Legend        |          1 |
|         3 | Return of the King      |     25000 | Book of Legend        |          1 |
|         4 | Science                 |     45000 | Book of Legend        |          2 |
|         5 | Newton                  |      8000 | Science Magazine      |          2 |
|         6 | Bourne Identity         |     18000 | Spy Novel             |          1 |
|         7 | World War Z             |     20000 | Most interesting book |          1 |
+-----------+-------------------------+-----------+-----------------------+------------+
7 rows in set (0.00 sec)
----
+
6. 아래 질의를 수행하여 Product 테이블의 데이터를 확인합니다.
+
----
mysql> SELECT * FROM Product WHERE CategoryNo > 0;
----
명령이 수행되면, 결과는 아래와 같습니다. Product 테이블의 CategoryNo 컬럼에 대해 생성된 보조 키 인덱스를 기준으로 정렬됩니다. (시스템 상황에 따라, index를 사용한 정렬에는 더 많은 열이 필요할 수 있습니다)
+
----
+-----------+-------------------------+-----------+-----------------------+------------+
| ProductNo | ProductName             | UnitPrice | Description           | CategoryNo |
+-----------+-------------------------+-----------+-----------------------+------------+
|         1 | Fellowship of the Rings |     25000 | Book of Legend        |          1 |
|         2 | The Two Towers          |     25000 | Book of Legend        |          1 |
|         3 | Return of the King      |     25000 | Book of Legend        |          1 |
|         6 | Bourne Identity         |     18000 | Spy Novel             |          1 |
|         7 | World War Z             |     20000 | Most interesting book |          1 |
|         4 | Science                 |     45000 | Book of Legend        |          2 |
|         5 | Newton                  |      8000 | Science Magazine      |          2 |
+-----------+-------------------------+-----------+-----------------------+------------+
7 rows in set (0.00 sec)
----
link:./16_review.adoc[다음: 검토]