= 데이터베이스 보안 개요

* 안전한 데이터베이스 응용 설계 +
* 보안(Security) +
정보가 권한 없는 사용자에게 누출되어서는 안된다
* 무결성(Integrity) +
권한 있는 사용자에게만 데이터의 수정이 허용된다
* 가용성(Availability) +
권한 있는 사용자의 접근이 제한되어서는 안된다
* 명확하고 일관성 있는 보안 정책의 설정 필요
* DBMS는 데이터 보안에 대한 메커니즘을 제공

---

데이터베이스 관리 시스템은 한 기업체의 모든 측면에 대한 정보를 저장합니다. 따라서 DBMS에 있는 데이터는 조직체의 사업적인 분야에 있어 가장 중요한 부분인 경우가 많으며, 회사의 자산으로 취급됩니다. 데이터를 본질적인 가치를 보호하는 일 이외에도 회사는 사적 정보에 대한 기밀을 보장하거나 기타 여러가지 이유로 어떤 사용자 그룹에게 누출되어서는 안되는 데이터에 대해 접근을 통제할 수 있는 여러 방안들을 강구해야 합니다.
안전한 데이터베이스 응용을 설계할 때 고려하는 목표는 다음과 같은 세 가지가 있습니다.

* 1. 보안(Securty) +
정보가 권한 없는 사용자에게 누출되어서는 안된다. 예를 들어 학생이 다른 학생의 점수를 볼 수 없도록 해야 한다.
* 2. 무결성(Integrity) +
권한이 있는 사용자에 대해서만 데이터 수정이 허용되어야 한다. 예를 들어 학생들이 자기 점수는 볼 일이 있으나 그 점수를 수정할 수는 없도록 해야 한다.
* 3. 가용성(Availability) +
권한 있는 사용자의 접근이 거부되어서는 안된다. 예를 들어 교수가 어떤 학점을 바꾸고자 하면 그렇게 할 수 있도록 허용되어야 한다.

이런 목표들을 달성하기 위하여, 명확하고 일관성이 있는 보안 정책을 수립하여 어떤 보안 사항들을 집행하여야 하는지를 기술해야 합니다. 특히 데이터의 어떤 부분을 보호하고 또 어떤 사용자가 어떤 데이터 부분을 접근할 수 있는지를 결정해야 합니다. 그 다음으로 바탕이 되는 DBMS등의 보안 메커니즘을 활용하여 이 정책을 집행해야 합니다. 

link:./04_user_object.adoc[다음: User 개체]