= 재량 접근 제어

* SQL1999 표준은 GRANT 명령과 REVOKE 명령을 통해 재량 접근 제어를 지원
* GRANT
** 사용자에게 기반 테이블이나 뷰에 대한 특권을 부여

[source, sql]
----
GRANT <특권> ON <개체> TO <사용자> [WITH GRANT OPTIONS]
----

* REVOKE
** 사용자에게 부여된 특권 허여를 취소

[source, sql]
----
GRANT <특권> ON <개체> FROM <사용자> [CASCADE]
----

---

SQL 1999는 GRANT 명령과 REVOKE 명령을 통해 재량 접근 제어를 지원합니다. GRANT 명령은 사용자들에게 기반 테이블이나 뷰에 대한 특권을 부여합니다. 이 명령의 구문은 아래와 같습니다.

[source, sql]
----
GRANT <특권> ON <개체> TO <사용자> [WITH GRANT OPTIONS]
----

명세할 수 있는 특권의 종류는 아래와 같습니다. 

* SELECT +
'개체'로 명시된 테이블의 모든 필드들을 접근(판독)할 수 있는 특권입니다. 여기에는 ALTER TABLE 명령으로 나중에 추가된 필드들도 포함됩니다.
* INSERT (필드 이름) +
'개체' 테이블의 명세된 필드에 값을 넣은 투플을 삽입할 수 있는 특권입니다. 나중에 추가되는 필드들을 포함하여 모든 필드에 대해 이 권한을 허가하려면 단순히 INSERT로 지정하면 됩니다.
* UPDATE (필드 이름) +
'개체' 테이블의 명세된 필드에 값을 넣은 투플의 컬럼을 갱신할 수 있는 특권입니다. 나중에 추가되는 필드들을 포함하여 모든 필드에 대해 이 권한을 허가하려면 단순히 UPDATE로 지정하면 됩니다.
* DELETE +
'개체' 테이블로부터 투플들을 삭제할 수 있는 특권입니다.
* REFERENCES(필드 이름) +
'개체'라는 테이블의 명세된 필드를 참조하는 외래 키를 (다른 테이블에서) 정의할 수 있는 특권입니다. 단순히 REFERENCES라고 표기하면 나중에 추가되는 것들을 포함해서 모든 필드에 대해 이 특권을 부여합니다.

사용자가 허가권(GRANT OPTION)이 부여된 특권을 가지면 GRANT 명령을 사용해서 다른 사람들에게 같은 특권을 전달해 줄 수 있습니다. 기반 테이블을 생성한 사용자는 그 객체에 대해 모든 적용 가능한 특권들을 가지며 이 특권들을 다른 사용자에게 허가할 수 있는 허가권도 가집니다. 

link:./07_privilege.adoc[다음: 특권]