= 투플 관계 해석

* **T(투플 변수) | p(T)(Formula - T를 묘시하는 식) }** 형식으로 투플 간의 관계를 해석
* 투플 변수
** 어느 릴레이션 스키마의 투플들을 값을 갖는 변수. 
** 주어진 투플 변수에 대입되는 값들은 모두 동일한 개수와 타입의 필드들을 가짐
* Rel이 릴레이션 이름이고 R과 S를 투플 변수로, a를 R의 한 애트리뷰트로, b를 S의 한 애트리뷰트라고 하고, op를 집합 { <, >, =, ≤, ≥, ≠ }에 속하는 연산자라고 할 때, 원자식은
** R ∈ Rel
** R.a op S.b
** R.a op 상수 또는 상수 op R.a
* 식 (Formula)은 다음 중 하나로 순환적으로 정의
** 원자식 
** ㄱp, p∧q, p∨q, 또는 p ⇒q
** ∃R(p\(R)). 이때 R은 투플 변수
** ∀R(p\(R)). 이때 R은 투플 변수

*투플 변수(Tuple Variable)*는 어느 특정 릴레이션 스키마의 투플들을 값으로 하는 변수입니다. 즉 주어진 투플 변수에 대입되는 값들은 모두 동일한 개수와 타입의 필드들을 가집니다.

*투플 관계 해석(Tuple Relational Calculus)* 질의는 _{ T | p(T) }_ 형식으로 되는데, 이때 T는 투플 변수이며 p(T)는 T를 묘사하는 식입니다. 이 질의의 결과는 식 p(T)가 T=t일 때 true인 모든 투플 t의 집합입니다. 관계 대수로도 표현할 수 있는 아래 질의는

_등급이 5 이상인 파일럿을 구하라_

아래와 같이 투플 관계 해석으로 표현될 수 있습니다.

_{ S | S ∈ 파일럿 ∧ S.등급 > 5 }_

== TRC 질의 구문

Rel이 릴레이션 이름이고 R과 S를 투플 변수로, a를 R의 한 애트리뷰트로, b를 S의 한 애트리뷰트라고 하고, op를 집합 { <, >, =, ≤, ≥, ≠ }에 속하는 연산자라고 할 때, 원자식은 다음 중 하나가 됩니다.

•	R ∈ Rel
•	R.a op S.b
•	R.a op 상수 또는 상수 op R.a

식(formula)은 다음 중 하나로 순환적으로 정의되는데, p와 q는 그 자체로 식이며 P(R)은 변수 R이 나오는 식을 의미합니다.

•	원자식 
•	ㄱp, p∧q, p∨q, 또는 p ⇒q
•	∃R(p(R)). 이때 R은 투플 변수
•	∀R(p(R)). 이때 R은 투플 변수

[%header, cols="1,1,1,3", width=80%]
|===
|구분	|구성요소	|기호	|설명
|연산자	|OR 연산	|∨	|원자식 간 “또는” 이라는 관계로 연결
|	|AND 연산	|∧	|원자식 간 “그리고”라는 관계로 연결
|	|NOT 연산	|ㄱ	|원자식에 대해 부정
|정량자	|전칭 정량자	|∀|	모든 가능한 투플
	|존재 정량자	|∃|	어떤 투플 하나라도 존재
|===

어떤 TRC 식에 나오는 모든 변수들은 그 부속 원자식 중 하나에 나오며 또 모든 관계 스키마는 필드마나 도메인을 하나씩 명세해 주기 때문에 TRC 식의 각 변수는 값을 취할 수 있는 잘 정의된 도메인(정의역)을 가지고 있음을 알 수 있습니다. 쉽게 말한다면 원자식 R ∈ Rel은 R의 타입을 Rel에 속한 투플의 타입으로 만드는 것이며, R.a op S.b나 R.a op 상수 같은 비교는 R.a의 타입을 제한하게 만듭니다.

TRC 질의(TRC Query)는 { T | p(T) } 형식으로 정의되는데 이때 T는 식 p내에서 자유 변수이어야 합니다.

== TRC 질의의 의미

TRC 질의 { T | p(T) } 에 대한 답은 변수 T에 투플 값 t를 대입했을 때 식 p(T)가 참이 되는 모든 투플 t의 집합입니다. 이 정의를 완성하기 위해서는 자유 변수들에게 어떤 투플 값을 대입하면 그 식이 참이 되는지를 설명해야 합니다.

질의는 주어진 데이터베이스 인스턴스에 대해 계산됩니다. 어떤 식 F 내의 각 자유변수가 한 투플 값으로 바인딩 된다고 하면, 변수에 어떤 투플을 대입했을 때 주어진 데이터베이스 인스턴스에 대해서 F가 참으로 계산되는 것은 다음 중 한가지 경우일 때입니다.

•	F가 원자식 R ∈ Rel이고 변수 R에 릴레이션 Rel의 인스턴스에 있는 한 투플을 대입할 때
•	F가 비교 R.a op S.b, R.a op 상수 또는 상수 op R.a 중 하나이고 해당 투플들을 R과 S에 넣으면 필드 값 R.a와 S.b가 이 비교를 참으로 만들 때
•	F가 ㄱp의 형식이고 p가 참이 아닐 때, 또는 p∧q의 형식이고 p와 q가 모두 참일 때, 또는 p∨q의 형식이고 둘 중 하나가 참일 때, 또는 p ⇒q의 형식이로 p가 참일 경우에는 q도 참일 때
•	F가 ∃R(p(R))의 형식이고 R을 위히해서 p(R)내의 자유 변수들에게 어떤 투플을 대입하면 p(R)이 참이 될 때
•	F가 ∀R(p(R))의 형식이고 R애 어느 투플을 대입한 경우에도 p(R)내에 있는 자유 변수들에 어떤 투플을 대입하면 식 p(R)dl 참이 될 때

== TRC 질의

아래와 같은 릴레이션 스키마가 있고, 

_파일럿(파일럿번호: 정수, 파일럿이름: 문자열, 등급: 정수, 나이: 실수)_

각 릴레이션의 인스턴스가 아래와 같다고 할 때,

Pilot1

[%header, cols="1,1,1,1", width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|===

등급이 5이상인 파일럿의 이름과 나이를 구하는 투플 관계 해석식은 아래와 같이 작성될 수 있습니다.

_{ S.이름, S.나이 | ∃S ∈ 파일럿 S.등급>=5) }_

또는 아래와 같이 보다 명시적이고 간략하게 작성될 수 있습니다.

_{ S.이름, S.나이 | Pilot1(S) and S.등급 >= 5 }_

link:./11_quiz.adoc[다음: Quiz 투플 관계 해석 질의]

