= 도메인 관계 해석

•	투플 변수 대신 도메인 변수를 사용하는 관계 해석
•	{<x1, x2, … xn> | p<x1, x2 … xn>} 형식으로 도메인 간의 관계를 해석
•	도메인 변수(Domain Variable)
한 애트리뷰트의 도메인을 값의 치역으로 하는 변수
•	원자식 
**	<x1, x2, … xn> ∈ Rel, 이때 Rel은 n개의 애트리뷰트 값을 갖는 릴레이션이며 xi, 1 ≤ i ≤ 는 변수 또는 상수 
**	X op Y
**	X op 상수, 또는 상수 op X
•	식
**	원자식
**	ㄱp, p∧q, p∨q, 또는 p ⇒q
**	∃X(p(X)). 이때 X는 도메인 변수
**	∀X(p(X)). 이때 X는 도메인 변수

---

**도메인 변수(Domain Variable)**는 어떤 애트리뷰트의 도메인을 값의 치역으로 하는 변수입니다. 만약 정수 집합을 도메인으로 하는 애트리뷰트에 대한 변수라면 이 변수에는 정수를 대입할 수 있습니다.

도메인 관계 해석(Domain Relation Calculus - DRC) 질의의 형식은 {<x1, x2, … xn> | p<x1, x2 … xn>}으로, xi는 도메인 변수이거나 상수이며 p<x1, x2 … xn>는 DRC 식(formula)로  자유변수는 xi, 1 ≤ i ≤ 뿐입니다. 이 질의의 결과는 식을 true로 만드는 모든 투플 {<x1, x2, … xn>} 의 집합입니다.

DRC 식은 TRC 식과 유사하게 정의되며, 주된 차이점은 변수가 투플 변수가 아닌 도메인 변수라는 점입니다. op를 집합 { <, >, =, ≤, ≥, ≠ }에 속하는 연산자라고 하고, x, y를 도메인 변수라고 할 때, DRC에서 원자식은 다음 중 하나입니다.

•	<x1, x2, … xn> ∈ Rel, 이때 Rel은 n개의 애트리뷰트 값을 갖는 릴레이션이며 xi, 1 ≤ i ≤ 는 변수 또는 상수 
•	X op Y
•	X op 상수, 또는 상수 op X

식은 다음 중 하나로 정의되는데 이때 p, q는 자체로 식이며 p(X)는 변수 x가 나오는 식입니다.

•	원자식
•	ㄱp, p∧q, p∨q, 또는 p ⇒ q
•	∃X(p(X)). 이때 X는 도메인 변수
•	∀X(p(X)). 이때 X는 도메인 변수

== DRC 질의

아래와 같은 릴레이션 스키마가 있고, 

_파일럿(파일럿번호: 정수, 파일럿이름: 문자열, 등급: 정수, 나이: 실수)_ 

각 릴레이션의 인스턴스가 아래와 같다고 할 때,

Pilot1

[%header, cols="1,1,1,1", width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|===

등급이 5이상인 파일럿의 이름과 나이를 구하는 투플 관계 해석식은 아래와 같이 작성될 수 있습니다.

_{<N, T>| < <N, T> ∈ Pilot1 ∧ 파일럿 T > 5>}_

link:./13_quiz.adoc[다음: Quiz 도메인 관계 해석 질의]
