= 검토

* 데이터베이스 설계 개요
* 개체 관계 데이터 모델
* ER 모델 기능
* 개념적 설계 고려사항

---

Quiz

1.	다음 용어들을 간단히 설명하세요.
* 속성(Attribute)
* 도메인(Domain)
* 개체(Entity)
* 관계(Relationship)
* 개체집합(Entity Set)
* 관계집합(Relationship Set)
* 일대다 관계(One-to-Many Relationship)
* 다대다 관계(Many-to-Many Relationship)
* 참여 제약조건(Participation Constraint)
* 중첩 제약조건(Overlap Constraint)
* 포괄 제약조건(Covering Constraint)
* 약 개체 집합(Weakly Entity Set)
* 역할 지시자(Role Indicator)
2.	어떤 대학 데이터베이스에 교수(ProfessorID로 식별됨)와 과목(LectureID로 식별됨)에 대한 정보가 저장되어 있습니다. 교수들은 과목을 강의하는 관계에 있습니다. 강의 관계 집합이 다음 각 상황에 있다고 할 때, 각 상황에 맞는 ER 다이어그램을 표시하세요.
A.	교수는 같은 과목을 여러 학기에 강의할 수 있는데 이 개설학기들을 기록해 두어야 한다.
B.	교수가 같은 과목을 여러 학기에 강의할 수 있는데 가장 최근의 개설 학기만 기록하면 된다.
C.	모든 교수들은 무슨 과목인가는 반드시 강의하여야 한다.
D.	각 교수들은 한 과목을 강의한다.
E.	각 교수들은 정확히 한 과목을 강의하며 각 과목을 강의하는 교수가 반드시 있어야 한다.
F.	어떤 과목을 교수진이 연합해서 강의할 수 있으나 이 교수진에 속한 어느 한 교수도 이 과목을 가르칠 수 없다. 필요하다면 개체 집합이나 관계집합을 더 도입해도 무방하다.
3.	다음과 같은 요구사항이 있는 대학 데이터베이스의 ER 다이어그램을 작성하세요.
A.	교수는 ProfessorID, Name, Age, Grade, ResearchField를 가진다.
B.	과제는 SubjectID, SupportOrg, StartDate, EndDate, Budget을 가진다.
C.	대학원생은 StudentID, Name, Age, Degree를 가진다.
D.	각 과제는 한 교수에 의해서 관리된다.
E.	각 과제는 한 사람 이상의 교수에 의해 수행된다.
F.	한 교수가 여러 과제를 관리할 수도 있고 수행할 수도 있다.
G.	한 과제는 한 명 이상의 대학원생에 의해 수행된다.
H.	대학원생이 한 과제를 수행할 때는 어떤 교수가 이 작업을 감독하여야 한다. 한 대학원생이 여러 프로젝트를 수행할 수 있는데 각 수행과제마다 감독자가 있어야 하며 감독자는 서로 달라도 무방하다.
I.	학과는 DepartmentID, Name, Office를 가진다.
J.	각 학과마다 그 학과를 운영하는 교수가 한 명 있다.
K.	한 교수가 여러 학과에서 근무할 수 있는데, 이때 학과별로 참여 백분율이 기록된다.
L.	대학원생은 전공 학과가 하나씩 있다.
M.	대학원생은 조언자 역할을 하는 선배가 있다.
4.	파인만 레코드사는 데이터베이스를 구축하고자 한다. 아래 요구사항에 맞는 데이터베이스 개념 스키마를 설계하고 이에 따라 ER 다이어그램을 작성하세요. 그리고, 설계에 따라 데이터베이스를 작성하는 SQL DDL 구문을 작성하세요.
A.	파인만 레코드사에서 녹음을 한 음악가들은 MusicianID, Name Address, TelephoneNo를 가진다. 이 중 같은 주소를 사용하는 음악가들도 있는데, 한 주소에는 한 전화번호만 있다.
B.	파인만 레코드사에서 녹음에 사용되는 악기는 종류(기타, 신디사이저, 드럼 등)와 음조(C, B-Flat 등)을 가진다.
C.	녹음된 앨범은 Title, RegisteredDate, ISBN을 가진다.
D.	모든 노래는 제목과 작가를 가진다.
E.	한 음악가가 여러 악기를 연주할 수 있으며, 한 악기를 여러 음악가가 연주할 수 있다.
F.	한 앨범에는 여러 곡이 들어있지만, 노래 한 곡은 단 하나의 앨범에만 수록 될 수 있다.
G.	여러 음악가가 협동하여 한 곡을 만들 수 있고, 한 음악가는 여러 곡을 만들 수 있다.
H.	각 앨범에는 프로듀서로 한 음악가가 참여한다. 한 음악가는 여러 곡의 프로듀서가 될 수 있다.
