= 개체 or 속성

* 속성으로 모델링 하는 경우
** 한 개체가 속성을 단일 값으로 가지는 경우
** 요구 사항에서, 수직, 수평적으로 분리될 수 없는 값인 경우
* 개체로 모델링하는 경우
** 한 개체가 여러 개의 값을 가지는 경우
** ER 다이어그램에서 주소의 구조를 표현해야 하는 경우

---

어떤 개체집합이 가지는 것들을 식별해 내는데 있어서, 이를 **속성(Attribute)**로 표현하는 것이 좋은지 아니면 **개체집합(Entity Set)**으로 표현하는 것이 좋은지 불분명할 때가 있습니다. 예를 들어 직원 개체 집합에 주소 정보를 추가한다고 할 때, 한 가지 안은 주소라는 속성을 이용하는 것입니다. 직원 당 하나의 주소만 기록하면 된다고 하면 적절한 선택이며, 주소를 문자열로 생각할 수 있습니다.

다른 방안은 주소라는 개체집합을 하나 만들고 직원과 그 직원의 주소간에 관계를 표현하는 것입니다. 이는 아래와 같은 경우에 해당합니다.

* 한 직원이 여러 주소를 가지고 있는 경우
* ER 다이어그램에서 주소의 구조를 표현해야 하는 경우, 주소의 내용을 시/도, 구/군, 우편번호 등으로 구분해야 하는 경우. 이런 경우라면 “분당구 판교동에사는 직원을 구하라”와 같은 질의를 작성할 수 있습니다.
 
속성이 아닌 개체로 모델링 해야 하는 다른 경우로, 아래와 같은 ER 다이어그램이 있습니다.
 
이 모델링은 한 직원이 부서에 근무한 이력을 저장할 수 있도록 합니다. 이 모델링에서 근무 관계집합의 기본 키는 직원 개체집합의 사번과 부서 개체집합의 부서번호 속성이 모여서 만든 수퍼키 <사번, 부서번호>가 됩니다. 이 모델링에서 한 직원이 여러 부서에 근무한 이력이 있는 경우를 생각해봅시다. 
사번이 1인 직원이 다른 기간에 같은 부서에서 근무한 이력이 있다면, 근무 릴레이션의 인스턴스는 아래와 같이 될 수 있습니다.

[%header, cols=4, width=60%]
|===
|사번	|부서번호	|근무시작일	|근무종료일
|1	|1	|2018-01-23	|2019-10-11
|1	|2	|2019-10-12	|2020-11-23
|1	|1	|2020-11-23	|2021-09-10
|===

이 인스턴스에서 사번과 부서번호는 중복된 값을 가질 수 있게 되어, 릴레이션의 적법한 인스턴스가 아니게됩니다. 이 문제는 근무 관계에 설명형 속성을 여러 개 두고 싶다는 것에서 발생합니다. 이 문제는 아래와 같이 근무시작일과 근무종료일을 속성으로 가지는 새로운 개체집합을 도입하면 해결됩니다.
 
ER 모델의 어떤 버전에서는 속성의 값이 집합인 것을 허용합니다. 이런 기능을 이용할 수 있다면 기간 정보를 개체집합으로 독립시키지 않고 근무 관계의 한 속성으로 만들 수 있습니다. 그렇지만 이런 집합 값을 가지는 속성을 관계 모델로 표현할 때는 관계 모델에서는 집합 값을 갖는 속성을 지원하지 않기 때문에 기간 정보를 개체집합으로 취급한 것과 같은 릴레이션 스키마를 얻게 됩니다.

link:./16_entity_or_relationship.adoc[다음: 개체 or 관계]