= WHERE 절

* 관계대수에서 셀렉션(Selection - σ) 연산과 일치함
* `FROM` 절에 나타나는 릴레이션 속성들의 조건으로 구성

[source, sql]
----
SELECT [DISTINCT] A1, A2 … An
FROM r1 A, r2 B, … rm M
WHERE P
----

* WHERE 절의 조건식으로 셀렉션 연산을 수행
** `식 op 식`` 형태의 조건들을 조합한 불리언 식으로, op는 비교 연산자 `{<, <=, =, <>, >=, >}` 중의 하나
** 범위 연산을 위해 `BETWEEN` 비교 연산을 제공

---

`WHERE` 절은 관계 대수에서 셀렉션(σ)에 해당합니다. `WHERE` 쩔은 `FROM` 절에 나타나는 릴레이션들의 속성들의 조건으로 구성됩니다.

`WHERE` 절에 있는 조건식(qualification)은 `식 op 식` 형식의 조건들을 조합한 불리언 식입니다. 즉, 논리 접속사 `AND`, `OR`, `NOT` 로 연결한 수식입니다. 이때 op는 비교 연산자 `{ <, <=, =, <>, >=, > }` 중의 하나입니다. 여기에서 식은 필드 이름, 상수, 또는 산술/문자열 중 하나입니다.

범위 연산을 위해 `BETWEEN` 비교 연산을 제공합니다.

> 번호가 101인 비행기의 운항 일자를 구하라

위 질의를 관계 대수로 다음과 같이 작성할 수 있습니다.

_πFlightDate(σAircraftNo=101(Aircraft ⋈ Flight)_

위 관계 대수식을 SQL로 아래와 같이 작성할 수 있습니다.

[source, sql]
----
SELECT FlightDate
FROM Aircraft AS A INNER JOIN Flight AS F ON A.AircraftNo = F.AircraftNo
WHERE A.AircraftNo = 101;
----

> 대한항공을 예약한 모든 승객의 이름과 나이를 구하라

위 질의를 관계 대수로 다음과 같이 작성할 수 있습니다.

_πPassenger, age(σAirline=’대한항공’(Aircraft ⋈Flight ⋈ Reservation ⋈ Passenger)_

위 질의를 관계 해석식으로 다음과 같이 작성할 수 있습니다.

_{ P.PassengerName, P.Age | P ∈ Passenger ∧ A.AircraftName=대한항공 +
∧ ∃A ∈ Aircraft(A.AircraftNo = F.AircraftNo +
∧ ∃F ∈ Flight(F.FlightNo = R.FlightNo +
∧ ∃R ∈ Revervation(R.PassengerNo = P.PassengerNo)))}_

위 질의를 SQL 질의로 아래와 같이 작성할 수 있습니다.

[source, sql]
----
SELECT PassengerName, Age
FROM Aircraft INNER JOIN Flight ON Aircraft.AircraftNo = Flight.AircraftNo
	INNER JOIN Reservation ON Flight.FlightNo = Reservation.FlightNo
     	INNER JOIN Passenger ON Passenger.PassengerNo = Reservation.PassengerNo
WHERE Aircraft.Airline = '대한항공';
----

link:./17_set_operation.adoc[다음: 집합 연산]
