== 서브 쿼리 개요

* 단일 질의 안에 질의가 포함된 형태의 쿼리
** 관계 대수 질의 결과는 릴레이션을 반환함
** 서브 쿼리의 결과를 주 쿼리에서 받아서 처리는 형식으로, `포함된 쿼리(Nested Query)` 라라고도 부름
* 서브 쿼리 (Subquery)
** 가장 많이 사용되는 형태로, WHERE 절에서 셀렉션 연산의 값을 산출하기 위해 사용하는 질의
* 인라인 뷰(Inline View)
** `FROM` 절에서 질의의 결과를 테이블처럼 사용하는 용도의 질의
* 스칼라 서브 쿼리(Scala Subquery)
** `SELECT` 문에서 사용되는 서브 쿼리로, 주로 계산 결과값을 쿼리 결과에 포함시키는데 사용되는 질의
* 연관 서브 쿼리
** 서브 쿼리에서 주 쿼리의 필드값과 연관되어 사용하는 질의

---

`서브 쿼리(Subquery)` 는 다른 질의를 포함하는 질의를 말합니다. 다른 질의를 포함하는 질의라는 의미에서 `포함된 쿼리(Nested Query)` 라고도 부릅니다. 결과를 위한 질의에서, 질의 도중에 어떤 테이블을 계산해 내고 그 테이블에 대해서 다시 질의를 할 필요가 생기는 경우가 있습니다. 이렇게 중간 단계 테이블을 만들어내는 질의가 서브 쿼리이고 이를 포함하여 주 쿼리를 구성합니다. 
서브 쿼리는 주로 주 쿼리의 `WHERE` 절에서 나타나지만, `FROM`, `SELECT` 절에서도 나타날 수 있습니다. 때에 따라 각 절에서 나타나는 쿼리를 인라인 뷰, 스칼라 서브 쿼리등으로 분류하며 서브 쿼리의 값과 주 쿼리의 값을 연관하여 사용하는 쿼리를 연관 서브 쿼리라고 부르기도 합니다.

> 인천에서 출발하는 비행기의 종류를 구하라

위 질의는 아래와 같이 서브 쿼리로 작성할 수 있습니다.

[source, sql]
----
SELECT KindOfAircraft
FROM
	Aircraft
WHERE
	AircraftNo IN 
    (SELECT AircraftNo
    FROM Flight
    WHERE Depareture = '인천');
----

서브 쿼리를 이해하는 가장 좋은 방법은 이를 이중 루프 수행 전략으로 생각하는 것입니다. 최상층 질의의 전략을 일반적으로 서브 쿼리까지 포함하도록 확장할 수 있습니다. 주 질의의 FROM 절에 나타나는 테이블들로 카티션 프로덕트를 이전과 같이 구성합니다. 이 카티션 프로덕트의 각 투플에 대해 WHERRE절의 조건식을 검사하며, 서브 쿼리를 재 실행합니다. 서브 쿼리 자체에도 또 다른 서브 쿼리가 내포될 수 있는데, 이 경우 역시 똑같이 동작하므로, 결과는 다중 루프 수행 전략이 됩니다.

> 샌프란시스코에 도착하는 비행기를 예약한 승객의 이름을 구하라

위 질의는 아래와 같이 2중으로 포함된 서브 쿼리로 작성할 수 있습니다.

[source, sql]
----
SELECT PassengerName
FROM
	Passenger
WHERE
	PassengerNo IN 
     (SELECT PassengerNo 
     FROM Reservation
     WHERE FlightNo IN
		(SELECT FlightNo
              FROM Flight
              WHERE Arrival = '샌프란시스코'));
----

link:./23_nested_subquery.adoc[다음: 포함된 서브쿼리]