= 무손실 조인 분해

* R을 릴레이션 스키마라고 하고 F를 R에 대한 FD의 집합이라고 할 때,
** R를 속성 집합 X와 속성 집합 Y의 두 스키마로 분해하였을 때
** F에 속하는 함수 종속을 만족하는 R의 모든 인스턴스 R에 대해
** π X(r) ⋈ π Y(r)=R 이 성립하면 무손실 조인 분해라고 함

---

R를 한 릴레이션의 스키마라고 하고 F를 R에 대한 FD의 집합이라고 할 때, R을 속성 집합 X과 속성 집합 Y의 두 스키마로 분해하였을 때 F에 속하는 속성들을 만족하는 모든 인스턴스 R에 대해 π X(r) ⋈ π Y(r)=R 이 성립하면 이를 **무손실 조인 분해(lossless Join Decomposition)**이라고 합니다.

이 정의는 둘 보다 많은 릴레이션으로 분해하는 경우에 대해서도 쉽게 확장할 수 있습니다. r ⊆ π X(r) ⋈ π Y(r)=R 이 항상 성립한다는 건 쉽게 확인할 수 있습니다. 그렇지만 일반적으로 역은 성립하지 않습니다. 어떤 릴레이션으로부터 프로젝션을 구한 후 이들을 자연조인으로 다시 합치면 보통 원래 릴레이션에 없던 새로운 투플들이 몇 개 생기게 됩니다.

[%header, cols=3, width=30%]
|===
|S	|P	|D
|s1	|p1	|d1		
|s2	|p2	|d2		
|s3	|p1	|d3		
|===
인스턴스 r		

[%header, cols=2, width=30%]
|===
|S	|P		
|s1	|p1		
|s2	|p2		
|s3	|p1		
|===
πSP(r)		

[%header, cols=2, width=30%]
|===
|P	|D
|p1	|d1		
|p2	|d2		
|p1	|d3		
|===
πPD(r)		

[%header, cols=3, width=30%]
|===
|S	|P	|D
|s1	|p1	|d1
|s2	|p2	|d2
|s3	|p3	|d3
|s1	|p1	|d3
|s3	|p1	|d1
|===
πSP(r) ⋈ πPD(r) 

인스턴스 r을 인스턴스 πSP(r)와 πPD(r)로 대치하면 정보를 일부 손실하게 됩니다. 특히 r에 있는 투플들이 관계를 표현하는 경우, 관계(s1, p1, d3)와 (s3, p1, d1)이 성립하지 않는다고 더 이상 말할 수 없게 됩니다. 따라서 인스턴스 r이 적법하다면, 즉 모델링 하려고 하는 조직체에서 이러한 인스턴스가 발생할 수 있다면, 스키마 SPD를 SP과 PD로 분해하는 것은 손실성(lossy) 분해가 됩니다. 

중복성을 없애기 위한 분해라면 어떠한 것이든 손실이 없는 것이어야 합니다. 다음과 같은 간단한 시험을 해 보는 것이 좋습니다.

R을 릴레이션이라고 하고 F를 R에 있는 FD들의 집합이라고 할 때, R을 속성 집합 R1과 R2로 구성된 두 릴레이션으로 분해하는 것이 무손실이려면 F+에 FD R1 ∩ R2 → R1이나 FD R1 ∩ R2 → R2가 있어야 하며, 그 역도 성립합니다.

다른 말로 하면, R1과 R2 모두에 있는 속성에는 반드시 R1이나 R2에 대한 키가 있어야 한다는 것입니다. 어떤 릴레이션을 두 개의 릴레이션으로 분해할 때에는 그 분해가 무손실- 조인 분해인지 아닌지에 대한 시험을 해 보는 것이 필요하고 충분한 조건이 됩니다. 

아래 릴레이션에서,

----
Parttime_emp(EmpID, Name, Parkingslot, Grade, WagePerHr, Workingtime)
                E      M        P        G        W            T
----

이 릴레이션은 속성이 EMPGWT이고 함수 종속 G → W가 3NF를 위반합니다. 이 위반사항을 처리하려면 릴레이션을 EMPGT와 GW로 분해하면 됩니다. R이 분해된 두 릴레이션 모두에 있고 G → W가 만족되므로 이 분해는 무손실 분해입니다.

이 예를 일반화하면 다음과 같습니다.

_어떤 릴레이션 R에 FD X → Y가 존재하고 X ∩ Y가 공집합이면 R을 R – Y와 XY로 무손실 분해할 수 있다._

_X는 R - Y와 XY에 모두 나타나며, (X ∩ Y)가 공집합이므로), XY에 대해 키입니다. 따라서 무손실 조인 분해를 위한 검사법으로부터 위와 같은 사실에 도달할 수 있습니다._


link:./17_dependency_decomp.adoc[다음: 종속성 유지 분해]