= 분해

* 3NF나 BCNF가 아닌 릴레이션을 중복성 문제가 발생하지 않도록 처리하는 기법
* 해당 릴레이션 스키마를 더 적은 속성을 가진 릴레이션 스키마로 분해
* 릴레이션 R의 분해
** R에 속한 속성의 부분집합으로 각기 구성된 둘 이상의 스키마들로 R을 대치
** 이들의 속성을 모두 합쳤을 때 원래 R에 속한 속성 중에 빠지는 것이 있으면 안됨

---

BCNF에 속하는 릴레이션은 중복성이 없으며(FD 정보로 알 수 있는 중복성이 없다는 뜻), 3NF에 속하는 정규형도 이와 가깝습니다. 이러한 3NF나 BCNF에 속하지 않는 릴레이션에서는 종속성 때문에 문제가 발생할 수 있습니다. 이런 종속성 때문에 발생하는 문제들을 처리하는 방법은 해당 릴레이션의 스키마를 더 적은 속성을 가진 릴레이션 스키마들로 분리하는 것입니다.

릴레이션 스키마 R을 분해(Decomposition)한다는 것은 R에 속한 속성의 부분 집합으로 각기 구성된 둘 이상의 릴레이션 스키마들로 이 릴레이션 스키마를 대치한다는 것이며, 이때 이들의 속성을 모두 합쳤을 때 원래 R에 속한 속성중에 빠지는 것이 있어서는 안됩니다. 따라서 당연히 R의 주어진 인스턴스의 정보를 몇 가지로 프로젝션 해서 저장하게 됩니다.

아래 릴레이션에서,
----
Parttime_emp(EmpID, Name, Parkingslot, Grade, WagePerHr, Workingtime)
                E      M        P        G        W           T
----

이 릴레이션은 속성이 EMPGWT이고 두 함수 종속, E → EMPGWT와 G → W을 가지고 있습니다. G가 키가 아니고 W가 키의 일부가 아니기 때문에 두 번째 함수 종속은 3NF를 위반합니다.

설계를 다시 해보면 속성이 EMPGT와 GW인 릴레이션 두 개로 만들면 됩니다. EMPGT에서는 E → EMPGWT가 만족되고 E가 키가되며, GW에서는 G → W가 만족되고 G가 키가 됩니다. 이 두 스카메엇 만족되는 다른 속성들은 첨가 법칙으로 얻어지는 것뿐입니다. 따라서 이 두 스키마는 BCNF가 됩니다.

EMPGWT를 예를 들어 GMPG와 PGWT로 분해하지 않고 EMPGT와 GW로 분리하는 것은 종속성 G → W가 3NF를 위반한다는 사실을 보고 이 위배사항을 처리하는 가장 자연스러운 방법이 이 스키마로부터 W 속성을 없애는 것이라고 분석이 나왔기 때문입니다. 원래의 스키마에서 W를 없애는 대신 새 릴레이션 GW를 만들었는데, 이는 FD G → W에 의하여 모든 R은 각기 유일한 W 값과 연관되기 때문입니다.

이 시점에서 중요한 것은 릴레이션 스키마 EMPGWT의 적법한 인스턴스 R을 그에 대한 두 개의 인스턴스 EMPGT(R1)과 GW(R2)로 대치했을 때 이 R1과 R2로부터 R을 복원해 낼 수 있는 것인지 하는 것입니다. EMPGWT를 EMPGT과 GW로 분해하겠다는 것은 인스턴스 R을 R1과 R2를 나누어서 저장하는 다는 말과 같습니다. 원래 의도하던 인스턴스 R을 R1과 R2로부터 구할 수 없으면 안됩니다.

link:./16_join_decomp.adoc[다음: 무손실 조인 분해]