= 정보 시스템

* 조직체에 필요한 데이터를 수집, 조직, 저장하고 필요시에 유효한 정보를 생성하고 분배
* 조직의 운영과 외부적 상황에 관련된 과거, 현재, 예측적 미래에 대한 정보를 조직적으로 제공
** 의사 결정 과정에서 적시에 정확한 정보를 제공
** 조직의 관리, 기획, 통제, 운영을 조정
* MIS (Management Information System – 경영 정보 시스템)
* ERP (Enterprise Resource Planning – 전사적 자원 관리)
* CRM (Customer Relationship Management – 고객 관계 관리)
* SCM (Supply Chain Management – 공급 사슬 관리)
* ...

---

의사 결정에 유용한 정보는 데이터를 효과적으로 처리함으로서 얻을 수 있습니다. 조직의 활동에 필요한 데이터를 수집, 조직, 저장해 두었다가 필요할 때 처리해서 의사 결정에 유효한 정보를 생성하고 분배하는 도구를 일반적으로 `정보 시스템(Information System)` 이라고 합니다.

정보 시스템은 한 조직체의 내부적 운영과 외부적 상황에 관련된 과거, 현재, 예측되는 미래에 상황에 대한 정보를 조직적으로 제공하는 방법이며, 의사 결정 과정에서 적시에 정확한 정보를 제공함으로써 그 조직체의 기획, 통제, 운영 기능을 조정하는 역할을 수행합니다.

기업에는 다양한 정보 시스템이 있으며, 한 기업의 경영 관리, 업무 기획, 운영, 통제에 필요한 의사 결정을 위하여 가장 정확하고 최신의 정보를 제공하는 수단으로 사용되는 정보 시스템을 `MIS(Management Information System – 경영 정보 시스템)` 이라고 하며, 최근 특정 영역으로 세분화되어 존재하는 가장 보편적인 정보 시스템입니다.

의사 결정을 위해 사용되는 정보 시스템은 사용 목적에 따라 여러 이름으로 불립니다. 여기에는 `ERP(Enterprise Resource Planning – 전사적 자원 관리)` , `CRM (Customer Relationship Management – 고객 관계 관리)` , `SCM(Supply Chain Management – 공급 사슬 관리)` 등이 있으며, 보다 세분화된 시스템으로 나누어 통합되는 형태로 존재하기도 합니다.

하나의 전문적인 목적보다는 여러가지 복합적이고 광범위한 목적을 위해 통합적인 기능을 수행하는 정보 시스템을 구축할 수 있는데, 이런 시스템을 `DSS(Decision Support System – 의사 결정 지원 시스템)` 이라고 합니다. 

link:./05_database.adoc[다음: 데이터베이스]
