= 데이터베이스

* 같은 데이터가 다른 목적을 가진 여러 응용에 중복되어 사용될 수 있다는 공용 개념의 기초
* 한 조직의 여러 응용 시스템들이 함께 사용할 수 있도록 통합되고 저장된 데이터의 집합
** 통합된 데이터(Integrated Data)
** 저장된 데이터(Stored Data)
** 운영 데이터(Operational Data)
* 공용 데이터(Shared Data)
* 통합 저장된 운영 데이터로서의 특징
** 실시간 접근성(Real-time Accessibility)
** 지속적인 변화(Continuous Evolution)
** 동시 사용(Concurrency Sharing)
** 내용 참조(Content Reference)

---

데이터베이스(Database)나 데이터베이스 관리(Database Management)라는 용어가 정확하게 언제부터 사용되기 시작하였는지는 분명하지 않습니다. 1963년 6월 미국 SDC(System Development Corporation)가 개최한 "컴퓨터 중심의 데이터베이스 개발과 관리"라는 학술회 제목에서 데이터베이스란 용어가 공식적으로 처음 사용되었습니다. 이 학술회에서 발표된 대부분의 논문에서 데이터베이스는 자기 테이프와 같은 저장 장치에 저장된 데이터 파일을 의미하였습니다.

데이터베이스 시스템이라는 용어도 1965년 9월 SDC가 개최한 “컴퓨터 중심 데이터베이스 시스템”이라는 학술회 제목에서 처음 사용되었습니다. 이 학술회에서는 상당하 복잡한 데이터 관리 문제가 다루어졌으며, 제기된 문제 해결을 위한 시스템도 많이 제안되었습니다.

데이터베이스는 원래 같은 데이터가 상이한 목적을 가진 여러 응용에 중복되어 사용될 수 있다는 공용의 개념에 기초를 두고 있습니다. 데이터베이스는 어느 한 조직의 여러 응용 시스템들이 공유하여 사용할 수 있도록 통합, 저장된 운영 데이터의 집합으로 정의할 수 있습니다.

== 데이터베이스의 정의

. **통합된 데이터(Integrated Data)** +
데이터베이스에서는 똑 같은 데이터가 원칙적으로 중복되어 있지 않다는 것을 말합니다. 데이터의 중복은 일반적으로 관리상의 복잡한 부작용을 초래합니다. 
. **저장된 데이터(Stored Data)** +
디스크 등과 같이 컴퓨터가 접근할 수 있는 저장 매체에 저장된 데이터를 의미합니다. 
. **운영 데이터(Operational Data)** +
모든 조직은 그 조직의 생존적인 기능을 유지하기 위해 반드시 유지해야하는 데이터가 있고, 이를 운영 데이터라고 합니다. 데이터베이스는 단순한 데이터의 집합이 아니라 그 조직의 존재 목적이나 기능을 수행하는데 없어서는 안되는 데이터의 집합을 의미합니다. 단순한 입출력 데이터나 작업 처리를 위해 일시적으로 필요한 임시적인 데이터는 운영 데이터로 취급하지 않습니다.
. **공용 데이터(Shared Data)** +
데이터베이스는 어느 하나의 응용 프로그램이나 시스템을 위한 데이터가 아니라 조직에 있는 여러 응용 시스템들이 공동으로 소유하고 유지하며, 이용하는 공유하여 사용하는 데이터의 집합을 의미합니다. 여러 사용자들이 서로 다른 목적으로 데이터베이스의 데이터를 공동으로 이용하며, 따라서 데이터베이스는 일반적으로 큰 규모의 데이터를 저장하며 구조가 복잡한 것이 일반적입니다.

== 데이터베이스의 특징
. **실시간 접근성(Real-time Accessibility)** +
컴퓨터가 접근할 수 있는 저장 장치에 수록된 데이터베이스는 임의적이고 비정형적인 질의에 대해 실시간으로 응답할 수 있어야 합니다. 실시간 처리(Real-time processing)은 생성된 데이터를 즉시 컴퓨터에 보내어 처리결과를 확인하고 바로 다음 의사 결정에 반영할 수 있는 처리 방식을 말하며, 온라인 처리와 동일한 의미로 사용됩니다. 실시간 처리는 초 단위를 넘겨서는 안됩니다.
. **지속적인 변화(Continuous Evolution)** +
어느 한 시점에 데이터베이스가 저장하고 있는 내용은 곧 데이터베이스의 상태를 의미하며, 데이터베이스의 상태는 동적이라는 것을 의미합니다. 데이터베이스는 새로운 데이터의 삽입(Insertion)이나 삭제(Deletion), 갱신(Update)으로 항상 변하고, 항상 현재의 정확한 데이터를 유지해야 합니다.
. **동시 사용(Concurrent Sharing)** +
데이터베이스는 서로 다른 목적을 가진 응용들을 위한 것이므로 여러 사용자가 동시에 자기가 원하는 데이터에 접근할 수 있어야 합니다. 이는 한 가지 특정 목적으로 하나의 응용 프로그램에 의해 접근되는 데이터와 다르며, 여러 응용 프로그램이 같은 데이터를 직렬적으로 공유하여 사용하는 개념과도 다릅니다. 데이터베이스의 서로 다른 부분을 여러 사용자가 동시에 사용하는 것도 쉽지 않지만 특히 같은 내용의 데이터를 여러 사용자가 서로 다른 방법으로 동시에 공유하여 사용한다는 것은 관리와 조직 모든 측면에서 복잡하게 됩니다. 
. **내용 참조(Content Reference)** +
데이터베이스 환경에서 데이터의 참조는 수록되어 있는 데이터 레코드의 주소나 위치에 의해서가 아니라 사용자가 요구하는 데이터의 내용, 즉 데이터가 가지고 있는 값에 따라 참조됩니다. 일반적으로 사용자가 참조하기를 원하는 데이터의 조건을 명세하면 이 조건을 만족하는 모든 레코드들은 데이터의 위치에 상관없이 논리적 단위로 취급되고 접근됩니다.

link:./06_database_management_system.adoc[다음: 데이터베이스 관리 시스템]