= 데이터 모델

* 데이터 또는 정보를 설명하기 위한 표기법
** 데이터의 구조(Structure of the Data)
** 데이터에 대한 작업(Operations on the Data)
** 데이터에 대한 제약 조건(Constraints on the Data)
* 주요 데이터 모델
** 관계 데이터 모델(Relational Data Model)
** 반정형 데이터 모델(Semistructured-data Model)
* 기타 데이터 모델
** 네트워크 데이터 모델(Network Data Model)
** 계층형 데이터 모델(Hierarchical Data Model)
** 객체 지향 데이터 모델(Object Data Model)

---

데이터 모델은 데이터 또는 정보를 설명하기 위한 표기법입니다. 일반적으로 세 가지 부분으로 나누어 설명할 수 있습니다.

1. 데이터의 구조(Structure of the Data) +
컴퓨터에서 데이터를 구현하는데 사용되는 데이터 구조는 데이터베이스 시스템 관점에서 물리적 데이터 모델로 언급되기도 하지만 데이터 관점에서는 다릅니다. 데이터베이스의 관점에서 데이터 모델은 데이터의 물리적 구조보다 높은 레벨인 개념적 관점에서 언급됩니다.
2. 데이터에 대한 작업(Operations on the Data) +
데이터 모델은 데이터에 대해 수행할 수 있는 작업을 제한합니다. 일반적으로 제한된 쿼리와 업데이트 작업을 수행할 수 있습니다. 이 한계는 약점이 아니라 장점이 되며, 데이터에 대한 작업을 제한함으로써 데이터베이스 작업을 높은 수준에서 설명하면서도 데이터베이스 관리 시스템이 작업을 효율적으로 구현하도록 할 수 있습니다.
3. 데이터에 대한 제약 조건(Constraints on the Data) +
데이터 모델은 일반적으로 데이터가 무엇인지에 대한 제약 사항을 설명하는 방법이 포함됩니다. 이 제약 조건은 아주 복잡한 데이터 한계에 대해 단순한 방법으로 범위를 지정합니다.

== 주요 데이터 모델

오늘날에는 데이터베이스 시스템에서 두 가지 데이터 모델은 다음과 같습니다.

1. 관계 데이터 모델 +
관계 데이터 모델은 술어 논리와 집합론에 기반을 둔 데이터베이스 모델로, 개체와 개체들 사이의 관계로 데이터를 표현합니다. 1970년 IBM의 Codd 박사에 의해 제안되었으며, 데이터베이스의 이론적인 모델을 제공했습니다.
논리적 데이터베이스 모델 중 가장 널리 사용되는 데이터 모델로, 하나의 개체에 대한 데이터를 릴레이션이라 부르는 테이블 형태의 집합으로 데이터베이스에 저장합니다. 관계형 모델은 데이터를 표현하는데 있어서 단순하면서도 매우 강력한 표현력을 가지고 있습니다. 
2. 반정형 데이터 모델 +
반정형 데이터 모델은 테이블이나 배열보다는 트리나 그래프와 유사합니다. XML 파일이나 보다 단순한 JSON 형식의 파일은 다양한 형태로 표현될 수 있으며 작업, 구조, 제약 조건등의 측면에서 데미터 모델의 특징을 가지고 있습니다.
+
CSV 형태로 저장된 파일 역시 계층적 데이터와 테이블을 포함할 수 있으므로 반정형 데이터로 볼 수도 있습니다.

== 기타 레거시 데이터 모델

예전에 사용되었으나 현재는 거의 사용되지 않는 데이터 모델들입니다.

* 네트워크 데이터 모델 +
네트워크 데이터 모델은 1969년 튜링상 수상자인 찰스 바크만에 의해 만들어진 데이터 모델이며, 객체와 객체에 대해 상/하위 관계를 가지는 모델로 데이터를 표현하는 모델입니다. 그래프 구조에 기반을 둔 모델이며, 단일 객체를 표현하는 데이터의 집합인 레코드를 노드로, 레코드와 레코드의 관계는 선으로 표현하며, 하나의 레코드의 다수의 레코드를 연결할 수 있기 때문에 M:M 관계의 데이터 모델링을 기반으로 합니다. 레코드의 구조 변경이 어려워 확장성이 떨어지는 단점이 있습니다. +
* 계층형 데이터 모델 +
계층형 데이터 모델은 초창기 메인 프레임 컴퓨터에서 널리 사용되었으며, 계층형 데이터 모델에서 데이터는 레코드와 링크로 구성된 트리 형태로 나타납니다. 링크로 연결된 레코드 집합은 부모-자식 관계를 표현하는데, 부모 노트는 다수의 자식 노드를 가질 수 있지만 자식 노드는 하나의 부모 노드만 가질 수 있는 전형적인 계층 구조로, 1:N 관계로 데이터를 표현합니다. 
* 객체 지향 데이터 모델 +
1980년 후반에 등장한 객체 지향 데이터 모델은 객체 지향 프로그래밍 패러다임을 기반으로 합니다. 즉 데이터와 메소드를 하나의 객체로 다루기 때문에 이해하기 쉽고, 유지와 변경이 용이합니다. 관계형 데이터 모델이 객체 지향 데이터 모델 개념을 가질 수 있도록 확장된 객체-관계 데이터 모델이 1990년에 등장하여 사용되고 있습니다.

link:./12_data_independency.adoc[다음: 데이터 독립성]