= 데이터베이스 질의

* 데이터베이스로부터 정보를 얻는 방식의 쉬움 정도에 따라 데이터베이스의 가치가 좌우됨
* 데이터를 얻기 위한 일반적인 질문(Query)의 전산학적인 구현
* DBMS는 일반적으로 질의(Query)를 만들 수 있는 질의어(Query Language)를 제공
** 데이터 조작어(DML: Data Manipulation Language)
** 데이터 정의어(DDL: Data Definition Language)
** 데이터 제어어(DCL: Data Control Language)

---

복잡하고 많은 데이터를 저장하는 데이터베이스의 특성상, 데이터베이스에 저장된 데이터를 얻고 저장하는 방식은 매우 중요합니다. 데이터베이스로부터 정보를 얻는 방식이 얼마나 쉽고 일관성이 있는지에 따라 데이터베이스의 가치가 좌우됩니다. 
데이터베이스는 저장된 데이터에 대해 다양한 방식으로 질의를 수행할 수 있는 방법을 제공해야 합니다. DBMS에 저장되어 있는 데이터에 대한 다양한 질문들을 `쿼리(Query)` 라고 하며, 데이터베이스 관리 시스템은 이를 수행할 수 있는 `질의어(Query Language)` 를 제공합니다. 

관계 데이터 모델이 가장 널리 쓰이게 된 이유중의 하나가 SQL(Structured Query Language)라고 불리는 강력한 질의어를 제공합니다.

* 관계 해석(Relational Calculus) +
수학적인 논리에 바탕을 둔 일종의 정형 질의어로 이 언어로 작성된 질의들은 직관적이며 정확한 의미를 갖습니다. 
* 관계 대수(Relational Algebra) +
릴레이션을 조작할 수 있는 연산자들의 합성에 바탕을 두고 있는 정형 질의으로, 표현력 면에서 관계 해석과 동일합니다.
데이터베이스 질의는 데이터 조작어(DML)의 일부입니다. 데이터베이스는 데이터의 모양을 정의하고, 삽입, 삭제, 수정하며 보안을 제어할 수 있는 3가지로 분류할 수 있는 데이터 언어를 제공합니다.
* 데이터 조작어(DML: Data Manipulation Language) +
정의된 데이터베이스에 입력된 데이터를 조회, 수정, 삭제, 입력하는 역할을 하는 언어를 말합니다. 데이터베이스 사용자가 질의어를 통하여 저장된 언어를 실질적으로 처리하는데 사용하는 언어입니다.
* 데이터 정의어(DDL: Data Definition Language) +
데이터베이스를 정의하는 언어를 말하며, 저장된 데이터의 스키마를 정의하여 데이터가 저장되는 형식을 정의하는데 사용됩니다.
* 데이터 제어어(DCL: Data Control Language) +
데이터베이스에 대한 접근을 제어하기 위한 언어요소로, 데이터에 대해 접근 권한을 허가하고 박탈하는데 사용됩니다.

link:./14_concurrency.adoc[다음: 동시 접근 및 복구]