== 동시 접근 및 복구

* 데이터베이스에는 수 많은 사용자가 동일한 데이터에 동시 접근함
** 각 사용자의 요구사항을 상호 독립적으로 수행
** DBMS는 다른 사용자가 동일한 데이터에 접근하고 있다는 것을 사용자 관점에서 무시해도 되도록 동작
* 시스템의 장애 순간에도 일관성을 유지할 수 있도록 동작
** 장애 발생 순간에 동작에 참여중이던 데이터에 대한 일관성 유지
** 시스템이 재시동된 후 모든 데이터를 일관성 있는 상태로 유지해야 함

== 동시 접근 제어
극장 좌석을 예약하는 시스템을 생각해봅시다. 인기 있는 영화의 경우 여러 명의 사용자들이 동시에 좋은 좌석을 예매하기 위해 데이터베이스에 접근할 것입니다. 이 경우 비슷한 시간에 같은 좌석 데이터에 접근하여 예매를 시도할 경우 전통적인 공유자원 문제가 발생합니다. 이는 극장 좌석 예매뿐만이 아니라 온라인 쇼핑, 항공 예매, 자원 예약 등 다양한 분야에서 발생하는 공통적인 문제입니다. 

은행 데이터베이스는 공유 자원 동시 사용의 다른 예입니다. 어떤 사용자의 응용 프로그램이 모든 계좌의 예금액 합계를 계산하고 있는데 다른 응용 프로그램이 앞의 응용 프로그림이 이미 조회한 계좌로부터 아직 조회하지 않은 계좌로 송금을 실행했을 경유, 예금액 합계는 실제보다 크게 나오게 됩니다. 은행 업무에서는 이런 부작용이 발생해서는 안됩니다. 여러 명의 사용자들이 데이터베이스의 특정 데이터 동시에 접근하게 되면 충돌을 피하기 위해 데이터베이스 관리 시스템은 요청들의 순서를 정해야 합니다. 



동시 접근을 제어함으로써 사용자들이 동일한 데이터에 동시에 접근하고 있다는 것을 무시해도 되도록 하는 것은 데이터베이스 관리 시스템의 중요한 임무중의 하나입니다. 데이터베이스 관리 시스템이 이러한 기능을 지원하므로 임해 사용자는 자신의 프로그램이 마치 격리되어 수행되는 것 처럼 생각하고 사용할 수 있습니다. 은행 데이터베이스를 예로 들면, 동일 계좌에 대하 예금하는 프로그램과 인출하는 프로그램이 동시에 요청되면 이들 중 어떤 프로그램이 먼저 수행되어도 무방하지만, 두 프로그램의 수행 단계들이 서로 간섭하는 형태로 교대로 수행되어서는 안된다는 말입니다. 이런 프로그램의 실행 단위를 `트랜잭션(Transaction)` 이라고 합니다.

== 복구
데이터베이스 관리 시스템은 시스템이 장애가 발생하더라도 그 후 시스템이 재시동되고 나면 모든 데이터(사용 중이던 응용 프로그램들이 데이터에 적용한 변경 등의 상태)를 일관적인(consistent) 상태로 반드시 회복시킴으로써 사용자가 이러한 장애로부터 보호받도록 해야 합니다.

항공권 예약을 요청하고 예약이 완료되었다고 응답한 상태라면, 어떤 순간에 시스템에 장애가 발생하더라도 그 예약 정보를 잃어버리면 안된다는 것입니다. 

또한 데이터베이스 관리 시스템이 해당 요청에 대해 응답을 하지 않은 상태로 데이터 변경을 수행하고 있는 도중에 장애가 발생했다면, 시스템이 복구된 후 이러한 부분적인 변경이 없었던 것으로 무효화(undo)하여야 합니다.

만약 데이터베이스 관리 시스템이 계좌 A로부터 계좌 B로 송금하는 과정에서 A 계좌에서 돈을 인출한 후 B에 입금하기 전 장애가 발생하였다면, 시스템이 복구된 후에는 계좌 A에서 인출한 금액이 원상복구되어야 합니다. 

이런 문제를 해결하기 위해 데이터베이스 관리 시스템은 `트랜잭션(Transaction)` 이라는 사용자 응용 프로그램 실행 단위를 사용합니다.

link:./14_transaction.adoc[다음: 트랜잭션]