= 디스크의 성능

HDD 

* DBMS가 작업을 수행하려면 데이터는 주 기억장치에 있어야 함
* 디스크와 주 기억장치 간의 데이터 전송 단위는 HDD의 경우 블록이므로 블록 내의 항목 중 하나만 필요한 경우라도 블록 또는 페이지의 전체 데이터가 전송되어야 함
* 블록과 페이지 입출력은 데이터 위치에 좌우됨 +
접근 시간 = 탐색시간 + 회전 지연 시간 + 전송 시간

SSD

* HDD와는 다르게 탐색 지연 시간, 회전 지연 시간이 없이 전송 시간만 소요되므로 임의적 읽기에서도 일정한 응답 속도가 보장됨
* 쓰기의 경우 비어있는 공간이 없으면 공간을 초기화하고, 이 작업 시간 동안 해당 공간에 대한 I/O 작업이 대기 상태가 됨

---

데이터가 HDD에 저장될 경우, 다음과 같은 내용을 생각해 볼 수 있습니다.

1.	DBMS가 작업을 수행하려면 데이터는 주 기억장치에 있어야 함 +
2.	디스크와 주 기억장치 간의 데이터 전송 단위는 HDD의 경우 블록이므로 블록 내의 항목 중 하나만 필요한 경우라도 블록 또는 페이지의 전체 데이터가 전송되어야 함 +
3.	블록과 페이지 입출력은 데이터 위치에 좌우됨 +
접근 시간 = 탐색시간 + 회전 지연 시간 + 전송 시간

HDD의 경우 데이터가 디스크에 저장되어 있는 형태에 따라 데이터베이스 연산에 영향을 미친다는 것을 알 수 있습니다. 디스크에 블록을 저장하거나 디스크에서 블록을 판독해 오는 시간은 데이터베이스 연산에 소요되는 시간의 대부분을 차지합니다. 디스크의 기하학적 기계적 특성상 이 시간을 최소화하기 위해서는 디스크 상에 데이터 레코드를 전략적으로 배치할 필요가 있습니다. 본질적으로, 만일 두 레코드가 같이 사용되는 경우가 많다면 그 두 레코드는 가까운 위치에 배치하여야 합니다. 두 레코드를 가장 가깝게 배치하는 방법은 같은 블록에 저장하는 것입니다. 다음으로 같은 트랙, 같은 실린더, 그 다음은 인접한 실린더가 됩니다.

데이터가 SSD에 저장될 경우, SSD는 HDD와는 다르게 탐색 시간, 회전 지연 시간이 없이 전송 시간만 소요되므로 임의적인 읽기에서도 일정한 응답 속도가 보장됩니다. 쓰기의 경우에는 비어있는 공간이 없으면 공간을 초기화하고, 이 작업 시간 동안 해당 공간에 대한 I/O 작업이 대기 상태가 됩니다.

link:./09_disk_space_mgt.adoc[다음: 디스크 공간 관리]