= 버퍼 교체 전략

* LRU (Least Recently Used) +
pin_count가 0인 프레임들에 대란 포인터로 큐를 생성
* Clock +
LRU의 변형으로, 1부터 N 사이의 값인 current 변수를 사용하여 교체용 페이지를 선정
* FIFO (First In First Out), MRU(Most Recently Used), Random등의 방식을 사용

---

버퍼 풀의 사용되지 않는 페이지 중 어떤 페이지를 교체할 것인지를 선택하는 전략에 따라 데이터베이스의 연산 시간이 상당히 달라질 수 있습니다. DBMS는 페이지 교체에 대한 전략을 수립하고 실행하는데, 대표적인 교체 전략은 아래와 같습니다.

* LRU(Least Recently Used) +
가장 최근에 사용한 페이지를 교체하는 전략으로, 버퍼 관리자에서 pin_count가 0인 프레임들에 대한 포인터로 큐를 만들면 이 방법을 구현할 수 있습니다. 어떤 프레임의 pin_count가 0이 될 때, 큐의 끝에 그 프레임을 삽입합니다. 교체할 페이지로 선택되는 페이지는 큐의 처음에 있는 프레임에 적재된 페이지입니다.
* Clock +
LRU의 변형으로, 1부터 N 사이의 값을 가지는 current 변수를 사용하여 교체용 페이지를 선정하는 방법입니다. N은 프레임의 수로, N이 되면 1로 돌아갑니다. 프레임은 시계처럼 원형으로 배치되어 있고, current 변수는 시계 바늘처럼 그 원판위를 움직이는 형태가 됩니다. LRU처럼 동작하기 위하여 프레임마다 reference 비트가 있는데, 페이지의 pin_count 값이 0이 되면 비트가 꺼집니다.
+
current 프레임부터 교체가 가능한지 점검해 나가며, 그 프레임이 교체 대상이 될 수 없으면 current의 값이 1 증가하고 다음 프레임을 점검합니다. 교체 대상 페이지를 선정할 때 까지 이 작업을 반복합니다. current 프레임의 reference 비트가 켜져 있으면 알고리즘은 referenced 비트를 끄고 current를 1증가 시켜 최근에 참조되었던 페이지는 교체될 확률이 적도록 합니다. current 프레임의 pin_count 값이 0이고 referenced 비트가 꺼져 있는 경우에는 페이지를 교체용으로 선정합니다.

LRU 전략과 Clock 전략이 항상 좋은 성능을 나타내는 것은 아닙니다. 특히 데이터베이스를 순차적으로 스캔해야 할 경우에는 연쇄 범람(Sequential flooding)이 발생할 수 있습니다.

이외에는 DBMS에 따라 FIFO(First In First Out), MRU(Must Recently Used), Random등의 교체 전략을 사용합니다.

link:./15_buffer_management.adoc[다음: 버퍼 관리 기법 비교]