= ISAM

* 색인 순차 접근 방식(Indexed Sequential Access Method) 파일
* 데이터를 순서대로 저장하거나 특정 항목을 색인으로 처리할 수 있는 파일 처리 방법
* 인덱스를 순차적으로 구성하여 큰 인덱스의 성능 문제를 해결
** 인덱스 파일이 클 경우, 인덱스를 계층화하여 인덱스에 대한 인덱스를 생성
** 완전한 정적 구조로, 인덱스 계층의 페이지가 수정되지 않음
* 파일 구조
** 인덱스 구역(비 단말 페이지) +
기본 구역에 있는 레코드들의 위치를 찾아가는 인덱스가 기록되는 구역
** 기본 구역(기본 단말 페이지) +
실제 레코드들을 기록하는 부분으로, 각 레코드는 키 값 순으로 저장
** 오버플로우 구역(오버 플로우 페이지) +
기본 구역에 빈 공간이 없을 경우 새 레코드의 삽입을 위한 예비적 구역

---

만약 데이터가 힙 형식 파일에 저장되어 있고, “가격이 3000원보다 높은 상품을 모두 찾아라”라는 쿼리가 실행된 경우를 생각해 봅시다. 힙 형식의 파일에서 이와 같은 범위 셀렉션 질의에 응답하기 위해서는 전체 파일을 스캔해야 합니다. 

파일이 정렬된 경우라면 이진 검색을 수행할 수 있습니다. 하지만 파일이 큰 경우라면 비용이 많이듭니다. 이와 같은 경우에서 데이터의 빠른 처리를 위한 파일 구조가 ISAM 형식입니다. ISAM 파일은 데이터에 대한 인덱스를 만들고, 인덱스를 이진 검색해서 범위 셀렉션을 만족하는 페이지를 찾아내고 포인터를 찾아가서 그 첫 번째 레코드가 있는 페이지로 이동하여, 데이터를 순차적으로 스캔하여 질의에 만족하는 레코드들을 검색합니다. 

인덱스에 있는 엔트리의 크기는 페이지의 크기보다 훨씬 작고 데이터 파일의 페이지 당 하나의 엔트리만 만들기 때문에 인덱스는 데이터보다 일반적으로 훨씬 작습니다. 그러므로 인덱스 파일의 이진 탐색은 데이터 파일의 이진 탐색보다 훨씬 빠릅니다. 하지만 인덱스가 큰 경우 삽입과 삭제의 비용이 높을 수 있습니다.

ISAM은 이런 인덱스가 큰 경우에 대한 문제를 해결하기 위해 착안 되었습니다. 보조 자료구조를 만드는 단계를 인덱스에도 적용하여 마지막 보조 자료구조가 한 페이지에 들어갈 때 까지 반복하여 데이터를 찾는 방법이 적용된 파일이 ISAM입니다. ISAM의 구조는 완전히 정적이기 때문에 낮은 수준의 최적화가 쉽습니다. 

트리의 각 노드는 디스크 페이지 하나에 해당하며, 데이터들은 모두 단말 페이지에 들어갑니다.

기본적인 연산인 삽입, 삭제, 검색은 대단히 간단합니다. 동등 셀렉션 탐색의 경우 루트 노드부터 시작하여 그 키 값에 해당하는 레코드가 어느 서브트리에 있을지를 판단합니다. 범위 셀렉션의 경우에는 데이터 구역에서의 시작점을 같은 방식으로 알아낸 후, 데이터 페이지를 순차적으로 스캔합니다. 삽입이나 삭제의 경우에는 탐색과 같은 방법으로 알맞은 페이지를 결정해서 레코드를 삽입하거나 삭제하는데, 이때 필요하다면 오버 플로우 페이지를 추가합니다.

ISAM에서 삽입과 삭제는 단말 페이지의 내용에만 영향을 주게 됩니다. 이 경우 하나의 단말 노드에 많은 삽입이 수행될 때 긴 오버 플로우 체인을 만들 가능성이 있습니다. 이런 긴 체인이 있으면 해당 단말 노드를 검색할 때 오버 플로우 체인을 그만큼 탐색하여야 하므로 레코드를 찾아내는 시간에 상당한 영향을 미치게 됩니다. 이를 위해 페이지에 약 20%의 여유 공간이 있도록 트리를 만듭니다. 이런 경우에도 트리가 가득 찼을 때 데이터가 삽입되면 오버 플로우 체인이 만들어지지 않을 수 없습니다.

단말 페이지만 수정될 수 있기 때문에 동시성 제어에서는 이점을 가지게 됩니다. 일반적으로 어떤 페이지를 접근하는 요청자는 자신이 이 페이지를 사용하고 있는 동안 다른 사용자들이 그 내용을 동시에 수정하지 못하도록 **잠금(Lock)**합니다. 페이지를 수정하려는 경우에는 그 페이지를 잠근 사용자가 없을 경우에만 허용되는 **전용(exclusive)** 잠금을 해야 합니다. 잠금을 설정하면 그 페이지에 대한 접근을 시도하는 사용자(더 정확히는 트랜잭션)을 기다리도록 할 수 있습니다.

인덱스 계층 페이지를 잠글 필요가 없는 것은 B+ 트리와 같은 동적 구조에 비해 커다란 이점이 됩니다. 만약 데이터의 분포와 크기가 상대적으로 정적이라면, 즉 오버 플로우 체인이 거의 없다면 ISAM은 B+ 트리보다 좋은 구조가 됩니다.

link:./27_Bplus_tree.adoc[다음: B+ 트리]