= 시스템 카탈로그

* 데이터베이스는 자신이 가지고 있는 모든 데이터에 대한 설명 정보를 저장함
* 관계형 데이터베이스 관리 시스템은 생성된 모든 릴레이션과 인덱스에 대한 정보를 유지 관리
* 시스템 카탈로그(System Catalog), 데이터 사전(Data Dictionary), 마스터 데이터베이스(Master Database), 메타데이터(Metadata)라고도 부름

---

데이터베이스 시스템의 근본적인 성질 중 하나는 자신이 가지고 있는 모든 데이터베이스에 대한 설명 정보를 유지한다는 것입니다. 관계형 데이터베이스는 자신에 속한 모든 릴레이션과 인덱스에 대한 정보를 유지 관리합니다. 또한 투플이 실제로 저장되지는 않은 뷰에 대한 정보도 유지관리 합니다. 뷰에 대한 정의를 저장해 두었다가 여기에 대한 질의를 받으면 그 뷰 정의를 이용해서 뷰에 속하는 투플을 계산해 냅니다. 

이런 정보는 시스템이 유지 관리하는 릴레이션인 **카탈로그 릴레이션(Catalog Relation)**에 저장됩니다. 이런 카탈로그 릴레이션이 저장되는 데이터베이스를 **시스템 카탈로그(System Catalog)**, **데이터 사전(Data Dictionary)**, **데이터 사전(Data Dictionary)**, **마스터 데이터베이스(Master Database)**등이라고도 부릅니다. 

시스템 카탈로그는 버퍼 풀의 크기나 페이지 크기와 같은 시스템 전반의 정보를 가지고 있으며, 이외에도 일반적으로 아래와 같은 정보를 저장합니다.

* 릴레이션
** 릴레이션 이름, 파일 이름(또는 어떤 형태의 식별자), 파일 구조
** 각 애트리뷰트의 이름과 타입
** 릴레이션과 관련된 인덱스 이름
** 무결성 제약 조건
* 인덱스
** 인덱스 이름, 인덱스 구조
** 탐색 키 애트리뷰트
*뷰
**뷰 이름과 정의

이 밖에 데이터베이스의 각 릴레이션에 대한 통계도 포함합니다.

* 릴레이션의 카디널리티
* 탐색 키가 취할 수 있는 서로 다른 값의 수
* 인덱스의 최소값과 최대값

시스템 카탈로그에는 또한 릴레이션과 필드에 대한 보안 정보도 포함됩니다.

* 계정 정보
* 릴레이션과 필드에 대한 접근 권한 정보

시스템 카탈로그도 일종의 릴레이션 집단이라는 사실은 매우 유용합니다. 카탈로그 릴레이션의 정보에는 다른 릴레이션과 마찬가지로 DBMS의 질의어를 통해 검색할 수 있습니다.

link:./30_lab3.adoc[다음: Lab 3]