= 셀렉션과 프로젝션

* 릴레이션에서 투플들을 선택(Selction)할 수 있는 연산자 시그마( δ )
* 필드들을 추출(Projection)할 수 있는 연산자 파이 ( π )
* 단일 릴레이션에 있는 데이터를 조작하는데 사용
* 셀렉션 연산자 δ는 셀렉션 조건을 통해 얻을 투플들을 명세
** 비교 연산자 <, <=, =, ≠, >= > 중의 하나를 op라고 할 때  +
애트리뷰트 op 상수 또는 애트리뷰트 op 애트리트뷰트 형태의 항을 불리언으로 조합
* 프로젝션 연산자 π는 릴레이션의 필드들을 추출

---

관계 대수에는 릴레이션에서 투플들을 선택(Selection)할 수 있는 연산자 시그마(δ)와 필드들을 투사(Projection)할 수 있는 연산자 파이(π)가 있습니다. 이 들 연산은 단일 릴레이션에 있는 데이터를 조작하는데 사용합니다.

셀렉션 연산자 δ는 셀렉션 조건을 통해 투플들을 명세합니다. 일반적으로 이 셀렉트 조건은 비교 연산자 <, <=, =, ≠, >=, >중의 하나를 op라고 표현할 때 애트리뷰트 op 상수 또는 애트리뷰트 op 애트리뷰트라는 형태의 항들을 불리언으로 조합한 것입니다. 논리 연산자 ∧와 ∨으로 연결한 식과 같습니다. 애트리뷰트에 대한 지칭은 위치나 이름으로 나타낼 수 있습니다.

아래와 같은 릴레이션 스키마가 있고,

_파일럿(파일럿번호: 정수, 파일럿이름: 문자열, 등급: 정수, 나이: 실수)_

릴레이션 스키마의 각 인스턴스 Pilot1이 아래와 같다고 할 때,

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|4	|안중근	|7	|32
|===

아래의 관계 대수식은

_δ~등급>5~(Pilot1)_ 

아래와 같은 릴레이션을 산출합니다. 셀렉션 결과의 스키마는 입력 릴레이션 스키마와 같습니다.

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|32	|이순신	|10	|47
|44	|안중근	|7	|32
|===

프로젝션 연산자 π는 한 릴레이션의 필드들을 추출합니다. 릴레이션 인스턴스 Pilot1에 대해 아래와 같은 연산을 적용하면

_π~파일럿이름,등급~(Pilot1)_

아래와 같은 릴레이션을 산출합니다. 식의 파일럿 이름, 등급은 추출할 필드들을 명세한 것으로서, 나머지 필드들은 모두 버리게 됩니다. 프로젝션 결과의 스키마는 프로젝션한 필드에 따라 결정됩니다.

[%header, cols=2, width=30%]
|===
|파일럿이름	|등급
|이순신	|10
|안중근	|7
|===

파일럿의 나이만 구하고 싶은 경우 아래와 같은 대수식을 쓸 수 있습니다.

_π~나이~(Pilot1)_

결과는 아래와 같습니다.

[%header, cols=1, width=20%]
|===
|나이
|44
|32
|===

릴레이션 인스턴스에는 나이가 44인 파일럿이 두 사람이지만 결과에는 투플이 하나만 존재합니다. 이는 릴레이션의 투플의 집합이라고 정의되었기 때문입니다. 

관계 대수식의 결과도 언제나 하나의 릴레이션이기 때문에 릴레이션이 나올 자리에 대수식을 넣을 수 있습니다. 앞의 두 예제 질의를 합성하여 하나의 릴레이션을 계산할 수 있습니다.

_π~파일럿이름,등급~(δ~등급>5~(Pilot1))_

결과는 아래와 같습니다.

[%header, cols=2, width=30%]
|===
|파일럿이름	|등급
|이순신	|10
|안중근	|7
|===

위 대수식은 Pilot1에 셀렉션을 먼저 적용하고 프로젝션을 적용합니다.

link:./05_set_operation.adoc[다음: 집합연산]