= 집합 연산

* 합집합, 교집합, 차집합, 카티션 프로덕트와 같은 표준 집합 연산
* 합집합(Union, ∪) +
인스턴스 R이나 인스턴스 S 모두에 속하는 투플들을 포함하는 릴레이션 인스턴스를 만듦 +
R과 S는 합병 가능해야 하며, 결과 스키마는 R의 스키마와 동일
* 교집합(Intersection, ∩) +
R ∩ S는 양쪽에 함께 속하는 모든 투플로 구성된 릴레이션 인스턴스를 만듦
* 차집합(Set-different, – ) +
R – S는 R에는 속하고 S에는 속하지 않는 투플로 구성된 릴레이션 인스턴스를 만듦
* 카디션 프로덕트(Cartisian Product, X) +
R X S는 R의 모든 필드와 S의 모든 필드를 순서대로 가지는 스키마의 릴레이션 인스턴스를 만듦 +
R X S는 r∈R, s∈S 쌍에 대하여 투플 <r, s>를 하나씩 가짐

---

합 집합 (Union, ∪), 교집합(Intersection, ∩), 차집합(Set-difference, –), 카티션 프로덕트(Cartisian Product, X)와 같은 표준 집합 연산들을 관계 대수에서도 사용합니다.

아래와 같은 릴레이션 스키마가 있고, 

_파일럿(파일럿번호: 정수, 파일럿이름: 문자열, 등급: 정수, 나이: 실수) +
비행기(비행기번호: 정수, 비행기이름: 문자열, 비행기종류: 문자열) +
운항(파일럿번호: 정수, 비행기번호: 정수, 운항일자: 날짜)_

아래의 파일럿의 인스턴스 Pilot1과 Pilot2, 운항 릴레이션의 인스턴스 Flight이 있을 때, 이 두 릴레이션 인스턴스를 기준으로 한 집합 연산 별 관계 대수 연산 결과를 보여줍니다.

Pilot1

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|===

Pilot2
[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|28	|김영랑	|9	|35
|32	|이순신	|10	|44
|45	|김소월	|5	|35
|64	|안중근	|7	|32
|===

Flight

[%header, cols=3, width=60%]
|===
|파일럿번호	|비행기번호	|운항일자
|13	|101	|2022-10-09
|44	|102	|2022-11-23
|===

== 합집합 (Union, ∪)

R∪S는 릴레이션 인스턴스 R이나 릴레이션 인스턴스 S 또는 양쪽 모두에 속하는 투플들을 모두 포함하는 릴레이션 인스턴스를 만듭니다. 이때 R과 S는 서로 합병 가능(Union-Compatible)해야 하며 그 결과의 스키마는 R의 스키마와 동일합니다.

두 릴레이션이 다음의 두 조건을 만족하면 이들을 서로 합병가능하다고 봅니다.

* 필드의 수가 같고
* 왼쪽부터 오른쪽으로 가면서 순서대로 대응되는 필드들의 도메인이 같음

_Pilot1 ∪ Pilot2_ 는 아래와 같습니다.

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|28	|김영랑	|9	|35
|45	|김소월	|5	|35
|===

== 교집합 (Intersection, ∩)

R∩S는 R과 S 양쪽에 함께 속하는 모든 투플로 구성된 릴레이션 인스턴스를 만듭니다. 릴레이션 R과 S는 합병 가능해야 하며, 결과 스키마는 R의 스키마와 동일합니다.

_Pilot1 ∩ Pilot2_ 는 아래와 같습니다.

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|===

== 차집합 (Set-Difference, –)

R–S는 R에는 속하고 S에는 속하지 않는 모든 투플로 구성된 릴레이션 인스턴스를 만듭니다. 릴레이션 R과 S는 합병 가능해야 하며 결과 스키마는 R의 스키마와 동일합니다.

_Pilot1 - Pilot2_ 는 아래와 같습니다.

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|===

== 카티션 프로덕트(Cartisian Product, X)

R X S는 R의 모든 필드와 S의 모든 필드를 순서대로 가지는 스키마의 릴레이션 인스턴스를 만듭니다. R X S에는 r∈R, s∈S 쌍에 대하여 투플 <r, s>를 하나씩 가집니다. <r, s>는 투플 r과 투플 s를 접합(concatenation)하여 만드는 투플을 의미합니다. 카티션 프로덕트 결과 릴레이션엔느 같은 이름을 같는 필드들이 있을 수 있기 때문에 명명 충돌이 발생합니다. 이런 필드들은 R X S에서 이름을 붙이지 않고 그 위치로만 지칭합니다.

_Pilot1 X Flight_ 는 아래와 같습니다.

[%header, cols=7, width=100%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|32	|이순신	|10	|44	|13	|101	|2022-10-19
|44	|안중근	|7	|32	|13	|101	|2022-10-19
|13	|홍길동	|1	|44	|44	|102	|2022-11-23
|32	|이순신	|10	|44	|44	|102	|2022-11-23
|44	|안중근	|7	|32	|44	|102	|2022-11-23
|===

카티션 프로덕트의 결과 릴레이션은 크기가 매우 클 수 있으며, 사용자가 실제로 원하는 결과는 카티션 프로덕트 결과의 일부인 경우가 대부분이므로 카티션 프로덕트 연산 자체는 많이 쓰이지 않습니다. 

link:./06_row.adoc[다음: 이름 바꾸기]