= 조인

* 둘 이상의 릴레이션으로 부터 정보를 조합하는 연산 (⋈)
* 유도된 연산으로, 카티션 프로덕트와 프로젝션 연산을 함께 실행하여 얻은 결과와 동일

[%header, cols="2,1,4" width=95%]
|===
|종류	|기호	|기능
|동등 조인	|⋈	|두 릴레이션간의 값을 가진 집합
|세타 조인	|⋈θ	|두 릴레이션 간의 비교 조건에 만족하는 집합
|자연 조인	|⋈N	|동등 조인에서 중복 속성을 제거
|세미 조인	|⋉ and ⋊ 	|자연 조인 후 기호의 열린쪽의 속성을 제거
|외부 조인 Left|⟕	 	|자연 조인 후 왼쪽의 모든 값을 추출, 값이 없을 경우 한쪽의 값을 NULL로 채용
|외부 조인 Right|⟖	 	|자연 조인 후 오른쪽의 모든 값을 추출, 값이 없을 경우 한 쪽의 값을 NULL로 채용
|외부 조인 Full|	⟗ 	|자연 조인 후 양쪽의 모든 값을 추출, 값이 없을 경우 한 쪽의 값을 NULL로 채용
|===

---

조인은 관계 대수식에서 가장 유용한 연산중의 하나로서, 보통 둘 이상의 릴레이션으로부터 정보를 조합해 낼 때 사용합니다. 관계 데이터베이스에서 두 개 이상의 릴레이션들의 관계를 다루는데 매우 중요한 연산자로, 조인은 카티션 프로덕트를 한 후에 프로젝션을 수행한 것과 같은 결과를 산출하지만 조인은 카티션 프로덕트보다 훨씬 적은 결과를 산출하기 때문에, 조인을 인식해서 구현하는 것이 중요합니다. 

아래와 같은 릴레이션 스키마가 있고, 

_파일럿([.underline]#파일럿번호:정수#, 파일럿이름:문자열, 등급:정수, 나이:정수) +
비행기([.underline]#비행기번호:정수#, 비행기이름:문자열, 비행기종류:문자열) +
운항([.underline]#파일럿번호:정수, 비행기번호:정수#, 운항일자:날짜)_

아래의 파일럿의 인스턴스 Pilot1과 Pilot2, 운항 릴레이션의 인스턴스 Flight이 있을 때, 이 두 릴레이션 인스턴스를 기준으로 한 집합 연산 별 관계 대수 연산 결과를 보여줍니다.
Pilot

[%header, cols=4, width=60%]
|===
|파일럿번호	|파일럿이름	|등급	|나이
|13	|홍길동	|1	|44
|32	|이순신	|10	|44
|44	|안중근	|7	|32
|===

Flight
[%header, cols=3, width=60%]
|===
|파일럿번호	|비행기번호	|운항일자
|13	|101	|2022-10-09
|44	|102	|2022-11-23
|===

== 세타 조인(Theta join)

세타 조인은 두 릴레이션 사이에서 비교 조건에 만족하는 값을 가진 릴레이션 인스턴스를 만듭니다.

릴레이션 R(a~1~, a~2~, ... a~n~)과 S(b~1~, b~2~, ... b~n~)이 있을 때, 릴레이션 R과 S의 세타 조인의 결과는 degree가 R~n~ + S~n~이고, R과 S의 모든 애트리뷰트를 가지며 조인 조건을 만족하는 모든 투플의 수가 카디널리티가 됩니다.

조인 조건은 R.a~1~ θ S.b~1~ 형태가 되며, θ는 {=, <>, <=, <, >=, >} 중의 하나가 됩니다. 세타 조인의 결과는 두 릴레이션의 카티션 프로덕트에 조인 조건을 적용한 결과와 동일합니다.

아래와 같은 관계 대수 연산을 적용하면

_Pilot ⋈θ ~pilot.파일럿번호>Flight.파일럿번호~Flight_

아래와 같은 릴레이션을 산출합니다.

[%header, cols=7, width=100%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|44	|안중근	|7	|32	|13	|101	|2022-10-19
|===

== 동등 조인(Equijoin)

동등 조인은 두 릴레이션 간의 같은 값을 가진 릴레이션 인스턴스를 만듭니다. 즉, 세타 조인 중에서 비교 연산자가 = 인 조인입니다.

아래와 같은 관계 대수 연산을 적용하면

_Pilot⋈ ~pilot.파일럿번호=Flight.파일럿번호~ Flight_

아래와 같은 릴레이션을 산출합니다
[%header, cols=7, width=100%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|44	|안중근	|7	|32	|44	|102	|2022-11-23
|===

== 자연 조인(Natural Join)

두 릴레이션의 공통된 애트리뷰트에 대해 동등 조인을 수행하고, 동등 조인의 결과 릴레이션에 있는 두 개의 조인 애트리뷰트 중 하나를 제외한 조인으로, 여러가지 조인 연산자 중 가장 많이 사용됩니다.


== 외부조인 Left (Left outer join)

자연(동등) 조인 후 왼쪽의 모든 값을 추출하고, 오른쪽에 해당 값이 없는 경우 한 쪽의 값을 NULL로 처리합니다.

아래와 같은 관계 대수 연산을 적용하면,

_Pilot ⟕ pilot.파일럿번호=Flight.파일럿번호 Flight_

아래와 같은 릴레이션을 산출합니다.

[%header, cols=7, width=90%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|32	|이순신	|10	|44	|NULL	|NULL	|NULL
|44	|안중근	|7	|32	|13	|101	|2022-10-19
|===

== 외부 조인 Right
자연(동등) 조인 후 오른쪽의 모든 값을 추출하고, 왼쪽에 해당 값이 없는 경우 한 쪽의 값을 NULL로 처리합니다.

아래와 같은 관계 대수 연산을 적용하면,

_Pilot ⟖ pilot.파일럿번호=Flight.파일럿번호 Flight_

아래와 같은 릴레이션을 산출합니다.

[%header, cols=7, width=90%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|44	|안중근	|7	|32	|13	|101	|2022-10-19
|===

== 외부 조인 FULL
자연(동등) 조인 후 양쪽의 모든 값을 추출합니다. 값이 없을 경우 한 쪽의 값을 NULL로 처리합니다.

아래와 같은 관계 대수 연산을 적용하면

_Pilot ⟗ pilot.파일럿번호=Flight.파일럿번호 Flight_

아래와 같은 릴레이션을 산출합니다.

[%header, cols=7, width=90%]
|===
|(파일럿번호)	|파일럿이름	|등급	|나이	|(파일럿번호)	|비행기번호	|운항일자
|13	|홍길동	|1	|44	|13	|101	|2022-10-19
|32	|이순신	|10	|44	|NULL	|NULL	|NULL
|44	|안중근	|7	|32	|13	|101	|2022-10-19
|===

link:./08_quiz.adoc[다음: Quiz 관계 대수 질의]