= Lab 12-2a: 잠금 (MySQL)

이 연습에서는 같은 데이터 객체에 두 트랜잭션이 접근할 때 발생할 수 있는 여러 문제를 해결할 수 있는 잠금과, 잠금 해제를 기다리는 관계에 사이클이 생기는 경우에 발생하는 deadlock이 발생하는 상황을 시뮬레이션하고 살펴봅니다.

1. macOS에서는 터미널, Windows에서는 명령 프롬프트를 실행합니다. (터미널 1로 호칭합니다)
2. 아래 명령을 실행하여 MySQL 콘솔에 접근합니다.
+
----
$ mysql -u root -p
Enter password:
----
+
3. 아래 명령을 수행하여 Deadlock 감지를 수행하지 않도록 설정합니다.
+
[source, sql]
----
set global innodb_deadlock_detect = off;
----
+
4. 아래 명령을 수행하여 터미널 1의 프로세스가 가진 잠금을 확인합니다.
+
[source, sql]
----
SELECT * FROM performance_schema.data_locks;
----
+
5. macOS에서는 터미널, Windows에서는 명령 프롬프트를 하나 더 실행합니다. (터미널 2로 호칭합니다)
6. 터미널 2에서 아래 명령을 실행하여 MySQL 콘솔에 접근합니다.
+
----
$ mysql -u root -p
Enter password:
----

== 연습 1: 잠금

이 연습에서는 MySQL의 기본적인 잠금에 대해 연습합니다. 아래 절차를 따릅니다.

1. 터미널 1에서, 아래 쿼리를 실행하여 Passenger 테이블의 인덱스를 확인합니다.
+
[source, sql]
----
SELECT index_name, column_name, cardinality, index_type FROM information_schema.statistics where table_name = 'Passenger';
----
+
----
+------------+-------------+-------------+------------+
| INDEX_NAME | COLUMN_NAME | CARDINALITY | INDEX_TYPE |
+------------+-------------+-------------+------------+
| PRIMARY    | PassengerNo |           7 | BTREE      |
+------------+-------------+-------------+------------+
1 row in set (0.00 sec)
----

=== 테이블 잠금

1. 터미널 1에서 아래 명령을 수행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)
----
+
2. 아래 명령을 수행하여 터미널 1의 프로세스 ID를 확인합니다.
+
[source, sql]
----
SELECT connection_id();
----
+
----
+-----------------+
| connection_id() |
+-----------------+
|               8 |
+-----------------+
1 row in set (0.00 sec)
----
+
3. 아래 질의를 시작하여 데이터에 대해 잠금을 수행합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
----
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           2 | 이순신        |    10 |   44 |
|           6 | 윤동주        |    10 |   26 |
+-------------+---------------+-------+------+
2 rows in set (0.00 sec)
----
+
4.	아래 명령을 수행하여 터미널 1의 프로세스가 잠근 객체를 확인합니다.
+
[source, sql]
----
SELECT engine, engine_transaction_ID, Thread_ID, Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks;
----
+
----
+--------+-----------------------+-----------+---------------+-------------+-----------+-----------+------------------------+
| engine | engine_transaction_ID | Thread_ID | Object_schema | object_name | Lock_type | Lock_Mode | Lock_data              |
+--------+-----------------------+-----------+---------------+-------------+-----------+-----------+------------------------+
| INNODB |                  4077 |        48 | Module06      | Passenger   | TABLE     | IX        | NULL                   |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | supremum pseudo-record |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 1                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 2                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 3                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 4                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 5                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 6                      |
| INNODB |                  4077 |        48 | Module06      | Passenger   | RECORD    | X         | 7                      |
+--------+-----------------------+-----------+---------------+-------------+-----------+-----------+------------------------+
9 rows in set (0.00 sec)
----
+
5. 터미널 2에서, 아래 쿼리를 실행하여 Passenger 테이블에서 등급이 3인 데이터에 대한 잠금 획득을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 3 FOR UPDATE;
----
+
쿼리는 결과를 보여주지 않고 대기하다가, 지정한 시간이 지나면 취소됩니다.
+
----
mysql> SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction
----
+
6. 터미널 2에서, 아래 쿼리를 실행하여 Passenger 테이블에서 등급이 9인 데이터에 대한 잠금을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
----
+
7. 터미널 1에서, 아래 명령을 실행하여 트랜잭션을 종료합니다.
+
[source, sql]
----
COMMIT;
----
+
8. 터미널 2에서, 쿼리가 실행되고 결과를 출력하는 것을 확인합니다.
+
----
mysql> SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           4 | 김영랑        |     9 |   54 |
|           5 | 김소월        |     9 |   45 |
+-------------+---------------+-------+------+
2 rows in set (7.05 sec)
----

=== 레코드 잠금

1. 터미널 1에서, 아래 쿼리를 실행하여 잠금 현황을 확인합니다.
+
[source, sql]
----
SELECT engine, engine_transaction_ID, Thread_ID, Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks;
----
+
2. 터미널 1에서, 아래 쿼리를 Passenger 테이블의 Grade 컬럼에 인덱스를 생성합니다.
+
[source, sql]
----
CREATE INDEX idx_passenger_grade ON Passenger(Grade);
----
+
3. 아래 명령을 실행하여 Passenger 테이블에 생성된 인덱스를 확인합니다.
+
[source, sql]
----
SELECT index_name, column_name, cardinality, index_type FROM information_schema.statistics where table_name = 'Passenger';
----
+
----
+---------------------+-------------+-------------+------------+
| INDEX_NAME          | COLUMN_NAME | CARDINALITY | INDEX_TYPE |
+---------------------+-------------+-------------+------------+
| idx_passenger_grade | Grade       |           5 | BTREE      |
| PRIMARY             | PassengerNo |           7 | BTREE      |
+---------------------+-------------+-------------+------------+
2 rows in set (0.01 sec)
----
+
4. 아래 명령을 실행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
5. 아래 쿼리를 실행하여 데이터에 대한 잠금을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
----
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           2 | 이순신        |    10 |   44 |
|           6 | 윤동주        |    10 |   26 |
+-------------+---------------+-------+------+
2 rows in set (0.00 sec)
----
+
6. 아래 쿼리를 실행하여 터미널 1의 프로세스가 잠근 객체를 확인합니다.
+
[source, sql]
----
SELECT engine, engine_transaction_ID, Thread_ID, Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks;
----
+
----
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+------------------------+
| engine | engine_transaction_ID | Thread_ID | Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data              |
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+------------------------+
| INNODB |                  4094 |        48 | Module06      | Passenger   | TABLE     | IX            | NULL                   |
| INNODB |                  4094 |        48 | Module06      | Passenger   | RECORD    | X             | supremum pseudo-record |
| INNODB |                  4094 |        48 | Module06      | Passenger   | RECORD    | X             | 10, 2                  |
| INNODB |                  4094 |        48 | Module06      | Passenger   | RECORD    | X             | 10, 6                  |
| INNODB |                  4094 |        48 | Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 2                      |
| INNODB |                  4094 |        48 | Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 6                      |
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+------------------------+
6 rows in set (0.00 sec)
----
+
7. 터미널 2에서, 아래 쿼리를 실행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
8. 터미널 2에서, 아래 쿼리를 실행하여 데이터에 대한 잠금을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
----
+
9. 아래 쿼리를 실행하여 터미널 2의 프로세스 ID를 확인합니다.
+
[source, sql]
----
SELECT connection_id();
----
+
결과는 아래와 유사할 것입니다.
+
----
+--------+
| trx_id |
+--------+
|   4095 |
+--------+
1 row in set (0.02 sec)
----
+
10. 아래 쿼리를 실행하여 터미널 2의 Transaction ID를 확인합니다.
+
[source, sql]
----
SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id();
----
+
결과는 아래와 유사할 것입니다.
+
+--------+
| trx_id |
+--------+
|   4095 |
+--------+
1 row in set (0.00 sec)
+
11. 아래 쿼리를 실행하여 터미널 2의 트랜잭션이 잠금을 획득한 데이터를 확인합니다.
+
[source, sql]
----
SELECT engine, engine_transaction_ID, Thread_ID, Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = 4095;
----
+
결과는 아래와 유사할 것입니다.
+
----
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+-----------+
| engine | engine_transaction_ID | Thread_ID | Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data |
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+-----------+
| INNODB |                  4095 |        49 | Module06      | Passenger   | TABLE     | IX            | NULL      |
| INNODB |                  4095 |        49 | Module06      | Passenger   | RECORD    | X             | 9, 4      |
| INNODB |                  4095 |        49 | Module06      | Passenger   | RECORD    | X             | 9, 5      |
| INNODB |                  4095 |        49 | Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 4         |
| INNODB |                  4095 |        49 | Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 5         |
| INNODB |                  4095 |        49 | Module06      | Passenger   | RECORD    | X,GAP         | 10, 2     |
+--------+-----------------------+-----------+---------------+-------------+-----------+---------------+-----------+
----

=== 실행중인 트랜잭션 확인

1. 터미널 1에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 확인합니다.
+
[source, sql]
----
SELECT trx_state, trx_tables_in_use, trx_tables_locked FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id();
----
+
결과는 아래와 유사할 것입니다.
+
----
+-----------+-------------------+-------------------+
| trx_state | trx_tables_in_use | trx_tables_locked |
+-----------+-------------------+-------------------+
| RUNNING   |                 0 |                 1 |
+-----------+-------------------+-------------------+
1 row in set (0.00 sec)
----
+
2. 터미널 2에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 확인합니다.
+
[source, sql]
----
SELECT trx_state, trx_tables_in_use, trx_tables_locked FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id
();
----
+
결과는 아래와 유사할 것입니다.
+
----
+-----------+-------------------+-------------------+
| trx_state | trx_tables_in_use | trx_tables_locked |
+-----------+-------------------+-------------------+
| RUNNING   |                 0 |                 1 |
+-----------+-------------------+-------------------+
1 row in set (0.00 sec)
----
+
3. 터미널 1에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 COMMIT 합니다.
+
[source, sql]
----
COMMIT;
----
+
4. 터미널 1에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 확인합니다.
+
[source, sql]
----
SELECT trx_state, trx_tables_in_use, trx_tables_locked FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id
----
+
----
Empty set (0.00 sec)
----
+
5. 터미널 2에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 COMMIT 합니다.
+
[source, sql]
----
COMMIT;
----
+
6. 터미널 1에서, 아래 쿼리를 실행하여 실행중인 트랜잭션을 확인합니다.
+
[source, sql]
----
SELECT trx_state, trx_tables_in_use, trx_tables_locked FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id();
----
+
----
Empty set (0.00 sec)
----

== 연습 2: 잠금 확인

=== 모니터링을 위한 터미널 실행

1.	macOS에서는 터미널, Windows에서는 명령 프롬프트를 하나 더 실행합니다. (터미널 3로 호칭합니다)
2.	터미널 3에서 아래 명령을 실행하여 MySQL 콘솔에 접근합니다.
+
----
$ mysql -u root -p
Enter password:
----

=== 터미널 1에서 잠금 획득

1. 터미널 1에서, 아래 쿼리를 실행하여 Passenger 테이블에 설정된 인덱스를 확인합니다.
+
[source, sql]
----
SELECT index_name, column_name, cardinality, index_type FROM information_schema.statistics where table_name = 'Passenger';
----
+
----
+---------------------+-------------+-------------+------------+
| INDEX_NAME          | COLUMN_NAME | CARDINALITY | INDEX_TYPE |
+---------------------+-------------+-------------+------------+
| idx_passenger_grade | Grade       |           5 | BTREE      |
| PRIMARY             | PassengerNo |           7 | BTREE      |
+---------------------+-------------+-------------+------------+
2 rows in set (0.01 sec)
----
+
2. 터미널 1에서, 아래 명령을 실행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
3. 터미널 1에서, 아래 쿼리를 실행하여 Grade가 10인 데이터에 대해 잠금을 요청합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
----
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           2 | 이순신        |    10 |   44 |
|           6 | 윤동주        |    10 |   26 |
+-------------+---------------+-------+------+
2 rows in set (0.00 sec)
----
+
4. 아래 쿼리를 실행하여 현재 세션이 잠근 데이터를 확인합니다.
+
[source, sql]
----
SELECT Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = (SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id());
----
+
----
+---------------+-------------+-----------+---------------+------------------------+
| Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data              |
+---------------+-------------+-----------+---------------+------------------------+
| Module06      | Passenger   | TABLE     | IX            | NULL                   |
| Module06      | Passenger   | RECORD    | X             | supremum pseudo-record |
| Module06      | Passenger   | RECORD    | X             | 10, 2                  |
| Module06      | Passenger   | RECORD    | X             | 10, 6                  |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 2                      |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 6                      |
+---------------+-------------+-----------+---------------+------------------------+
6 rows in set (0.00 sec)
----

=== 터미널 2에서 터미널 1에서 잠금을 획득한 데이터에 액세스

1. 터미널 2에서, 아래 쿼리를 실행하여 Passenger 테이블에서 Grade가 10인 데이터를 요청합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10;
----
+
----
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           2 | 이순신        |    10 |   44 |
|           6 | 윤동주        |    10 |   26 |
+-------------+---------------+-------+------+
2 rows in set (0.00 sec)
----
+
2. 터미널 2에서, 아래 쿼리를 실행하여 Passenger 테이블에서 Grade가 10인 데이터에 잠금을 요청합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
쿼리는 터미널 1의 트랜잭션이 잠금을 획득한 데이터에 대해 잠금을 획득하지 못합니다. timeout이 발생하여 쿼리가 종료될 때 까지 기다립니다.
+
3. 터미널 3에서, 아래 쿼리를 실행하여 프로세스를 확인합니다.
+
[source, sql]
----
show processlist;
----

=== 터미널 2에서 잠금 획득

1. 터미널 1에서 아래 쿼리를 실행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
2. 터미널 2에서 아래 쿼리를 실행하여 Passenger 테이블에서 Grade가 9인 데이터에 대해 잠금을 획득합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
----
+
----
+-------------+---------------+-------+------+
| PassengerNo | PassengerName | Grade | Age  |
+-------------+---------------+-------+------+
|           4 | 김영랑        |     9 |   54 |
|           5 | 김소월        |     9 |   45 |
+-------------+---------------+-------+------+
2 rows in set (0.00 sec)
----
+
3. 아래 쿼리를 실행하여 현재 세션이 잠근 데이터를 확인합니다.
+
[source, sql]
----
SELECT Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = (SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id());
----
+
----
+---------------+-------------+-----------+---------------+-----------+
| Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data |
+---------------+-------------+-----------+---------------+-----------+
| Module06      | Passenger   | TABLE     | IX            | NULL      |
| Module06      | Passenger   | RECORD    | X             | 9, 4      |
| Module06      | Passenger   | RECORD    | X             | 9, 5      |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 4         |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 5         |
| Module06      | Passenger   | RECORD    | X,GAP         | 10, 2     |
+---------------+-------------+-----------+---------------+-----------+
6 rows in set (0.00 sec)
----

=== Deadlock

1. 터미널 1에서 아래 쿼리를 실행하여 터미널 2에서 잠금을 획득한 데이터에 대해 잠금 획득을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
----
+
쿼리는 실행을 완료하지 않습니다. 잠금을 획득할 때 까지 기다립니다.
+
2. 터미널 2에서 아래 쿼리를 실행하여 터미널 1에서 잠금을 획득한 데이터에 대해 잠금 획득을 시도합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
쿼리는 실행을 완료하지 않습니다. 잠금을 획득할 때 까지 기다립니다.
+
3. 터미널 3에서, 아래 쿼리를 수행하여 프로세스를 확인합니다.
+
[source, sql]
----
show processlist;
----
+
----
+----+-----------------+------------------+----------+---------+-------+------------------------+-----------------------------------------------------+
| Id | User            | Host             | db       | Command | Time  | State                  | Info
            |
+----+-----------------+------------------+----------+---------+-------+------------------------+-----------------------------------------------------+
|  5 | event_scheduler | localhost        | NULL     | Daemon  | 34143 | Waiting on empty queue | NULL
            |
|  8 | root            | 172.17.0.1:34660 | Module06 | Query   |    23 | executing              | SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE  |
|  9 | root            | 172.17.0.1:38636 | Module06 | Query   |     4 | executing              | SELECT * FROM Passenger WHERE Grade = 10 FOR UPdate |
| 18 | root            | 172.17.0.1:36008 | Module06 | Query   |     0 | init                   | show processlist
            |
+----+-----------------+------------------+----------+---------+-------+------------------------+-----------------------------------------------------+
4 rows in set, 1 warning (0.00 sec)
----

== MySQL의 Deadlock detection

1. 터미널 1에서, 아래 명령을 수행하여 Deadlock 감지를 수행하지 않도록 설정합니다.
+
[source, sql]
----
set global innodb_deadlock_detect = on;
----
+
2. 터미널 1에서, 아래 쿼리를 수행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
3. 터미널 1에서, 아래 쿼리를 살행하여 Passenger 테이블의 Grade가 10인 데이터에 대해 잠금을 요청합니다.
+
[source, sql]
----
UPDATE Passenger SET Age = Age + 1 WHERE Grade = 10;
----
+
4. 터미널 1에서, 아래 쿼리를 실행하여 현재 트랜잭션이 잠금을 수행한 데이터를 확인합니다.
+
[source, sql]
----
SELECT Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = (SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id());
----
+
----
+---------------+-------------+-----------+---------------+------------------------+
| Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data              |
+---------------+-------------+-----------+---------------+------------------------+
| Module06      | Passenger   | TABLE     | IX            | NULL                   |
| Module06      | Passenger   | RECORD    | X             | supremum pseudo-record |
| Module06      | Passenger   | RECORD    | X             | 10, 2                  |
| Module06      | Passenger   | RECORD    | X             | 10, 6                  |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 2                      |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 6                      |
+---------------+-------------+-----------+---------------+------------------------+
6 rows in set (0.00 sec)
----
+
5. 터미널 2에서, 아래 쿼리를 실행하여 트랜잭션을 시작합니다.
+
[source, sql]
----
BEGIN;
----
+
6. 터미널 2에서, 아래 쿼리를 실행하여 Passenger 테이블의 Grade가 9인 데이터에 대해 잠금을 요청합니다.
+
[source, sql]
----
UPDATE Passenger SET Age = Age + 1 WHERE Grade = 9;
----
+
7. 터미널 1에서, 아래 쿼리를 실행하여 현재 트랜잭션이 잠금을 수행한 데이터를 확인합니다.
+
[source, sql]
----
SELECT Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = (SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id());
----
+
----
+---------------+-------------+-----------+---------------+-----------+
| Object_schema | object_name | Lock_type | Lock_Mode     | Lock_data |
+---------------+-------------+-----------+---------------+-----------+
| Module06      | Passenger   | TABLE     | IX            | NULL      |
| Module06      | Passenger   | RECORD    | X             | 9, 4      |
| Module06      | Passenger   | RECORD    | X             | 9, 5      |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 4         |
| Module06      | Passenger   | RECORD    | X,REC_NOT_GAP | 5         |
| Module06      | Passenger   | RECORD    | X,GAP         | 10, 2     |
+---------------+-------------+-----------+---------------+-----------+
6 rows in set (0.00 sec)
----
+
8. 터미널 1에서, 아래 쿼리를 실행하여 터미널 2에서 잠근 데이터에 대한 잠금을 요청합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 9 FOR UPDATE;
----
+
9. 터미널 2에서, 아래 쿼리를 실행하여 터미널 1에서 잠근 데이터에 대한 잠금을 요청합니다.
+
[source, sql]
----
SELECT * FROM Passenger WHERE Grade = 10 FOR UPDATE;
----
+
10. 터미널 1에서 Deadlock이 감지되고 트랜잭션이 중단되는 것을 확인합니다.
+
----
ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting transaction
----
+
11. 터미널 1에서, 아래 쿼리를 실행하여 현재 트랜잭션이 잠금을 수행한 데이터를 확인합니다.
+
[source, sql]
----
SELECT Object_schema, object_name, Lock_type, Lock_Mode, Lock_data FROM performance_schema.data_locks WHERE engine_transaction_ID = (SELECT trx_id FROM information_schema.innodb_trx WHERE trx_mysql_thread_id = connection_id());
----
+
----
Empty set (0.00 sec)
----
+
12. 터미널 2에서, 아래 쿼리를 수행하여 트랜잭션을 롤백합니다.
+
----
ROLLBACK;
----

---

link:./04-5_deadlock_detection.adoc[이전: 교착 상태 탐지] +
link:./04-lab12-2b.adoc[다음: Lab 12-2b: 잠금 (Microsoft SQL Server)]
