== 함수 종속
:stem: asciimath

* 함수 종속(Functional Dependency)는 일종의 제약 조건
* 어떤 릴레이션 스키마를 R이라고 하고 X와 Y를 R에 속한 속성 집합이라고 하고, R의 인스턴스 r에 속한 투플 t1과 t2가 다음의 조건을 만족하면 FD X → Y가 존재한다고 한다
+
stem:[t1.X = t2.X 이면 t1.Y = t2.Y]

* 한 릴레이션에 대해 적법한 인스턴스가 되려면 명세된 모든 FD를 만족해야 함
* 기본 키는 FD의 특수한 경우
** 키에 대한 속성은 X의 역할을 하게 되며, 나머지 속성은 Y의 역할을 함
** X → Y가 만족되고 X의 진부분집합 V가 있어서 V → Y가 만족되면 X는 수퍼키이지 키는 아님

---

**함수 종속(Functional Dependency)**는 일종의 무결성 제약조건으로, 키의 개념을 일반화한 것입니다. 

어떤 릴레이션 스키마를 R이라 하고 X와 Y를 R에 속한 속성의 집합인데 공집합이 아닌 경우, R의 한 인스턴스 r에 속한 어떤 투플의 쌍 t1과 t2가 다음 조건을 만족하면 FD X → Y가 존재한다고 합니다.

_t1.X = t2.Y 이면 t1.Y = t2.Y 이다._

여기에서 t1.X의 의미는 투플 t1을 X에 속한 속성들로 프로젝션 한다는 것으로서, 투플 관계 해석의 표기법 t.a가 투플 t의 속성 a를 지칭한다는 것을 확장한 것입니다. FD X → Y는 두 투플의 속성들의 값이 같다면 Y 속성의 값도 같아야 한다는 것을 의미합니다.

아래 릴레이션은 AB → C라는 함수 종속을 만족합니다.

[%header, cols=4, width=40%]
|===
|A	|B	|C	|D
|a1	|b1	|c1	|d1
|a1	|b1	|c1	|d2
|a1	|b2	|c2	|d1
|a4	|b1	|c3	|d1
|===

상위 두 투플은 FD가 키 제약조건과 같은 것이 아니라는 것을 보여줍니다. FD를 위반하지 않으면서도 AB는 이 릴레이션의 키가 아닙니다. 세 번째와 네 번째 투플을 보면 A 필드와 B 필드 중 하나라도 값이 달라지면 C 필드의 값도 달라질 수 있음을 알 수 있습니다. 투플 <a1, b1, c3, d1>을 추가하면 이 FD를 위반합니다.

어떤 릴레이션에 대해 적법한 인스턴스가 되려면 명세된 모든 FD를 비롯한 모든 무결성 제약조건을 만족해야 합니다. 몇 개의 릴레이션 인스턴스를 보고 그 FD를 만족한다고 바로 추론할 수는 없는데, FD는 무결성 제약 조건들과 마찬가지로 한 릴레이션의 모든 적법한 인스턴스에 대한 주문이기 때문입니다.

기본 키 제약조건은 FD의 특수한 경우입니다. 키에 속한 속성들은 X의 역할을 하게 되며, 그 릴레이션의 나머지 속성들은 Y의 역할을 하게 됩니다. 그렇지만 FD의 정의에서는 집합 X가 최소일 필요는 없는데 반하여, X가 키가 되려면 그 조건도 만족해야 합니다. 만일 X → Y가 만족되고, Y가 모든 속성의 집합이며, X의 진부분집합 V가 있어서 V → Y가 만족된다면 이때 X는 슈퍼 키이지, 키는 아닙니다.

link:./06_schema_refine.adoc[다음: 스키마 정제]