= 종속성 유지 분해

* FD 프로젝션
** R이라는 릴레이션 스키마가 있고 속성 집합 X와 Y로 된 두 개의 스키마로 분해 되며,
** R에 대한 FD의 집합을 F라고 할 때
** X에 속한 속성들에게만 관계되는 폐쇄 F+에 속한 FD 집합
* 종속성 유지 분해
** FD 집합 F를 가진 릴레이션 스키마 R을 속성 집합 X와 Y를 가진 두 스키마로 분해할 때
** (F~X~ ∪ F~Y~)^+^ = F^+^이면 종속성 유지 분해라고 함

---

아래와 같은 릴레이션이 있을 때,

----
Contract(ContractNo, SupplierID, SubjectID, DepartmentID, PartNo, Quantity, ValuePrice)
              C           S          J           D           P        Q         V
----

Contract 릴레이션의 함수 종속은 C → CSJDPQV, JP → C, SD → P가 있습니다. 이 경우 SD는 키가 아니므로 FD SD → P는 BCNF를 위반합니다.

이 위반 사항을 처리하기 위해 Contract 릴레이션을 CSJDQV와 SDP 두 릴레이션으로 분해할 수 있는데 이 분해는 무손실 조인 분해입니다. 여기에는 문제가 있는데, 무결성 제약조건 JP → C는 Contract 릴레이션에 한 투플이 삽입될 때 삽입되는 투플의 JP 값은 같지만 C 값은 다른 투플이 존재하지 않는가를 확인함으로써 쉽게 집행할 수 있습니다. 그러나 Contract 릴레이션을 CSJDQV과 SDP로 분해하고 나면 CSJDQV에 한 투플이 삽입될 때 마다 두 릴레이션을 조인해서 이 제약조건이 유지될 수 있는지를 일일이 확인해 주어야 합니다. 이런 분해를 종속성 유지 분해가 아니라고 합니다.

쉽게 말하면, 종속성 유지 분해란 투플 하나를 삽입하거나 수정할 때 하나의 릴레이션 인스턴스만 검사해보아도 FD들을 준수해 줄 수 있는 것을 말합니다. 종속성 유지 분해를 엄밀히 정의하기 위해서는 먼저 FD의 프로젝션이라는 개념을 이해해야 합니다.

R이라는 릴레이션 스키마가 있고 이것이 속성 집합 X와 Y로 된 두 개의 스키마들로 분해되며 R에 대한 FD 집합을 F라고 할 때, F의 X에 대한 프로젝션은 X에속한 속성들에만 관계되는 폐쇄 F^+ 에 속하는 FD의 집합입니다. 속성 X에 대한 F의 프로젝션을 F~X~로 표시할 때, F^+^에 속하는 종속성 U → V가 F~X~에 속하려면 U와 V에 속하는 모든 속성이 X에 속한 것이어야 합니다.

FD 집합을 F를 가진 릴레이션 스키마 R을 속성 집합 X와 Y를 가진 두 스키마로 분해할 때(F~X~ ∪ F~Y~)^+^ = F^+^이면 이 분해를 **종속성 유지분해** 라고 합니다. 즉 F~X~와 F~Y~에 속하는 종속성들을 구해서 그들을 합집한 것의 폐쇄를 계산하면 F의 폐쇄에 속하는 모든 종속성을 얻게 됩니다. 그러므로 FX와 FY에 속한 모든 종속성들만 집행하면 F+에 속한 모든 FD들도 만족한다는 것을 알 수 있습니다. FX를 집행하려면 릴레이션 X에 대한 삽입만 따져보면 됩니다.

F의 프로젝션을 구할 때 폐쇄 F^+^를 고려해야 하는 이유를 알기 위해, 속성 ABC를 가진 릴레이션 R이 속성 AB와 속성 BC의 두 릴레이션으로 분해된다고 가정합시다. R에 대한 FD의 집합 F에는 A → B, B → C, C → A가 들어있습니다. 물론 A → F는 F~AB~에 속하고 B → C는 F~BC~에 속합니다.

F의 폐쇄에는 F자체에 속한 모든 종속성에 대하여 A → C, B → A, C → B도 포함합니다. 따라서 F~AB~는 B → A도 포함하며 F~BC~는 C → B도 포함합니다. 그러므로 F~AB~ ∪ F~BC~에는 A → B, B → C, B → A, C → B도 들어있습니다. 따라서 F~AB~와 F~BC~에 속한 종속성 폐쇄에는 C → B, B → A 이행 법칙에 의거하여 C → A도 들어있게 됩니다. 그러므로 이 분해는 종속성 C → A를 그대로 유지합니다.

link:./18_BCNF.adoc[다음: BCNF로 분해]