= 스키마 정제 개요

* 정제되지 않은 스키마에서의 문제
** 중복 이상 +
어떤 데이터는 반복적으로 저장됨
** 갱신 이상 +
반복 저장된 데이터 중 한 투플을 갱신할 때 다른 모든 사본을 갱신하지 않으면 불일치 발생
** 삽입 이상 +
한 정보를 저장하려면 다른 정보도 같이 저장하여야 함
** 삭제 이상 +
어떤 정보를 지우면 다른 정보도 같이 삭제됨

---

스키마 정제가 필요하게 되는 문제들은 정보를 중복해서 저장하는데서 발생합니다. 분해를 하면 중복성은 없앨 수 있지만 그 자체의 문제점을 야기할 수도 있습니다.

== 중복성으로 발생하는 문제

* 중복 저장(Duplicate) +
어떤 정보는 반복적으로 저장된다.
* 갱신 이상(Update Anomaly) +
반복 저장된 데이터 중 한 사본을 갱신할 때 다른 모든 사본도 갱신하지 않으면 불일치가 발생한다.
* 삽입 이상(Insert Anomaly) +
어떤 정보를 저장하려면 다른 정보도 같이 저장해야 한다.
* 삭제 이상(Delete Anomaly) +
어떤 정보를 지우면 다른 정보도 같이 삭제된다.

아래와 같은 개체 집합의 경우를 생각해봅시다.

_Parttime_emp(EmpID, Name, Parkingslot, Grade, WagePerHr, Workingtime)_

Partime_emp의 키는 EmpID입니다. WagePerHr 속성이 Grade 속성에 의해 결졍된다고 가정합시다. 즉 WagePerHr는 Grade에 의해 결정되고 한 Grade에 해당하는 WagePerHr는 하나밖에 존재하지 않는 경우입니다. 이러한 무결성 제약조건이 바로 함수 종속성(Functional Dependency)의 한 예입니다. 이에 따라 Parttime_emp 릴레이션에는 중복성이 생길 수 있습니다.

[%headder, cols=6, width=60%]
|===
|EmpID	|Name	|Parkingslot	|Grade	|WagePerHr	|Workingtime
|1	|홍길동	|16	|8	|10,000	|40
|2	|이순신	|13	|8	|10,000	|30
|3	|김영랑	|87	|5	|7,000	|30
|4	|박목월	|37	|5	|7,000	|20
|5	|천상병	|25	|8	|10,000	|40
|===

만일 두 투플의 등급 필드에 같은 값이 저장된다면 이 무결성 제약 조건에 따라 WagePerHr 필드에도 같은 값이 저장되어야 합니다. 이러한 중복성 때문에 다름과 같은 결과가 나타납니다.

* 어떤 정보는 여러 번 저장될 수 있습니다. Grade 값 8은 WagePerHr 10,000과 대응하는데 이 연관성이 세 번 반복됩니다. 같은 정보를 여러 번 저장함에 따른 공간의 낭비도 문제지만, 중복 저장하게 되면 잠재적으로 불일치가 발생할 수 있습니다. 
* 첫 번째 투플의 WagePerHr 값은 갱신하였으나 두 번째 투플의 값은 갱신하지 않았다면 갱신 이상이 발생합니다.
* 한 직원의 투플을 삽입하려면 직원의 Grade 값에 따른 WagePerHr 값을 알아야 합니다. 삽입 이상이 발생합니다.
* 어떤 등급 값에 대한 모든 투플을 삭제한다면 그 등급 값과 그에 따른 WagePerHr의 연관성을 잃어버리게 됩니다. 삭제 이상이 발생합니다.

link:./04_decomposition.adoc[다음: 분해법]