= 분해법

* 속성을 부자연스럽게 묶어서 한 릴레이션 스키마로 만들면 중복성이 발생
* 함수 종속(Functional Dependency)를 이용하여 상황을 식별
** 릴레이션을 더 작은 릴레이션의 모임으로 대치
** 작은 일레이션은 본래 릴레이션 속성의 부분집합으로 이루어 짐
* 분해의 문제
** 릴레이션의 분해가 필요한가?
*** 제안된 정규형(Normal Form)으로 분해
** 분해했을 때 발생할 수 있는 문제는 무엇인가?
*** 무손실 조인(Lossless Join) 성질에 따라 릴레이션 인스턴스 복구
*** 종속성 유지(Dependency Preservation) 조건에 따라 계약 조건 유지

---

속성들을 부자연스럽게 묶어서 한 릴레이션 스키마로 만들면 중복성이 발생합니다. 함수 종속 관계를 이용하면 이러한 상황을 식별해 낼 수 있고 스키마를 정제할 필요성이 있는지를 파악할 수 있습니다. 기본적으로, 릴레이션을 더 작은 릴레이션으로 대치하면 중복성으로 비롯되는 많은 문제들이 처리될 수 있다는 것입니다. 더 작은 릴레이션은 원본 릴레이션의 진부분집합으로 이루어집니다. 이 과정을 큰 릴레이션을 여러 작은 릴레이션으로 **분해(Decomposition)**한다고 말합니다.

Parttime_emp 릴레이션을 아래와 같이 두 릴레이션을 분해하여 중복성을 피할 수 있습니다

_Parttime_emp(EmpID, Name, Parkingslot, Grade, WagePerHr, Workingtime)_
_HourlyWage(Grade, WagePerHr)_

Parttime_emp 인스턴스에 해당하는 이들 릴레이션의 인스턴스는 아래와 같습니다.

[%header, cols=5, width=50%]
|===
|EmpID	|Name	|Parkingslot	|Grade	|Workingtime
|1	    |홍길동	|16	|8	|40
|2	    |이순신	|13	|8	|30
|3	    |김영랑	|87	|5	|30
|4	    |박목월	|37	|5	|20
|5	    |천상병	|25	|8	|40
|===

[%header, cols=2, width=40%]
|===
|Grade	|WagePerHr
|8	|10,000
|5	|7,000
|===

HourlyWage 릴레이션에 투플 하나를 추가하면 어떠한 등급에 해당하는 시간당 임금도 쉽게 기록해 둘 수 있으며, Parttime_emp 릴레이션에 그 등급에 해당하는 직원이 없어도 무방합니다. Grade 값에 해당하는 직원이 없어도 무방합니다. Grade에 해당되는 WagePerHr 값을 변경하면 해당 임금이 변경됩니다. 이는 여러 투플을 갱신하는 것 보다 훨씬 효율적이고 불일치의 위험도 줄어듭니다. 삽입 이상과 삭제 이상또한 없어집니다.

== 분해에 따르는 문제

어떤 릴레이션의 스키마를 분해할 때 주의하지 않으면 원래보다 더 많은 문제가 발생할 수 있습니다. 

* 릴레이션의 분해가 필요한가?
* 릴레이션을 분해했을 때 발생할 문제는 무엇인가?

릴레이션의 분해가 필요한지에 대해서는, 릴레이션에 대한 몇 가지 **정규형(Normal Form)**들이 제안되어 있습니다. 어떤 릴레이션 스키마가 어느 한 정규형에 속한다면 특정 종류의 문제는 발생하지 않는다는 것을 보장할 수 있습니다. 주어진 릴레이션 스키마가 어떤 정규형에 속하는지 알고 있다면 더 분해할 필요가 있는지를 결정하는데 도움이 됩니다. 

릴레이션을 분해했을 때 발생할 문제가 있는지에 관해서는, **무손실 조인(Lossless-Join)** 성질에 따라 분해된 릴레이션은 항상 복구할 수 있고, **종속성 유지(Dependency-Preservation)** 성질에 따라 분해된 릴레이션 각각에 대해 일정 제약조건을 걸어주면 원래 릴레이션의 모든 제약조건이 그대로 유지될 수 있습니다. 

분해의 큰 결점중의 하나는 분해된 릴레이션을 조인해야 할 때가 많다는 것입니다. 이런 조인이 빈번하게 발생한다면 릴레이션을 분해함으로써 생기는 성능상의 손실이 있을 수 있습니다. 이런 경우 중복성의 문제를 놓아두고 릴레이션을 분해하지 않기로 결정하는 경우도 있습니다. 설계에 내재된 중복성으로 인해 야기될 수 있는 잠재적인 문제들을 충분히 인지하고 이를 피하기 위한 절차를 수행하는 것이 중요합니다.

데이터베이스 설계를 위해서는 정규형에 대한 정확한 이해가 필요합니다. 정규형으로 방지할 수 있는 문제가 무엇인지, 또는 할 수 없는 문제가 무엇인지 정확히 알고 있어야 하며, 분해의 기법과 분해로 생길 수 있는 잠재적인 문제들이 무엇인지 알고 있어야 합니다.

link:./05_functional_dependency.adoc[다음: 정규화와 정규형]