= 정규화(Normalization)

* 속성간의 종속성으로 인한 이상 현상이 발생하는 릴레이션을 분해하여 이상 현상을 없애는 과정
* 데이터의 중복 방지, 무결성을 충족하기 위한 데이터의 설계 방법
* 릴레이션 스키마가 어떤 정규형을 만족하는지 확인하는 테스트
* 정규화 원칙
** 무손실 법칙: 분해된 릴레이션이 표현하는 정보는 분해되기 전의 정보를 모두 포함
** 최소 데이터 중복 법칙: 이상 현상을 제거, 데이터 중복을 최소화
** 분리 법칙: 독립된 함수 종속은 독립된 릴레이션으로 분해
* 장점
** 이상 현상 해결
** 새 속성 추가시 데이터베이스 변경의 최소화
** 현실 세계의 개념간의 관게 표현

---

**정규화(Normalization)**는 릴레이션에 존재하는 속성간의 종속성으로 인한 이상 현상이 발생할 수 있는 경우를 방지하기 위해 릴레이션을 분해하여 이상현상을 없애는 과정입니다.

Dr. Codd가 처음 제안한 정규화 과정은 어떤 릴레이션 스키마가 어떤 정규형을 만족하는지 확인하는 일련의 테스트입니다. Codd는 제 1정규형, 제 2정규형, 제 3정규형이라고 이름 붙인 세 개의 정규형을 제안하였습니다. 그 후 Boyce와 Codd가 3정규형보다 더 강한 정의를 제안하고, BCNF(Boyce-Codd Normal Form)이라고 불렀습니다. 

이 정규형들은 모두 한 릴레이션의 속성 사이의 함수 종속을 기반으로 합니다. 이와는 달리 4 정규형과 5 정규형은 각각 조인 종속성과 다치 종속성을 기반으로 합니다. 

데이터의 정규화는 중복을 최소화하고, 삽입, 삭제, 갱신 이상을 최소화하기 위해 함수 종속과 기본 키를 기반으로 주어진 릴레이션 스키마를 분석하는 과정입니다. 어떤 조건(정규형 검사)들을 만족하지 못하는 적법하지 못한 릴레이션 스키마는 정규형 검사를 만족하는 더 작은 릴레이션 스키마들로 분해되어 적법한 특성을 갖게 됩니다. 정규화 과정은 다음 기능을 제공합니다.

* 릴레이션 스키마의 속성들 사이에 존재하는 함수 종속과 키들을 기반으로 그 스키마를 분석할 수 있는 정형적 구조
* 관계 데이터베이스를 임의의 수준으로 정규화할 수 있도록 개개의 릴레이션 스키마에서 수행할 수 있는 일련의 정규형 검사

한 릴레이션의 정규형은 그 릴레이션이 만족하는 가장 높은 정규형을 나타냅니다. 즉 그 릴레이션이 어느 정도까지 정규화 되었는가를 나타냅니다. 정규형들이 다른 요인들과 동떨어져서 고려되면 데잍베이스 설계를 보장하지 못합니다. 일반적으로 데이터베이스의 각 릴레이션 스키마가 BCNF 정규형인지 3 정규형인지 검사하는 것은 충분하지 않습니다. 그보다 분해에 의한 정규화 과정은 릴레이션 스키마들이 함께 가져야 하는 추가적인 특성들을 만족하도록 해야 합니다. 

* 무손실 법칙: 분해된 릴레이션이 표현하는 정보는 분해되기 전의 정보를 모두 포함해야 한다.
* 최소 데이터 중복법칙: 이상 현상을 제거하여 데이터의 중복을 최소화한다.
* 분리 법칙: 독립된 함수 종속은 독립된 릴레이션으로 분해한다.

추가적인 형태의 제약조건을 기반으로 적법한 기준을 만족하기 위해 추가적인 정규형이 제안될 수 있습니다. 그러나 정규형은 제약조건들에 근거하여 정의되므로 데이터베이스 설계자와 사용자가 그 제약조건들을 이해하거나 발견하기 어렵다면 정규형의 실질적인 유용성은 떨어지게 됩니다. 현재는 BCNF나 3NF 까지의 정규형만 고려하는 것이 일반적입니다.

다른 알아야 할 사항은 릴레이션을 항상 최상의 정규형으로 정규화 할 필요는 없다는 것입니다. 성능과 편의성을 위해서 릴레이션을 낮은 수준의 정규형으로 둘 수도 있습니다. 더 높은 정규형 릴레이션들을 조인한 결과를 기본 릴레이션으로 저장하는 과정을 **비정규화(Denormalization)**이라고 합니다.

link:./10_1nf.adoc[다음: 제 1정규형(First Normal Form)]