= Microsoft SQL Server 설치

== Ubuntu에서 Microsoft SQL Server 설치

이 연습에서는 Ubuntu 22.04에서 Microsoft SQL Server와 GUI 도구인 Azure Data Studio를 설치합니다.

=== Microsoft SQL Server 설치

1. 터미널을 실행합니다.
2. 아래 명령을 실행하여 apt를 업데이트합니다.
+
----
$ sudo apt update
----
3. 공개키를 다운로드하고, ASCII에서 GPG 형식으로 변환하고 필요한 위치에 씁니다.
+
----
$ curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg 
----
+
4. 아래 명령을 실행하여 SQL Server 리포지토리를 등록합니다.
+
----
$ curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list | sudo tee /etc/apt/sources.list.d/mssql-server-2022.list
----
5. 아래 명령을 실행하여 apt를 다시 업데이트합니다.
+
----
$ sudo apt update
----
+
6. 아래 명령을 실행하여 Microsoft SQL Server를 설치합니다.
+
----
$ sudo apt install -y mssql-server
----
+
7. 패키지 설치가 완료되면 아래 명령을 실행하여 설정을 시작합니다.
+
----
$ sudo /opt/mssql/bin/mssql-conf setup
----
+
_참고: SA 계정에 대해 강력한 암호를 지정해야 합니다. 대문자와 소문자, 0~9의 숫자 및 / 또는 영 숫자가 아닌 기호를 포함하여 최소 길이 8자가 필요합니다._
+
8. 아래 지시에서, 2를 입력하여 Developer Edition으로 지정합니다.
+
----
Choose an edition of SQL Server:
  1) Evaluation (free, no production use rights, 180-day limit)
  2) Developer (free, no production use rights)
  3) Express (free)
  4) Web (PAID)
  5) Standard (PAID)
  6) Enterprise (PAID) - CPU core utilization restricted to 20 physical/40 hyperthreaded
  7) Enterprise Core (PAID) - CPU core utilization up to Operating System Maximum
  8) I bought a license through a retail sales channel and have a product key to enter.
  9) Standard (Billed through Azure) - Use pay-as-you-go billing through Azure.
 10) Enterprise Core (Billed through Azure) - Use pay-as-you-go billing through Azure.

Details about editions can be found at
https://go.microsoft.com/fwlink/?LinkId=2109348&clcid=0x409

Use of PAID editions of this software requires separate licensing through a
Microsoft Volume Licensing program.
By choosing a PAID edition, you are verifying that you have the appropriate
number of licenses in place to install and run this software.
By choosing an edition billed Pay-As-You-Go through Azure, you are verifying 
that the server and SQL Server will be connected to Azure by installing the 
management agent and Azure extension for SQL Server.

Enter your edition(1-10): 2
----
+
9. 아래 지시에서, Yes를 입력하여 라이선스에 동의합니다.
+
----
The license terms for this product can be found in
/usr/share/doc/mssql-server or downloaded from: https://aka.ms/useterms

The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010&clcid=0x409

Do you accept the license terms? [Yes, No]: Yes
----
+
10. 아래 지시에서, SA 계정에 대한 암호를 입력합니다. +
_**참고: SA 계정에 대해 강력한 암호를 지정해야 합니다. 대문자와 소문자, 0~9의 숫자 및 / 또는 영 숫자가 아닌 기호를 포함하여 최소 길이 8자가 필요합니다.**_
+
----
Enter the SQL Server system administrator password: P@ssw0rd
Confirm the SQL Server system administrator password: P@ssw0rd
----
+
11. 설치와 설정이 완료됩니다. 

=== Microsoft SQL Server 명령줄 도구 설치

이 연습에서는 Microsoft SQL Server 명령줄 도구인 sqlcmd와 bpc를 설치합니다.

1. 아래 명령을 실행하여 리포지토리를 등록합니다.
+
----
$ curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
----
+ 
2. 아래 명령을 실행하여 apt를 업데이트 합니다.
+
----
$ sudo apt update
----
+
3. 아래 명령을 실행하여 unixODBC 개발자 패키지를 사용하여 설치 명령을 실행합니다.
+
----
$ sudo apt install mssql-tools18 unixodbc-dev
----
4. Configuration msodbcsql18 창에서 Yes를 선택하고 Enter키를 누릅니다.
5. 라이선스 동의 창에서 Yes를 선택하고 Enter 키를 누릅니다.
6. 설치가 완료되면, 아래 명령을 실행하여 설치된 Microsoft SQL Server의 동작을 확인합니다.
+
----
$ sudo systemctl status mssql-server
----

7. 아래 명령을 실행하여 설치된 Microsoft SQL Server에 액세스합니다.
+
----
$ /opt/mssql-tools18/bin/sqlcmd -U sa -C
----
+
8. 아래 질의를 실행하여 Microsoft SQL Server의 데이터베이스를 확인합니다.
+
[source, sql]
----
SELECT * FROM Sys.databases
GO
----
+
9. 아래 명령을 실행하여 sqlcmd 도구를 종료합니다.
+
----
exit
----


=== Azure Data Studio 설치

이 연습에서는 SQL Server에 액세스 할 수 있는 GUI 도구 Azure Data Studio를 설치합니다. 아래 절차에 따릅니다.

1. 터미널을 실행합니다.
2. 아래 명령을 실행하여 Azure Data Studio를 다운로드 합니다.
+
----
$ wget "https://go.microsoft.com/fwlink/?linkid=2198763" -O azuredatastudio.deb
----
+
3. 아래 명령을 실행하여 Azure Data Studio를 위한 종속성 라이브러리를 설치합니다.
+
----
$ sudo apt-get install libunwind8
----
+
4. 아래 명령을 실행하여 Azure Data Studio를 설치합니다.
+
----
$ sudo dpkg -i azuredatastudio.deb
----
+
5. 아래 명령을 실행하여 Azure Data Studio를 실행합니다.
+
----
$ azuredatastudio
----
