= Lab 8-1 실습 환경 구성

이 연습에서는 다양한 데이터베이스 환경에서 SQL 구문을 실습하기 위한 환경을 구축합니다. 아래 절차에 따릅니다.

== Oracle 실습 환경 구축

1. 터미널(또는 명령 프롬프트)를 실행합니다.
2. 아래 명령을 실행하여 oracle-xe 컨테이너 이미지를 검색합니다.
+
----
$ docker search jaspeen/oracle-xe-11g
----
+
3. 검색된 이미지를 확인하고, 아래 명령을 실행하여 oracle xe docker 이미지를 다운로드 합니다.
+
----
$ docker pull jaspeen/oracle-xe-11g
----
+
4. 아래 명령을 실행하여 다운로드된 docker 이미지를 확인합니다.
+
----
$ docker images
----
+
5. 아래 명령을 실행하여 oracle-xe-11g 컨테이터를 실행합니다.
+
----
$ docker run --name oracle11g -d -p 1521:1521 jaspeen/oracle-xe-11g
----
+
6. 아래 명령을 실행하여 실행중인 컨테이너를 확인합니다.
+
----
$ docker ps
----
+
7. 아래 명령을 실행하여 실행중인 컨테이너에 액세스합니다.
+
----
$ docker exec -it oracle11g sqlplus
----
+
8. Oracle sqlplus에서, 아래 명령을 실행하여 HR 사용자의 잠금을 해제하고 패스워드를 변경합니다.
+
----
SQL> ALTER USER HR IDENTIFIED BY P@ssw0rd ACCOUNT UNLOCK;
---- 
+
9. 아래 명령을 실행하여 현재 사용자를 HR 사용자로 전환합니다.
+
----
SQL> CONNECT HR/P@ssw0rd;
----
+
10. 아래 명령을 실행하여 현재 접속한 사용자를 확인합니다.
+
----
SQL> show user;
----
+
11. 아래 명령을 실행하여 테이블을 확인합니다.
+
----
SQL> SELECT * FROM tab;
----

== MS-SQL 실습 환경 구축

1. 터미널(또는 명령 프롬프트)를 실행합니다.
2. 아래 명령을 실행하여 Microsoft SQL Server 2022 for Linux 이미지를 검색합니다.
+
----
$ docker pull mcr.microsoft.com/mssql/server:2022-latest
----
3. 아래 명령을 실행하여 다운로드 한 docker 이미지를 확인합니다.
+
----
$ docker images
----
+
4. 아래 명령을 실행하여 Microsoft SQL Server 2022 이미지를 실행합니다.
+
----
$ docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=P@ssw0rd" -p 1433:1433 --name mssql2022 -d mcr.microsoft.com/mssql/server:2022-latest
----
5. 아래 명령을 실행하여 실행중인 docker 이미지를 확인합니다.
+
----
$ docker ps
----
+
6. 실행중인 Microsoft SQL Server 컨테이너를 확인하고, 아래 명령을 실행하여 container에 접속합니다.
+
$ docker exec -it mssql2022 bash
+
7. 아래 명령을 실행하여 /opt 디렉토리의 폴더를 확인합니다. 이동합니다.
+
$ ls /opt
+
8. mssql-tools 폴더를 확인합니다. 만약 mssql-tools 디렉토리가 존재하지 않으면 아래 명령을 실행하여 mssql 도구를 설치합니다.
+ 
$ sudo ACCEPT_EULA=Y apt-get install mssql-tools18 unixodbc-dev
+
9. 아래 명령을 실행하여 sqlcmd 를 실행하고 Microsoft SQL Server에 접속합니다.
+
$ /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd
+
10. sqlcmd 프롬프트에서 아래 명령을 실행하고 결과를 확인합니다.
[source, sql]
----
1> SELECT @@VERSION
GO
----

== PostgreSQL 실습 환경 구성

1. 터미널(또는 명령 프롬프트)를 실행합니다.
2. 아래 명령을 실행하여 PostgreSQL 이미지를 다운로드 합니다.
+
----
$ docker pull postgres
----
3. 아래 명령을 실행하여 다운로드 한 docker 이미지를 확인합니다.
+
----
$ docker images
----
+
4. 아래 명령을 실행하여 PostgreSQL 컨테이너를 실행합니다.
+
----
$ docker run -e "POSTGRES_PASSWORD=P@ssw0rd" -p 5432:5432 --name postgres -d postgres:latest
----
5. 아래 명령을 실행하여 실행중인 docker 컨테이너를 확인합니다.
+
----
$ docker ps
----
+
6. 아래 명령을 실행하여 실행중인 컨테이너에 접속합니다.
+
----
$ docker exec -it postgres bash
----
+
7. 아래 명령을 실행하여 postgres DBMS에 액세스 합니다.
+
----
# psql -U postgres
----
+
8. 아래 질의를 실행하여 test 데이터베이스를 생성합니다.
+
----
postgres=# create database pgtest;
----
+
9. 아래 명령을 실행하여 데이터베이스 연결을 test 데이터베이스로 변경합니다.
+
----
\c pgtest
----
+
10. 아래 명령을 실행하여 현재 데이터베이스를 확인합니다.
+
----
test=# select current_database();
----

== MySQL 실습 환경 설정

1. 터미널(또는 명령 프롬프트)를 실행합니다.
2. 아래 명령을 실행하여 MySQL 이미지를 다운로드 합니다.
+
----
$ docker pull mysql
----
+
3. 아래 명령을 실행하여 다운로드한 docker 이미지를 확인합니다.
+
----
$ docker images
----
+
4. 아래 명령을 실행하여 MySQL 컨테이너를 실행합니다.
+
----
$ docker run --name mysql82 -e "MYSQL_ROOT_PASSWORD=P@ssw0rd" -p 3306:3306 -d mysql:latest
----

5. 아래 명령을 실행하여 컨테이너에 액세스 합니다.
+
----
$ docker exec -it mysql82 mysql -u root -p
----
6. 연결된 MySQL에서, 아래 명령을 실행하여 test 데이터베이스를 생성합니다.
+
----
mysql> create database mysqltest;
----
