= SQL에서 DDL 구문

•	SQL 데이터 정의 언어 지침
**	CREATE +
릴레이션(테이블), 뷰, 인덱스, 저장 프로시저 등 데이터베이스 객체 생성
**	DROP +
존재하는 데이터베이스 객체 삭제
**	ALTER +
존재하는 데이터베이스 객체 수정
**	TRUNCATE +
테이블 내 데이터의 완전 삭제

---

SQL에서 지원하는 데이터 정의 언어는 데이터베이스 객체 생성을 위한 `CREATE` 문, 객체 삭제를 위한 `DROP` 문, 객체를 수정하는 `ALTER`, 객체와 데이터를 완전 삭제하는 `TRUNCATE` 등 크게 네가지 문으로 나눌 수 있습니다.

== CREATE 문
CREATE문은 관계 데이터베이스 관리 시스템에서 데이터베이스 객체를 생성합니다. 상용 RDBMS의 구현에 따라 생성할 수 있는 객체는 다르지만 대부분의 RDBMS에서 아래와 같은 데이터베이스 객체의 생성을 지원합니다.

* 테이블
* 도메인(데이터 타입)
* 인덱스
* 사용자
* 별칭
* 저장 프로시저
* 사용자 정의 함수
* 트리거
* 데이터베이스

기본 구문은 아래와 같습니다.

[source, sql]
----
CREATE [데이터베이스 객체 형식] [객체 이름]
[객체의 종류에 따른 정의]
----

== DROP 문
DROP문은 RDBMS에 존재하는 데이터베이스 객체를 제거합니다. 지워질 수 있는 객체의 종류는 RDBMS의 종류에 따라 다르지만, CREATE 문으로 생성된 대부분의 객체를 제거할 수 있습니다. 대부분의 RDBMS에서 DROP 문을 통해 삭제된 객체는 복원 이외의 방법으로 되살릴 수 없습니다.

기본 구문은 다음과 같습니다.

[source, sql]
----
DROP [데이터베이스 객체 형식] [객체 이름]
----

== ALTER 문

ALTER 문은 RDMS에 존재하는 데이터베이스 객체의 특성을 변경합니다. 변경할 수 있는 객체의 종류는 RDBMS의 종류에 따라 다르지만, CREATE 문으로 생성된 대부분의 객체의 특성을 변경할 수 있습니다. 테이블의 경우 ALTER 문을 통해 도메인, 개체, 참조 무결성을 위한 각 제약조건을 추가하고 삭제하며, 컬럼명을 변경하고 삭제하며 추가합니다. 데이터베이스 종류에 따라 테이블의 이름을 바꾸는데 RENAME 문이 사용되기도 합니다.

기본 구문은 아래와 같습니다.

[source, sql]
----
ALTER [데이터베이스 객체 형식] [객체 이름]
[객체의 종류에 따른 정의]
----

== TRUNCATE 문

TRUNCATE 또는 TRUNCATE TABLE 문은 테이블에서 모든 투플을 삭제합니다. 무결성 제약조건을 생략하여 모든 데이터의 빠른 삭제를 가능하게 합니다. 삭제할 행 각각을 기록하는 트랜잭션 로그의 출력을 방지함으로써 효율적으로 모든 행을 삭제할 수 있습니다.

TRUNCATE문의 결과는 테이블의 모든 투플을 삭제하는 DELETE 문과 결과는 동일하지만 동작은 다릅니다.

* WHERE 절을 지정할 수 없습니다. 모든 투플은 일괄 삭제됩니다.
* 대상 테이블에 대한 단독 잠금을 얻을 수 있습니다.
* 삭제시 외래 키의 무결성을 확인하지 않습니다.
* 일부 데이터베이스(Oracle, MySQL 등)에서 TRUNCATE문은 롤백 할 수 없습니다.
* 일부 데이터베이스(Microsoft SQL Server)에서 TRUNCATE TABLE문은 복제 및 로그 전달 대상인 테이블에 대해 실행할 수 없습니다.

구문은 아래와 같습니다.

[source, sql]
----
TRUNCATE [TABLE] 테이블 이름 [, 테이블 이름]
----

link:./08_create_alter_drop.adoc[다음: 테이블 생성, 수정, 삭제 DDL 문]