== 테이블 생성, 수정, 삭제 DDL 문

* 생성

[source, sql]
----
CREATE TABLE {Table Name} (
	[Column Name] [Data Type] {NULL | NOT NULL} {Column Option}
	{Constraint List} [Constraint definition]
)
----
* 수정

[source, sql]
----
ALTER TABLE [TableName] 
	{ALTER COLUMN} [COLUMN NAME] {Column Option}
	{ADD} (Column | Constraints} {ADD Option}
	{DROP} (Column | Constraints} {DROP Option}
----

* 삭제

[source, sql]
----
DROP TABLE [TableName]
----

---

관계 데이터베이스에서 데이터가 저장되는 유일한 객체인 테이블은 `CREATE`` 문을 사용해 생성되고, `ALTER` 문을 통해 수정되며 `DROP` 문을 통해 삭제됩니다.

== 테이블 생성

`CREATE` 문으로 테이블을 생성합니다. SQL 1999에 정의된 테이블 정의 구문은 아래와 같습니다.

[source, sql]
----
<table definition> ::=
CREATE [ <table scope> ] TABLE <table name>
<table contents source>
[ ON COMMIT <table commit action> ROWS ]

<table contents source> ::=
<table element list>
| OF <user-defined type>
[ <subtable clause> ]
[ <table element list> ]

<table scope> ::=
<global or local> TEMPORARY

<global or local> ::=
GLOBAL
| LOCAL

<table commit action> ::=
PRESERVE
| DELETE

<table element list> ::=
<left paren> <table element> [ { <comma> <table element> }... ] <right paren>

<table element> ::=
<column definition>
| <table constraint definition>
| <like clause>
| <self-referencing column specification>
| <column options>

<self-referencing column specification> ::=
REF IS <self-referencing column name> <reference generation>

<reference generation> ::=
SYSTEM GENERATED
| USER GENERATED
| DERIVED

<self-referencing column name> ::= <column name>

<column options> ::=
<column name> WITH OPTIONS <column option list>

<column option list> ::=
[ <scope clause> ]
[ <default clause> ]
[ <column constraint definition>... ]
[ <collate clause> ]

<subtable clause> ::=
UNDER <supertable clause>

<supertable clause> ::= <supertable name>

<supertable name> ::= <table name>

<like clause> ::= LIKE <table name>
----

SQL 1999에 정의된 컬럼 정의 구문은 아래와 같습니다.

[source, sql]
----
<column definition> ::=
<column name>
{ <data type> | <domain name> }
[ <reference scope check> ]
[ <default clause> ]
[ <column constraint definition>... ]
[ <collate clause> ]

<column constraint definition> ::=
[ <constraint name definition> ]
<column constraint> [ <constraint characteristics> ]

<column constraint> ::=
NOT NULL
| <unique specification>
| <references specification>
| <check constraint definition>

<reference scope check> ::=
REFERENCES ARE [ NOT ] CHECKED
[ ON DELETE <reference scope check action> ]

<reference scope check action> ::=
<referential action>

SQL 1999에 정의된 데이터 타입은 아래와 같습니다.
<data type> ::=
<predefined type>
| <row type>
| <user-defined type>
| <reference type>
| <collection type>

<predefined type> ::=
<character string type> [ CHARACTER SET <character set specification> ]
| <national character string type>
| <binary large object string type>
| <bit string type>
| <numeric type>
| <boolean type>
| <datetime type>
| <interval type>

<character string type> ::=
CHARACTER [ <left paren> <length> <right paren> ]
| CHAR [ <left paren> <length> <right paren> ]
| CHARACTER VARYING <left paren> <length> <right paren>
| CHAR VARYING <left paren> <length> <right paren>
| VARCHAR <left paren> <length> <right paren>
| CHARACTER LARGE OBJECT [ <left paren> <large object length> <right paren> ]
| CHAR LARGE OBJECT [ <left paren> <large object length> <right paren> ]
| CLOB [ <left paren> <large object length> <right paren> ]

<national character string type> ::=
NATIONAL CHARACTER [ <left paren> <length> <right paren> ]
| NATIONAL CHAR [ <left paren> <length> <right paren> ]
| NCHAR [ <left paren> <length> <right paren> ]
| NATIONAL CHARACTER VARYING <left paren> <length> <right paren>
| NATIONAL CHAR VARYING <left paren> <length> <right paren>
| NCHAR VARYING <left paren> <length> <right paren>
| NATIONAL CHARACTER LARGE OBJECT [ <left paren> <large object length> <right paren> ]
| NCHAR LARGE OBJECT [ <left paren> <large object length> <right paren> ]
| NCLOB [ <left paren> <large object length> <right paren> ]

<binary large object string type> ::=
BINARY LARGE OBJECT [ <left paren> <large object length> <right paren> ]
| BLOB [ <left paren> <large object length> <right paren> ]

<bit string type> ::=
BIT [ <left paren> <length> <right paren> ]
| BIT VARYING <left paren> <length> <right paren>

<numeric type> ::=
<exact numeric type>
| <approximate numeric type>

<exact numeric type> ::=
NUMERIC [ <left paren> <precision> [ <comma> <scale> ] <right paren> ]
| DECIMAL [ <left paren> <precision> [ <comma> <scale> ] <right paren> ]
| DEC [ <left paren> <precision> [ <comma> <scale> ] <right paren> ]
| INTEGER
| INT
| SMALLINT

<approximate numeric type> ::=
FLOAT [ <left paren> <precision> <right paren> ]
| REAL
| DOUBLE PRECISION

<length> ::= <unsigned integer>

<large object length> ::=
<unsigned integer> [ <multiplier> ]
| <large object length token>

<precision> ::= <unsigned integer>

<scale> ::= <unsigned integer>

<boolean type> ::= BOOLEAN

<datetime type> ::=
DATE
| TIME [ <left paren> <time precision> <right paren> ]
[ <with or without time zone> ]
| TIMESTAMP [ <left paren> <timestamp precision> <right paren> ]
[ <with or without time zone> ]

<with or without time zone> ::=
WITH TIME ZONE
| WITHOUT TIME ZONE

<time precision> ::= <time fractional seconds precision>

<timestamp precision> ::= <time fractional seconds precision>

<time fractional seconds precision> ::= <unsigned integer>

<interval type> ::= INTERVAL <interval qualifier>

<row type> ::=
ROW <row type body>

<row type body> ::=
<left paren>
<field definition> [ { <comma> <field definition> }... ]
<right paren>

<reference type> ::=
REF <left paren> <referenced type> <right paren>
[ <scope clause> ]

<scope clause> ::=
SCOPE <table name>

<referenced type> ::= <user-defined type>

<user-defined type> ::= <user-defined type name>

<collection type> ::=
<data type> <array specification>

<array specification> ::=
<collection type constructor>
<left bracket or trigraph> <unsigned integer> <right bracket or trigraph>

<collection type constructor> ::=
ARRAY
----

테이블에 투플을 삽입할 때 컬럼에 값이 삽입되지 않을 때 기본 값을 지정하는 DEFAULT의 SQL 1999 정의 구문은 아래와 같습니다.

[source, sql]
----
<default clause> ::=
DEFAULT <default option>

<default option> ::=
<literal>
| <datetime value function>
| USER
| CURRENT_USER
| CURRENT_ROLE
| SESSION_USER
| SYSTEM_USER
| CURRENT_PATH
| <implicitly typed value specification>
----

테이블에서 개체  무결성을 정의하는 제약조건의 SQL 1999 정의 구문은 아래와 같습니다.

[source, sql]
----
<table constraint definition> ::=
[ <constraint name definition> ]
<table constraint> [ <constraint characteristics> ]

<table constraint> ::=
<unique constraint definition>
| <referential constraint definition>
| <check constraint definition>
----

컬럼에 삽입되는 데이터의 유일성을 지정하는 UNIQUE의 SQL 1999 정의 구문은 아래와 같습니다. UNIQUE로 지정된 컬럼에는 같은 값이 삽입될 수 없습니다.

[source, sql]
----
<unique constraint definition> ::=
<unique specification> <left paren> <unique column list> <right paren>
| UNIQUE ( VALUE )
<unique specification> ::=
UNIQUE
| PRIMARY KEY
<unique column list> ::= <column name list>
----

참조 무결성을 지원하는 제약조건의 SQL 1999 정의 구문은 아래와 같습니다.

[source, sql]
----
<referential constraint definition> ::=
FOREIGN KEY <left paren> <referencing columns> <right paren>
<references specification>

<references specification> ::=
REFERENCES <referenced table and columns>
[ MATCH <match type> ]
[ <referential triggered action> ]

<match type> ::=
FULL
| PARTIAL
| SIMPLE

<referencing columns> ::=
<reference column list>

<referenced table and columns> ::=
<table name> [ <left paren> <reference column list> <right paren> ]

<reference column list> ::= <column name list>

<referential triggered action> ::=
<update rule> [ <delete rule> ]
| <delete rule> [ <update rule> ]

<update rule> ::= ON UPDATE <referential action>

<delete rule> ::= ON DELETE <referential action>

<referential action> ::=
CASCADE
| SET NULL
| SET DEFAULT
| RESTRICT
| NO ACTION
----

투플의 컬럼에 삽입될 수 있는 데이터를 제한하는 CHECK 제약조건의 SQL 1999 정의 구문은 아래와 같습니다.

[source, sql]
----
<check constraint definition> ::=
CHECK <left paren> <search condition> <right paren>
----

=== 테이블 생성 예제 (MySQL)

아래와 같은 릴레이션 스키마를 가진 릴레이션이 있을 때, 

_Category(CategoryNo: Integer, CategoryName: String) +
Product(ProductNo: Integer, SerialKey: String, ProductName: String, Price: Integer, State: String, Detail: String, Stock: Integer, TaxRate: Integer, CategoryNo: Integer)_

`Category` 테이블은 아래와 같이 생성할 수 있습니다. 아래와 같이 생성하면 기본 키가 없는 테이블이 생성됩니다.

[source, sql]
----
CREATE TABLE Category (
    CategoryNo      int,
    CategoryName    nvarchar(20)
);
----

아래와 같이 `CategoryNo` 컬럼에 기본 키를 지정할 수 있습니다.

[source, sql]
----
CREATE TABLE Category (
    CategoryNo      int    PRIMARY KEY,
    CategoryName    nvarchar(20)
);
----

아래와 같이 기본 키를 지정할 수도 있습니다.

[source, sql]
----
CREATE TABLE Category (
    CategoryNo    int,
    CategoryName  nvarchar(20),
    
    CONSTRAINT pk_Category PRIMARY KEY(CategoryNo)
);
----

기본 키가 `ProductNo` 인 `Product` 테이블을 생성하는 SQL 구문은 아래와 같이 작성할 수 있습니다. 

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12),
    ProductName	nvarchar(30),
    Price       int,
    State       nvarchar(4),
    Detail      text,
    Stock       int,
    TaxRate     int,
    CategoryNo  int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo)
);
----

아래와 같이 `SeriakKey` 컬럼에 유일한 값이 저장되도록 설정할 수 있습니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12)    UNIQUE,
    ProductName	nvarchar(30),
    Price       int,
    State       nvarchar(4),
    Detail      text,
    Stock       int,
    TaxRate     int,
    CategoryNo  int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo)
);
----

아래와 같이 `UNIQUE` 제약조건을 지정할 수도 있습니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12),
    ProductName	nvarchar(30),
    Price       int,
    State       nvarchar(4),
    Detail      text,
    Stock       int,
    TaxRate     int,
    CategoryNo  int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey)
);
----

아래 쿼리는 `SerialKey`, `ProductName`, `Price`, `State`, `Stock`, `TaxRate` 컬럼에 `NULL` 을 허용하지 않도록 지정합니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12)      NOT NULL,
    ProductName	nvarchar(30)  NOT NULL,
    Price       int           NOT NULL,
    State       nvarchar(4)   NOT NULL,
    Detail      text,
    Stock       int	          NOT NULL,
    TaxRate     int	          NOT NULL,
    CategoryNo  int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey)
);
----

아래 쿼리는 `Product` 테이블에 투플이 삽입되면서 `Stock` 컬럼에 데이터가 지정되지 않았을 때 기본 값으로 0을 지정합니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey   char(12)      NOT NULL,
    ProductName nvarchar(30)  NOT NULL,
    Price       int	          NOT NULL,
    State       nvarchar(4)   NOT NULL,
    Detail      text,
    Stock       int	          DEFAULT 0,
    TaxRate	    int	          NOT NULL,
    CategoryNo  int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey)
);
----

`State` 컬럼에 저장될 수 있는 데이터를 ‘신상’, ‘중고’, ‘반품’, ‘전시’로 제한하며 Product 테이블을 생성합니다.

[source, sql]
----
CREATE TABLE Product (
	ProductNo 	int, 
   	SerialKey	char(12)		NOT NULL,
   	ProductName	nvarchar(30)	NOT NULL,
    Price		int		NOT NULL,
    State		nvarchar(4)	NOT NULL CHECK (State IN (‘신상’,’중고’,’전시’));
    Detail		text,
    Stock		int		DEFAULT 0,
    TaxRate		int		NOT NULL,
    CategoryNo	int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey)
);
----

아래와 같이 `CONSTRAINT` 문을 사용해서 `CHECK` 제약조건을 설정할 수 있습니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12)		NOT NULL,
    ProductName	nvarchar(30)	NOT NULL,
    Price		int		NOT NULL,
    State		nvarchar(4)	NOT NULL,
    Detail		text,
    Stock		int		DEFAULT 0,
    TaxRate		int		NOT NULL,
    CategoryNo	int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey),
    CONSTRAINT ch_State CHECK (State IN (‘신상’,’중고’,’전시’))
);
----

`TaxRate` 컬럼의 값을 10이상 20이하로 제한하는 `CHECK` 제약 조건을 아래와 같이 작성할 수 있습니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12)		NOT NULL,
    ProductName	nvarchar(30)	NOT NULL,
    Price		int		NOT NULL,
    State		nvarchar(4)	NOT NULL,
    Detail		text,
    Stock		int		DEFAULT 0,
    TaxRate		int	NOT NULL 	CHECK(TaxRate >= 10 AND TaxRate < 20),
    CategoryNo	int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey),
    CONSTRAINT ch_State CHECK (State IN (‘신상’,’중고’,’전시’))
);
----

`Category` 테이블의 `CategoryNo`` 컬럼을 참조하는 참조 무결성 제약조건을 아래와 같이 작성할 수 있습니다.

[source, sql]
----
CREATE TABLE Product (
    ProductNo 	int, 
    SerialKey	char(12)		NOT NULL,
    ProductName	nvarchar(30)	NOT NULL,
    Price		int		NOT NULL,
    State		nvarchar(4)	NOT NULL,
    Detail		text,
    Stock		int		DEFAULT 0,
    TaxRate		int		NOT NULL CHECK(TaxRate >= 10 AND TaxRate < 20),
    CategoryNo	int,
    
    CONSTRAINT pk_Product PRIMARY KEY(ProductNo),
    CONSTRAINT uq_ProductSerial UNIQUE(SerialKey),
    CONSTRAINT ch_State CHECK (State IN ('신상','중고','전시')),
    CONSTRAINT fk_Product_Category FOREIGN KEY(CategoryNo) REFERENCES Category(CategoryNo)
);
----

== 테이블 수정 예제 (MySQL)
Product 테이블의 ProductName 필드의 데이터 타입을 nvarchar(30)에서 nvarchar(40)으로 변경합니다.
[source, sql]
----
ALTER TABLE Product MODIFY COLUMN ProductName nvarchar(40);
----

Product 테이블에 ModelNo 필드를 추가합니다.
[source, sql]
----
ALTER TABLE Product ADD Column ModelNo nvarchar(20);
----

Product 테이블에 추가한 ModelNo 필드의 순서를 SerialKey 다음으로 변경합니다.

[source, sql]
----
ALTER TABLE Product MODIFY ModelNo varchar(20) AFTER SerialKey;
----

Product 테이블의 TaxRate 컬럼의 기본 값을 10으로 변경합니다.

[source, sql]
----
ALTER TABLE Product ALTER COLUMN TaxRate SET DEFAULT 10;
----

Product 테이블의 Detail 필드를 NOT NULL로 설정합니다.

[source, sql]
----
ALTER TABLE Product MODIFY COLUMN Detail text NOT NULL;
----

Product 테이블의 ModelNo 필드의 이름을 ModelNumber로 변경합니다.

[source, sql]
----
ALTER TABLE Product CHANGE ModelNo ModelNumber nvarchar(20);
----

Product 테이블의 이름을 Products로 변경합니다.

[source, sql]
----
ALTER TABLE Product RENAME Products;
----

Products 테이블의 이름을 Product로 변경합니다.

[source, sql]
----
RENAME TABLE Products TO Product;
----

=== 테이블 삭제 예제 (MySQL)

Product 테이블의 SerialKey 컬럼에 설정된 UNIQUE 제약 조건을 삭제합니다.

[source, sql]
----
ALTER TABLE Product DROP CONSTRAINT uq_ProductSerial;
----

Product 테이블의 ModelNumber 컬럼을 삭제합니다.
[source, sql]
----
ALTER TABLE Product DROP COLUMN ModelNumber;
----

Product 테이블을 삭제합니다.
[source, sql]
----
DROP TABLE Product;
----

link:./09_lab6-1.adoc[다음: Lab 6-1 테이블 생성(MySQL)]
