= 상호 연관 서브쿼리(Correlated Subquery)

* 서브 쿼리가 주 쿼리의 필드 값과 연관되어 사용하는 질의
* 일반적인 서브 쿼리는 서브 쿼리의 결과를 주 쿼리가 이용함
* 주 쿼리의 한 Row에 대해 서브 쿼리가 한번씩 실행됨
** 테이블에서 Row를 먼저 읽고 각 Row의 서브 쿼리에서 사용함
* 결과 집합이 대량인 경우 효율이 떨어짐
* 포함된 서브 쿼리와 인라인 뷰, 포함된 서브쿼리에서 주 쿼리와 값을 비교하는 모든 경우

---

일반적인 서브쿼리는 서브 쿼리의 결과를 주 쿼리가 이용합니다. 상호 연관 서브쿼리는 서브쿼리가 주 쿼리의 값을 이용하고, 구해진 서브쿼리의 결과를 주 쿼리가 이용하는 방식으로 동작합니다.

상호 연관 서브쿼리는 하나의 행을 비교할 때 마다 결과가 주 쿼리로 반환됩니다. 따라서, 각각의 행을 처리할 때 마다 그 결과를 다시 주 쿼리로 전송하는 방식으로 처리하기 때문에 성능이 저하됩니다.

> 같은 등급의 평균 나이보다 많는 나이의 승객을 이름과 나이를 구하시오

위 질의의 결과를 구하기 위해서는 각 등급별 승객의 나이 평균이 필요합니다. 각 등급 별 승객의 나이 평균을 구해낸 후, 각 등급별 나이 평균보다 나이가 많은 승객의 이름과 나이를 구해야 합니다.

각 등급별 나이 평균은 아래와 같이 구할 수 있습니다.

[source, sql]
----
SELECT avg(age), grade 
FROM Passenger
GROUP BY grade;
----

각 나이 평균을 구했으면, 구한 등급의 나이 평균만큼, 즉 등급의 개수만큼 반복을 수행하여 질의를 수행해야 합니다. 등급이 10개이면, 10번 반복하여 쿼리를 수행해야 결과를 얻을 수 있습니다. 이런 경우, 상호 연관 서브 쿼리를 아래와 같이 실행할 수 있습니다.
[source, sql]
----
SELECT passengerName, Age
FROM passenger AS p1
WHERE age > (SELECT avg(age)
	FROM passenger AS p2
    WHERE p1.grade = p2.grade);
----

위 상호 연관 서브 쿼리는 주 쿼리의 `Grade` 컬럼과 서브 쿼리의 `Grade` 컬럼이 상호 연관됩니다. 따라서 주 쿼리에서 SELECT하는 테이블의 컬럼이 10개이면, 각 등급별 나이의 평균을 구하는 동작을 수행하는 서브 쿼리도 10번 수행됩니다. 따라서, 결과 집합이 대량인 경우 효율이 떨어집니다.

link:./27_aggregate_calculation.adoc[다음: 집단 연산]