= 검토

* SQL 개요
* DDL: Data Definition Language
* DML: Data Manipulation Language, SQL 기본 질의 구조
* 집합 연산
* 서브 쿼리
* 집단 연산
* 정렬
* 삽입
* 갱신
* 삭제

---

== Quiz

1.	아래와 같은 릴레이션이 있습니다.
+
_학생(학번: 정수, 학생이름: 문자열, 전공: 문자열, 학년: 정수) +
과목(과목이름: 문자열, 수업시간: 시간, 강의실: 문자열, 교수번호: 정수) +
수강(학번: 정수, 과목이름: 문자열) +
교수(교수번호: 정수, 교수이름: 문자열, 학과번호: 정수)_
+
이 릴레이션의 의미는 단순합니다. 예를 들어 수강 릴레이션에는 한 학생이 과목을 수강할 때 마다 학생-과목 쌍에 해당하는 레코드가 하나씩 생깁니다.
다음 질의를 SQL로 작성하십시오. 어느 결과에서는 중복된 값을 출력해서는 안됩니다.
+
A.	이순신이 가르치는 과목을 수강하고 있는 모든 3학년들의 이름을 구하시오.
B.	역사를 전공하거나 이순신이 가르치는 과목을 수강하고 있는 가장 나이 많은 학생의 나이를 구하시오.
C.	강의실 번호가 1103이거나 다섯 명 이상이 수강하고 있는 모든 과목들의 이름을 구하시오.
D.	같은 시간에 진행되는 두 과목을 수강하고 있는 모든 학생들의 이름을 구하시오.
E.	강의에 이용되는 모든 강의실에서 가르치고 있는 교수들의 이름을 구하시오.
F.	자신이 가르치는 과목을 수강하는 학생의 수가 5가 안되는 교수들의 이름을 구하시오.
G.	등급별로 학생의 평균 나이와 그 등급을 출력하시오.
H.	3학년을 제외한 모든 등급에 대해서 학생들의 평균 나이와 그 등급을 출력하시오.
I.	과목을 최대로 수강하고 있는 학생들의 이름을 구하시오.
J.	어떠한 과목도 수강하고 있지 않은 학생들의 이름을 구하시오.
K.	학생의 나이별로 가장 많은 등급을 구하시오.
2.	아래와 같은 릴레이션이 있습니다.
+
_공급자(공급자번호: 정수, 공급자이름: 문자열, 주소: 문자열)  +
부품(부품번호: 정수, 부품이름: 문자열, 색상: 문자열) +
카탈로그(공급자번호: 정수, 부품번호: 정수, 단가: 실수)_
+
카탈로그 릴레이션은 공급자별 부품 단가를 가지고 있습니다. 다음 질의들을 SQL로 표현하세요.
+
A.	공급자가 있는 부품들의 이름을 구하시오.
B.	모든 부품을 공급하는 공급자들의 이름을 구하시오.
C.	모든 적색 부품을 공급하는 공급자들의 이름을 구하시오.
D.	홍길동이라는 공급자만 공급하는 부품의 이름을 구하시오.
E.	일부 부품에 대해서 평균 부품 단가보다 많이 받는 공급자들의 이름을 구하시오.
F.	각 부품별로 그 부품에 대해서 가장 비싼 단가를 책정하고 있는 공급자들의 이름을 구하시오.
G.	적색 부품들만 공급하는 공급자들의 이름을 구하시오.
H.	적색 부품 하나와 녹색 부품 하나를 공급하는 공급자들의 이름을 구하시오.
I.	적색 부품 하나 또는 녹색 부품 하나를 공급하는 공급자들의 이름을 구하시오.

3.	관계 스키마는 다음과 같습니다. 직원 한 명이 여러 부서에서 일할 수 있습니다. 근무 릴레이션에서 시간백분을 만드는 필드는 해당 직원이 해당 부서에서 근무하는 시간 백분율을 나타냅니다.
+
_직원(직원번호: 정수, 직원이름: 문자열, 나이: 정수, 급여: 실수)  +
근무(직원번호: 정수, 부서번호: 정수, 시간백분율: 정수)  +
부서(부서번호: 정수, 예산: 실수, 부서장번호: 정수)_
+
다음 질의를 SQL로 작성하세요.
+
A.	하드웨어 부서와 소프트웨어 부서에서 모두 근무하는 직원들의 이름과 나이를 출력하세요.
B.	20명 이상의 풀타임 직원이 있는 각 부서(즉 파트 타임 근무 직원과 풀타임 근무 직원들을 합하여 적어도 그만큼의 풀타임 직원에 해당하는 부서)별로, 부서번호와 그 부서에 근무하는 직원들의 수를 출력하세요.
C.	자신의 근무하는 어느 부서의 예산보다 급여를 많이 받는 직원들의 이름을 출력하세요.
D.	예산에 1억원이 넘는 부서를 관리하는 부서장의 이름을 구하세요
E.	한 부서장이 여러 부서를 관리한다면 그는 결국 부서의 예산 총액을 관리하는 것입니다. 5000만원 이상을 관장하는 부서장들의 번호를 구하세요.
F.	가장 많은 예산을 관리하는 부서장의 번호를 구하세요.
G.	모든 직원들이 5000만원 이상을 벌 수 있도록 직원 릴레이션에 대한 테이블 제약조건을 정의하세요.
H.	부서장이라면 나이가 30살이 넘어야 한다는 제약조건을 정의하세요.
I.	자신이 근무하는 부서들중에서 어느 한 곳에서라도 부서장보다 급여가 더 많은 직원들에 대한 모든 정보를 삭제하는 SQL문을 작성하세요. 이렇게 한 후에도 관련 무결성 제약조건은 만족되어야 합니다.
