= 버퍼 관리 기법 비교

* 운영체제의 가상 메모리와 DBMS의 버퍼 관리자는 매우 비슷함
* DBMS는 페이지 참조 패턴을 일반적인 운영체제 환경보다 더 정확히 예측해야 함
** DBMS는 참조 패턴을 예측할 수 있으므로 페이지 우선 적재 전략을 사용할 수 있음
* DBMS는 페이지를 디스크에 강제 출력할 수 있어야 함
** 손상 복구를 위한 WAL 규약을 실현할 수 있음

---

OS의 가상 메모리와 DBMS의 버퍼 관리기는 매우 비슷합니다. 양쪽 다 기억장치보다 큰 데이터에 접근할 수 있는 방법을 제공하며, 두 구성요소 모두 필요한 페이지를 디스크에서 주 기억장치로 가져오고, 주기억장치에서 사용하지 않는 페이지는 교체합니다.

하지만 일반적으로 DBMS는 운영체제의 가상 메모리를 사용하지 않습니다. DBMS는 페이지를 접근하는 순서, 즉 페이지 참조 패턴(Page Reference Pattern)을 일반적인 운영체제 환경보도 더 정확히 예측해야 합니다. 또한 DBMS는 페이지를 디스크에 기록하는 시점에 운영체제보다 더 많은 제어를 해야 합니다.

DBMS는 페이지 참조 패턴이 일반적으로 잘 알려져 있는 고수준 연산(스캔이나 관계 대수 연산자에 의한 특정한 구현법)에 의해서 페이지 참조가 이루어지기 때문에 페이지 참조 패턴을 예측하기 쉽습니다. 참조 패턴을 쉽게 예측할 수 있으므로 교체 페이지를 더 잘 선정할 수 있으며, 이에 따라 DBMS 환경에서는 최적화된 페이지 교체 전략을 사용할 수 있습니다.

DBMS는 페이지 참조 패턴을 사용할 수 있기 때문에 페이지 선반입(Page Prefetching)을 사용할 수 있습니다. 버퍼 관리자는 다음에 일어날 페이지 요청들을 예측할 수 있기 때문에 실제 요청이 일어나기 전에 미리 주 기억장치로 페이지들을 로드할 수 있습니다. 이 전략은 두 가지 이점이 있습니다.

1.	페이지가 실제로 요청되는 시점에 페이지가 이미 버퍼 풀 내에 로드되어 있음
2.	연속된 블록에 들어있는 페이지들을 한꺼번에 판독하는 것이 각각의 요청에 판독해 오는 것 보다 효율적이다.

== WAL(Write Ahead Log)

DBMS는 페이지를 디스크에 강제적으로 출력할 수 있어야 합니다. 필요한 경우 언제라도 주 기억장치에 있는 페이지의 내용과 디스크에 있는 해당 페이지의 내용을 같도록 할 수 있어야 한다는 것입니다. DBMS는 버퍼 풀의 특정 페이지에 다른 페이지를 기록하기 전에 먼저 디스크에 기록할 수 있어야 손상 복구를 위한 WAL 규약을 실현할 수 있습니다. 운영체제의 가상 메모리 구현 방식에서는 페이지를 디스크를 기록하는 시점에 이러한 제어를 보장받지 못합니다.

link:./16_record.adoc[다음: 레코드 형식]