= 파일 조직법 비교 기준 연산

* 스캔(Scan) +
파일에 있는 모든 레코드를 가져옴. 파일에 있는 페이지들은 디스크로 부터 버퍼 풀로 반입 되어야함
* 동등 셀렉션(Equality Selection) +
질의에서 요구하는 검색어와 같은 문자열임을 만족하는 모든 레코드를 가져옴
* 범위 셀렉션(Range Selection) +
1에서 10까지, 홍길동에서 이순신까지 등 범위에 해당하는 모든 레코드를 가져옴
* 삽입(Insertion) +
주어진 레코드를 파일에 삽입
* 삭제(Deletion) +
RID로 명세된 레코드 삭제. 

---

세 가지의 기본적인 파일 조직, 힙, 정렬된 파일, 해시 파일에 대해 대표적인 연산들의 비용을 비교합니다. 비교에 사용할 대표적인 데이터베이스 연산들은 다음과 같습니다.

* 스캔(Scan) +
파일에 있는 모든 레코드를 가져옵니다. 파일에 있는 페이지들은 디스크로부터 버퍼 풀로 로드되어야 합니다. 
* 동등 셀렉션(Equality Selection) +
질의에서 요구하는 검색어와 같은 문자열임을 만족하는 모든 레코드를 버퍼 풀로 로드합니다. “이름이 이순신인 모든 레코드”와 같은 질의가 이에 해당합니다. 조건을 만족하는 레코드가 포함된 모든 페이지를 로드한 후 페이지 내에서 원하는 레코드로 이동합니다.
* 범위 셀렉션(Range Selection) +
질의에서 요구하는 범위에 해당하는 모든 레코드를 버퍼 풀로 로드합니다. “고객 번호가 10000에서 100000 사이의 모든 고객”이나 “이름이 이순신에서 홍길동 사이의 모든 고객”등의 질의가 여기에 해당합니다.
* 삽입(Insertion) +
주어진 레코드를 파일에 삽입합니다. 먼저 새로운 레코드가 삽입될 페이지를 알아내고 디스크로부터 해당 페이지를 로드한 후, 새로운 레코드가 포함하도록 수정하여 페이지를 저장합니다.
* 삭제(Deletion) +
RID로 명세된 레코드를 삭제합니다. 해당 레코드가 있는 페이지를 알아내고 메모리로 로드한 후, 수정하여 저장합니다.

link:./05_heap_file.adoc[다음: 힙(Heap) 파일]