= 해시 파일

* 특정 필드를 기준으로 정렬된 파일
* 스캔 +
힙 파일과 다르지 않음. B(D+RC)
* 동등 셀렉션 +
정럴 기준 필드로 검색할 경우 이진 탐색으로 Dlog2B + Clog2R. 정렬 필드가 아닌 경우 스캔과 동일
* 범위 셀렉션 +
정렬 기준 필드로 검색할 경우 첫 레코드를 찾는데 동등 셀렉션과 동일. 이후 범위내 스캔
* 삽입 +
정렬 순서를 유지하기 위해 레코드가 삽입될 위치를 검색 후 레코드 추가. 후속 페이지를 모두 로드하여 다시 저장. 탐색 비용 + B(D + RC)

---

해시 파일은 파일의 특정 필드로 된 탐색키를 가지고 해시 함수를 사용해 키를 찾는 파일입니다. 해시 파일을 구성하는 페이지들은 버킷(Bucket) 단위로 묶이고 레코드가 속하게 될 버킷은 해시 함수(Hash Function)를 적용해서 결정할 수 있습니다.

* 스캔 +
해시 파일에서는 삽입을 위한 여분의 공간을 남겨 파일이 확장될 때 오버플로우의 수를 줄이기 위해 페이지를 보통 80% 정도 차도록 유지합니다. 레코드들을 초기에 해시 파일 구조로 조직하고 나면 기존 페이지가 80%가 찼을 때 해당 버킷에 새로운 페이지 하나를 추가하게 됩니다. 기존 페이지 수와 모든 데이터 페이지의 스캔 비용은 힙 파일의 1.25배가 되어 1.25B(D + RC)가 됩니다.
* 동등 셀렉션 +
셀렉션 조건이 해시 파일의 탐색 키에 대한 것이라면 다른 파일 조직과 비교하여 효율적으로 수행됩니다. 검색 대상 레코드들이 있는 페이지를 알아내는 비용이 그 버킷이 하나의 페이지만으로 구성되어 있다고 가정할 때 H가 되고, 그 페이지를 검색하는 비용은 D가 됩니다. 찾은 페이지에서 레코드를 찾기 위해 평균 50%의 페이지를 스캔해야 한다고 하면, 비용은 H + D + RC가 됩니다.
검색 조건이 해시 파일의 탐색 키가 아니라면 스캔과 같습니다.
* 범위 셀렉션 +
해시 구조는 범위 연산에서 어떠한 효율도 발하지 못합니다. 스캔과 같습니다.
* 삽입 +
적절한 페이지를 찾아서 다시 기록해야 합니다. 비용은 탐색비용 + C + D입니다.
* 삭제 +
레코드를 찾아서 해당 페이지에서 제거한 후, 수정한 페이지를 다시 기록해야 합니다. 탐색 비용 + C + D가 됩니다.

link:./08_file_choice.adoc[다음: 퍄일 조직 선택]