= 약 개체 집합

* 키가 존재하지 않는 개체집합
** 자신의 일부 속성과 다른 개체의 Primary Key를 조합하여야 유일하게 식별 됨
** 다른 개체를 식별 소유자(Identity Owner)라고 함
* 다음 조건들을 만족할 때 성립
** 식별 소유자와 약 개제 집합 사이에는 One-to-Many 관계 집합이 성립
** 약 개체 집합은 식별 관계집합에 전체적으로 참여하여야 함
** 소유자 개체에 대해 약 개제 하나를 유일하게 식별해 주는 속성 집합을 약 개체집합에 대한 구별자(discriminator) 또는 부분 키(Partial Key)라고 함

---

개체 집합에 키가 항상 존재해야 하는 것은 아닙니다. 예를 들어 직원들이 피 부양자를 위해 보험증권을 구매하는 경우를 생각해봅시다. 데이터베이스는 보험증권에 관한 정보를 기록합니다. 이런 경우 각 보험 증권이 어떤 피부양자를 대상으로 하는지에 대한 정보가 중요합니다. 직원이 회사를 사직할 경우 사직한 직원의 보험증권은 시한이 종료되고 그와 관련된 모든 증권 정보와 피 부양자 정보를 데이터베이스에서 삭제해야 하는 경우를 생각해봅시다.

이런 상황에서는 피부양자를 이름만으로 식별하는 것이 일반적입니다. 한 직원의 피 부양자는 이름이 모두 다른 경우가 일반적이기 때문입니다. 이런 경우 피부양자 개체 집합의 속성은 피부양자 이름과 나이 정도가 될 수 있습니다. 피부양자이름 속성은 피 부양자를 유일하게 식별하지 않습니다. 직원에 대한 키는 사번입니다. 회사에는 이순신이라는 이름을 가진 직원이 두 명 이상 있을 수 있고, 이들은 이면이라는 이름을 가진 자녀를 한 명씩 둘 수 있습니다.

이때의 피부양자는 **약 개체집합(Weakly Entity Set)**입니다. 약 개체는 자기 자신의 일부 속성과 다른 개체의 기본 키를 조합하여야만 유일하게 식별되는데, 이때 이 다른 개체를 **식별 소유자(Identifying Owner)**라고 합니다.

약 개체 집합은 다음과 같은 요건들이 만족 되어야 합니다.

* 소유자 개체집합과 약 개체 집합 사이에는 일대다 관계 집합이 있어야 합니다. 하나의 소유자 개체는 여러 약 개체와 연관되지만, 각각의 약 개체는 하나의 소유자만 갖습니다. 이러한 관계집합을 약 개체집합에 대한 **식별 관계집합(Identifying Relationship Set)**이라고 합니다.
* 약 개체집합은 식별 관계 집합에 전체적으로 참여해야 합니다.
어떤 피부양자 개체를 유일하게 식별하려면 소유자 직원 개체의 키와 해당 피부양자 개체의 피부양자 이름을 조합해보야야 합니다. 주어진 소유자 개체에 대하여 약 개체 하나를 유일하게 식별해주는 집합을 그 약 개체집합에 대한 **부분 키(Partial Key)**라고 합니다. 여기에서 피부양자이름은 피부양자에 대한 부분 키입니다.
 
피부양자 개제집합이 약 개체 집합이며, 보험 관계집합이 식별 관계집합입니다. 피부양자이름이 피부양자 약 개체 집합의 부분 키가 됩니다.

== 관계 모델로 변환

약 개체집합은 언제나 일대다 이진 관계에 참여하며, 키 제약조건과 전체 참여 제약조건을 수반합니다. 약 개체집합에서는 소유가 개체가 삭제되면 이와 관련된 모든 약 개체들도 삭제됩니다.

아래와 같은 보험 릴레이션으로 정의할 수 있습니다.

[source, sql]
----
CREATE TABLE 보험 (
	피부양자이름 	varchar(20),
	나이		int,
	가액		decimal,
	사번		int	NOT NULL,

	CONSTRAINT pk_보험 PRIMARY KEY(사번, 피부양자이름),
	CONSTRAINT fk_보험_직원 FOREIGN KEY(사번) REFERENCES 직원(사번) ON DELETE CASCADE
)
----

피 부양자는 약 개체이므로 기본 키는 <피부양자이름, 사번>이 됩니다. NOT NULL 제약조건에 의하여 모든 피부양자들은 하나의 직원 개체와 연관되게 되어 피부양자에 대한 전체 참여 제약조건을 만족하게 됩니다. CASCADE 조건을 붙여 직원 레코드가 삭제되면 피부양자 레코드 역시 삭제됩니다.

link:./12_specialization.adoc[다음: 전문화와 일반화]
