= 전문화와 일반화

* 하나의 개체 집합은 집합내의 다른 개체들과 구분되는 개체들의 하위집합을 가질 수 있음
** 개체 집합 내의 어떤 부분집합은 개체 집합내의 모든 개체들과 공유되지 않는 속성들을 가질 수 있음
** 개체 집합에 속한 세부 개체들을 세부 부류(subclass)로 분류
* 포함 제약 조건(Inclusion Constraint)
** 중첩 제약 조건(Overlap Constraints) +
두 서브 클래스에 같은 개체가 포함될 수 있는가를 결정
** 포괄 제약 조건(Covering Constraints) +
서브 클래스의 모든 개체를 모으면 수퍼 클래스의 모든 개체가 되어야 하는가를 결정

---

한 개체집합에 속한 개체들을 세부 부류(서브 클래스 - Subclass)로 분류하는 것이 자연스러울 때가 있습니다. 임금 계산 방식에 따라 시간제_직원 개체집합 또는 계약제_직원 개체집합을 생각할 수 있습니다. 이때 시간제_직원에 대해서는 근무시간과 시간당 임금 속성을, 계약제_직원에 대해서는 계약번호 속성을 할당할 수 있습니다.

이 두 집합에 속한 개체들은 모두 일종의 직원 개체이고, 따라서 직원 개체 집합에서 정한 사번, 이름 등의 모든 속성을 가져야 합니다. 이에 따라 시간제_직원 개체에 다한 속성들은 직원에 대한 속성에 시간제_직원의 속성을 더한 것이 되는데, 이때 시간제_직원 개체집합은 직원 개체집합의 속성들을 **상속(Inheritance)** 받는다고 합니다. 이때 Java등의 프로그래밍 언어들의 클래스 계층구조와는 다르게 **포함 제약조건(Inclusion Constraints)**이 따르게 됩니다. 즉, 모든 직원 개체들에 대한 질의는 모든 시간제_직원 개체와 계약제_직원 개체들에 대한 질의도 됩니다. 
 
직원 개체집합을 다른 기준에 따라 나눌 수도 있습니다. 예를 들어 직원 중 일부를 임원으로 나눌 수 있는데, 직원의 자식 노드로 또 다른 ISA 노드를 달고 그 임원을 자식으로 설정하면 됩니다. 이런 방법으로 다중 ISA 계층 구조를 만들 수 있습니다.

클래스 계층을 보는 관점은 다음과 같이 두 가지가 있습니다.

* 직원이 여러 클래스로 **전문화(Specialization)**된 것. 전문화란 어떤 개체집합(슈퍼클래스, Superclass)중에서 다른 것 들로부터 구별되는 어떤 특성을 공유하는 일부 집합을 식별해 내는 과정입니다. 일반적으로 슈퍼클래스가 먼저 정해지고 나서 서브클래스들이 다음으로 정해지며 서브클래스 고유의 속성과 관계집합들이 추가됩니다.
* 시간제_직원과 계약제_직원이 모여서 직원으로 **일반화(Generalization)**된 것. 여러 개체 집합에서 공통적인 특성들을 추출해서 그러한 공통 특성을 가지는 개체들을 모든 큰 개체집합을 만들어 내는 것입니다. 일반적으로 서브클래스들이 먼저 정해지고 나서 슈퍼클래스가 정해지며 그 슈퍼클래스에 대한 관계 집합이 추가됩니다.
* 중첩 제약조건(Overlap Constraints)와 포괄 제약조건(Covering Constraints)
ISA 계층에 명세해 줄 수 있는 제약조건으로는 중첩 제약조건과 포괄 제약조건이 있습니다. 중첩 제약조건은 두 서브 클래스에 같은 개체가 포함될 수 있는지를 결정합니다. 홍길동 직원이 계약제 직원이면서 시간제 직원일 수 있는지에 대한 제약조건을 말합니다.

포괄 제약조건은 서브클래스의 모든 개체를 모으면 슈퍼클래스의 모든 개체가 되는지를 결정합니다. 모든 직원 개체들은 그 서브클래스들 중 하나에 속해야 하는지에 대한 제약 조건입니다.

== 서브클래스를 정하는 이유

전문화나 일반화를 통해서 서브클래스들을 정하는 기본적인 이유는 다음과 같습니다.

1.	서브클래스의 개체들에 대해서만 어떤 설명용 속성들을 추가해야 할 필요가 있을 때
2.	어떤 관계에 참여하는 개체들만 분류해야 할 경우가 있을 때

== 관계 모델로 변환
ISA 계층을 처리하는 방법에는 두 가지가 있습니다.

1. 개체집합인 직원, 시간제_직원, 계약제_직원을 각기 다른 릴레이션으로 매핑하는 방법. 시간제_직원 개체 집합을 릴레이션으로 변환할 경우, 릴레이션에는 시간당임금과 근무시간 속성이 지정됩니다. 그리고 슈퍼클래스의 키 속성인 사번 역시 지정되는데, 이 속성은 슈퍼클래스의 기본 키일 뿐만 아니라 슈퍼클래스인 직원 릴레이션을 참조하는 외래 키로 지정됩니다. 직원 투플이 삭제되면 시간제_직원 투플 역시 삭제되어야 합니다.
+
[source, sql]
----
CREATE TABLE 시간제_직원 (
		사번		int,
		시간당임금	decimal,
		근무시간		int, 

		CONSTRAINT pk_시간제직원 PRIMARY KEY(사번),
		CONSTRAINT fk_시간제직원 FOREIGN KEY(사번) REFERENCES 직원(사번)
)
----
+
2. 시간제_직원과 계약제_직원에 해당하는 두 개의 릴레이션만 만드는 방법. 시간제_직원 릴레이션에는 시간제 직원에 필요한 모든 속성(직원 개체에 필요한 속성까지)이 모두 지정됩니다.

첫 번째 방식이 일반적으로 사용되는 방법으로서, 어느 경우에나 적용 가능합니다. 서브클래스에 한정된 속성들을 따지지 않고 모든 직원들을 검사하는 질의는 직원 릴레이션으로 수행하며, 시간제 직원과 관련된 질의는 직원과 조인해서 수행합니다. 

만일 직원중에 시간제 직원도 아니고 계약제 직원도 아닌 직원이 있다면 두 번째 방식은 사용할 수 없습니다. 또 한 직원이 계약제 직원이면서 시간제 직원인 경우가 있다면 중복 저장되는 속성이 생길 수 있습니다. 

link:./13_conceptural_design.adoc[다음: 개념적 설계 고려사항]
