= 접근 제어

* 대부분의 데이터베이스 사용자들은 자신의 업무를 수행하는데 필요한 데이터에만 접근
* DBMS는 크게 두 가지의 접근 제어 방식을 사용
** 재량 접근 제어(Discretionary Access Control)
*** 특권(Privileges)이라는 접근 권한의 개념에 기반함
*** 사용자에게 특권을 부여하는 메커니즘 사용
** 필수 접근 제어(Mandatory Access Control)
*** 사용자 개개인에 따라 변경할 수 없는 시스템 전반에 걸친 정책 사용
*** 모든 데이터베이스 개체에 비밀 등급을 매기고 사용자 마다 허가 등급을 부여
* SQL 1999 표준은 필수 접근 제어를 허용하지 않음

---

한 기업의 데이터베이스에는 많은 양의 정보와 여러 명의 사용자들이 존재하며, 일반적으로 사용자 집단이 여러 가지로 구분됩니다. 대부분의 사용자들은 자신의 업무를 수행하기 위해 데이터베이스의 일부만 사용합니다. 사용자들에게 모든 데이터에 대한 무제한적인 접근 권한을 부여하는 것은 바람직하지 않으며, 따라서 DBMS는 데이터에 대한 접근을 제어하는 메커니즘을 제공해 주어야 합니다.

DBMS는 크게 두 가지의 접근 제어 방식을 제공합니다. 재량 접근 제어(Discretionary Access Control)은 특권(Privileges)이라는 접근 권한의 개념에 기반하며, 사용자들에게 이러한 특권을 부여하는 매커니즘을 사용합니다. 특권이란 한 사용자에게 어느 데이터 객체에 대한 어떤 특정 형태(판독/수정 등)의 접근권을 주는 것입니다. 테이블이나 부와 같은 데이터베이스 객체를 생성한 사용자는 자동적으로 그 객체에 대한 모든 적용 가능한 권한을 가집니다. 그 이후는 DBMS가 이들 특권들이 어떤 사용자들에게 허가되었고 또 취소되었는가를 계속 추적하며, 항상 필요한 특권을 가진 사용자들만 객체에 접근할 수 있도록 합니다. SQL-92는 GRANT 명령과 REVOKE 명령을 통해 재량 접근 제어를 지원합니다. 

재량 접근 제어 메커니즘은 일반적으로 효과가 있으나 몇 가지 약점을 가지고 있습니다. 특히 권한없는 사용자가 권한있는 사용자로 하여금 민감한 데이터를 유출시키도록 속일 수 있습니다. 필수 접근 제어(Mandatory Access Control)는 사용자 개개인에 따라 변경할 수 없는 시스템 전반에 걸친 정책에 기반합니다. 이 방식에서는 모든 데이터베이스 객체를 판독하거나 기록하는 것에 대해 몇 가지 규칙들을 만들어 놓습니다. DBMS는 개체의 비밀 등급과 사용자의 허가 등급을 몇 가지 규칙에 따라 비교하여 그 사용자가 그 객체를 판독하거나 기록할 수 있는지를 결정합니다. 

SQL 1999 표준은 필수 접근 제어를 전혀 제공하지 않습니다. 일반적으로 DBMS는 보안을 위해 재량 접근 제어를 사용합니다.

link:./06_dac.adoc[다음: 재량 접근 제어]