= 필수 특권 제어

* 재량 접근 제어는 일반적으로 효과가 있으나 몇 가지 약점을 가지고 있음
** 권한 없는 불순한 사용자가 권한 있는 사용자로 하여금 민감한 데이터를 유출할 수 있도록 속일 수 있음
** 트로이 목마 방식에 특히 취약함
* 필수 접근 제어는 필수 데이터베이스 개체에 각각의 보안 등급을 지정함
** 테이블, 뷰, 투플, 필드 등 모든 개체는 개별 보안 등급을 가짐
* 모든 주체는 보안 등급에 해당하는 허가 등급이 지정됨
** 사용자, 프로그램 등의 주체는 허가 등급보다 높은 보안 등급을 가진 개체에는 접근 불가
* SQL 1999 표준은 필수 접근 제어를 지정하지 않음

---

재량 제어 매커니즘은 일반적으로 효과적이지만 몇 가지 약점이 있습니다. 특히 권한 없는 악의적인 의도를 가진 사용자가 권한 있는 사용자를 이용해 데이터를 유출시키는 함정에 빠트릴 수도 있다는 점에서 트로이의 목마(Trojan horse) 방식에 취약한 점이 있습니다.

예를 들어 홍길동 학생이 이순신 교수의 성적 테이블을 보고싶다고 합시다. 홍길동은 다음과 같은 작업을 수행합니다.

* 새로운 테이블 MyData를 만들어 이 테이블의 INSERT 특권을 이순신 교수에게 부여합니다. 이순신 교수는 데이터베이스에 대한 깊은 지식이 없습니다.
* 홍길동이 자주 사용하는 어떤 DBMS 응용 프로그램의 소스를 고쳐서 다음과 같은 두 가지 작업을 하도록 만든다. 1, 성적 테이블을 읽는다. 2. 결과를 MyData에 저장한다.

이렇게 되면 DBMS가 재량 접근 제어를 빈틈없이 적용한다 해도 데이터가 홍길동에게 유출됩니다. 홍길동이 프로그램 코드를 수정할 수 있는지의 여부는 DBMS의 접근 제어 메커니즘을 벗어납니다. 

필수 제어 메커니즘은이런 재량 접근 제어의 단점을 보완합니다. 접근 제어에서는 Bell-LaPudla 모델이 널리 사용되는데, 개체(테이블, 뷰, 투플, 필드 등), 주체(사용자, 프로그램 등), 보안 등급(Secure Class), 허가 등급(Clearance)로 표현됩니다. 모든 데이터베이스 개체에는 각각 보안 등급이 적용되며 모든 주체들에는 보안 등급에 해당하는 허가 등급이 지정됩니다. 

한 시스템 내에 있는 보안 등급들은 최고 보안 등급과 최저 보안 등급이 하나씩 있고, 그 사이는 부분 순서에 따라 체계화됩니다. Bell-LaPudla 모들은 데이터베이스 개체에 대한 모든 기록과 판독에 대해 다음과 같은 두 가지 제약을 가합니다. 개체나 주체의 A 등급을 class(A)라고 할 때, 만약 아래와 같은 등급들이 존재할 경우,

_TS(Top Secret) > S > C > U_

아래와 같은 제약을 가집니다.

1.	단순 보안 성질 +
주체 S가 개체 O를 판독하는 것은 class(S) >= class(O)인 경우에만 가능합니다. 예를 들어 TS등급의 사용자는 C등급의 테이블을 볼 수 있지만 C 등급의 사용자는 TS등급의 사용자를 볼 수 없습니다.
2.	*- 성질 +
주체 S가 객체 O를 기록하는 것은 class(S) <= class(O)인 경우에만 가능합니다. S 등급의 사용자는 S등급이나 TS등급의 사용자만 가능합니다.

재량 접근 제어도 명세를 통해 추가적인 제약을 표시할 수 있습니다. 그러므로 데이터베이스 개체를 기록하거나 판독하려는 사용자는 필요한 특권을 가질 수 있어야 할 뿐만 아니라 사용자와 객체 사이의 등급 관계가 앞의 제약을 만족해야 합니다.

SQL 1999 표준은 필수 특권 제어를 SQL의 기능에 포함시킬 것을 명세하지 않습니다. 따라서, 대부분의 관계 데이터베이스는 필수 특권 제어를 지원하지 않지만, MS-SQL Server와 같은 경우 필수 특권 제어의 개념을 사용해 다중 수준 보안(MLS – Multi-Level Secure)를 구현하고 있습니다.

link:./09_lab07_1.adoc[다음: 연습 7-1 사용자 생성 및 권한 제어]