= Lab 2-2c: SQL을 사용한 무결성 제약조건 설정(Oracle)

== 연습 1 SQL을 사용하여 개체 무결성을 위한 기본 키 제약조건 설정

이 연습에서는 SQL을 사용하여 연습 2-1에서 생성한 릴레이션에 무결성 제약조건을 설정합니다. 도메인 제약조건은 릴레이션 스키마에 이미 정의되어 적용되었으므로, 개체 무결성과 참조 무결성을 유지하기 위한 무결성 제약조건을 설정합니다. 아래 절차에 따릅니다.

=== Oracle에 접속하고 현재 데이터베이스 설정

1. 명령 프롬프트를 실행합니다.
2. 아래 명령을 실행하여 Oracle에 SQL Plus로 접속합니다.
+
----
docker exec -it oracle21c sqlplus
----
+
3. `celine` 사용자로 로그인합니다.
+
----
SQL*Plus: Release 21.0.0.0.0 - Production on Tue Aug 6 14:04:14 2024
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Enter user-name: celine
Enter password:
Last Successful login time: Tue Aug 06 2024 13:54:40 +00:00

Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0
----

=== Category 릴레이션에 기본 키 제약조건 설정

1. 아래 명령을 실행하여 테이블을 확인합니다.
+
[source, sql]
----
SELECT TNAME FROM tab;
----
+
결과는 아래와 같을 것입니다.
+
----
TNAME
--------------------------------------------------------------------------------
CATEGORY
PRODUCT
----
+
2. 아래 쿼리를 실행하여 `Category` 테이블의 정보를 확인합니다.
+
[source, sql]
----
desc Category;
----
+
결과는 아래와 같을 것입니다.
+
----
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 CATEGORYNO                                         NUMBER(38)
 CATEGORYNAME                                       VARCHAR2(20)
----
+
3. 아래 쿼리를 실행하여 `Category` 테이블의 제약조건을 확인합니다.
+
[source, sql]
----
SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'CATEGORY';
----
+
결과는 아래와 같을 것입니다.
+
----
no rows selected
----
+
4. 아래 쿼리를 실행하여 `Category` 테이블의 `CategoryNo` 컬럼에 PRIMARY KEY 제약조건을 설정합니다.
+
[source, sql]
----
ALTER TABLE Category ADD CONSTRAINT pk_Category PRIMARY KEY(CategoryNo);
----
+
5. 아래 쿼리를 실행하여 `Category` 테이블의 제약조건을 확인합니다.
+
[source, sql]
----
SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'CATEGORY';
----
+
결과는 아래와 같을 것입니다.
+
----
OWNER
--------------------------------------------------------------------------------
CONSTRAINT_NAME
--------------------------------------------------------------------------------
TABLE_NAME
--------------------------------------------------------------------------------
CELINE
PK_CATEGORY
CATEGORY
----
+
6. 아래 질의를 수행하여 `Category` 테이블의 데이터를 확인합니다.
+
[source, sql]
----
SELECT * FROM Category;
----
+
결과는 아래와 같을 것입니다.
+
----
CATEGORYNO CATEGORYNAME
---------- --------------------
         1 Novel
         3 History
----
+
7. 아래 쿼리를 수행하여 `Category` 테이블에 데이터를 삽입합니다.
+
[source, sql]
----
INSERT INTO Category VALUES (3, 'Science');
----
+
질의는 성공적으로 수행되지 않습니다. `Category` 테이블에 개체 무결성을 위한 기본 키 제약조건(Primary Constraint)이 적용되었고, 기본 키 제약조건에 해당하는 컬럼은 중복되는 값을 저장할 수 없습니다. 결과는 아래와 같습니다.
+
----
INSERT INTO Category VALUES(3, 'Science')
*
ERROR at line 1:
ORA-00001: unique constraint (CELINE.PK_CATEGORY) violated
----

=== Product 릴레이션에 기본 키 제약조건 설정

1. 아래 쿼리를 실행하여 `Product` 테이블의 스키마 정보를 확인합니다.
+
----
desc Product;
----
+
결과는 아래와 같을 것입니다.
+
----
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 PRODUCTNO                                          NUMBER(38)
 PRODUCTNAME                                        VARCHAR2(30)
 PRICE                                              NUMBER(19,4)
 CATEGORYNO                                         NUMBER(38)
----
+
2. 아래 질의를 실행하여 Category 